from building import *
import rtconfig

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = [cwd]

# add LittlevGL common include
src = src + Glob('*.c')

group = DefineGroup('App_watch_demo', src, depend = ['PKG_USING_STREAMING_MEDIA_DEMO_APP'], CPPPATH = inc)

Return('group')
