import os
import rtconfig
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path =  [cwd]
CPPDEFINES = []
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')

