Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src2 = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('databus', src2, depend = [''], CPPPATH = CPPPATH)

Return('group')
