from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../common', cwd]
group = DefineGroup('Drivers', src, depend = ['RGB_SK6812MINI_HS_ENABLE'], CPPPATH = CPPPATH)

Return('group')
