Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('App_bsp_test', src, depend = ['APP_BSP_TEST'], CPPPATH = CPPPATH)

Return('group')
