Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]


try:
    if rtconfig.CODE_IN_RAM:
        CPPDEFINES=['CODE_IN_RAM']
        group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH,CPPDEFINES=CPPDEFINES)
except:
    group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)


Return('group')
