from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../common', cwd]
group = DefineGroup('Drivers', src, depend = ['LCD_USING_ST7789_GTM024_08_SPI8P'], CPPPATH = CPPPATH)

Return('group')
