Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = [cwd]

if GetDepend('BF0_LCPU'):
    src += Glob('bt_audiopath.c')

if GetDepend('BF0_HCPU') and GetDepend('BT_FINSH'):
    src += Glob('*.c')
    if GetDepend('SF32LB58X_3SCO'):
        SrcRemove(src, 'audio_bt_voice_3sco.c')
    else:
        SrcRemove(src, 'audio_bt_voice_3sco.c')


group = DefineGroup('audio', src,depend = ['AUDIO_BT_AUDIO'],CPPPATH = CPPPATH)

Return('group')
