# for module compiling
import os
from building import *
import rtconfig

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

inc = [os.path.join(cwd, 'include')]
Env=GetCurrentEnv()
Env.AppendUnique(CPPPATH = inc)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))    
     
Return('objs')

