Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []

CPPPATH = [cwd]
list = os.listdir(cwd)

#lib = lib_bt_rvds

src = Glob('bluetooth.c')

objs = DefineGroup('bt', src, depend = ['BLUETOOTH'], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))    

if not GetDepend('BSP_USING_RTTHREAD'):
    objs=[]
Return('objs')
