Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

if GetDepend('PKG_USING_3MICS'):
    src = []
elif GetDepend('PKG_USING_SOUNDPLUS'):
    src = Glob('audio_3a_soundplus.c')
else:
    src = Glob('audio_3a.c')

if not GetDepend('BLUETOOTH'):
    SrcRemove(src, './audio_3a.c')
    SrcRemove(src, './audio_3a_soundplus.c')
    src += Glob('./audio_3a_dummy.c')

if GetDepend('AUDIO_FREQSHIFT'):
    src += ['audio_freqshift.c']

if GetDepend('AUDIO_SOFTEQ'):
    src += ['audio_softeq.c']
    
group = DefineGroup('audio', src,depend = ['AUDIO_USING_AUDPROC'],CPPPATH = CPPPATH)

Return('group')
