from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../common', cwd]
group = DefineGroup('Drivers', src, depend = ['TSC_USING_CST918_0x15'], CPPPATH = CPPPATH)

Return('group')
