import os
from building import *

# Add source code
src = Glob('*.c')


CPPDEFINES=[]
if GetDepend('SOC_SF32LB58X'):
    CPPDEFINES += ['SF32LB52X_58']
    CPPDEFINES += ['SF32LB58X_3SCO']
else:
    SrcRemove(src, 'lcpu_img.c')

group = DefineGroup('Applications', src, depend = [''], CPPDEFINES=CPPDEFINES)

Return('group')
