from building import *
import rtconfig
import os

src = []
inc = []
cwd = GetCurrentDir() # get current dir path

src+=Glob('*.c')
inc+= [cwd]

group = DefineGroup('LVGL_DEMO', src, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = inc)
Return('group')
