Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, 
    str(Dir('#')),
    '../../../../../middleware/sibles']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
