/*Auto generated configuration*/
#ifndef RT_CONFIG_H
#define RT_CONFIG_H

#define SOC_SF32LB52X 1
#define CORE "HCPU"
#define CPU "Cortex-M33"
#define BSP_USING_BOARD_EH_SS6500XXX 1
#define LXT_FREQ 32768
#define LXT_LP_CYCLE 200
#define BT_TX_POWER_VAL 1
#define BT_TX_POWER_VAL_MAX 10
#define BT_TX_POWER_VAL_MIN 0
#define BT_TX_POWER_VAL_INIT 0
#define ASIC 1
#define TOUCH_IRQ_PIN 43
#define LCD_PWM_BACKLIGHT_INTERFACE_NAME "pwm3"
#define LCD_PWM_BACKLIGHT_CHANEL_NUM 4
#define LCD_BACKLIGHT_CONTROL_PIN 1
#define BSP_USING_GPIO 1
#define BSP_GPIO_HANDLE 2
#define BSP_USING_DMA 1
#define BSP_USING_UART 1
#define BSP_USING_MPI 1
#define BSP_USING_SPI_FLASH 1
#define BSP_ENABLE_MPI5 1
#define BSP_ENABLE_QSPI5 1
#define BSP_MPI5_MODE_0 1
#define BSP_QSPI5_MODE 0
#define BSP_USING_NOR_FLASH5 1
#define BSP_QSPI5_USING_DMA 1
#define BSP_QSPI5_MEM_SIZE 4
#define BSP_USING_EXT_DMA 1
#define BSP_USING_HW_AES 1
#define BSP_USING_NO_OS 1
#define RT_USING_SERIAL 1
#define RT_USING_PIN 1
#define RT_USING_LIBC 1
#define BSP_USING_EMPTY_ASSERT 1
#define USING_PARTITION_TABLE 1
#define PKG_SIFLI_MBEDTLS_BOOT 1
#define BF0_HCPU 1
#define CFG_BOOTLOADER 1
#define CUSTOM_MEM_MAP 1
#endif
