Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = []
cwd = GetCurrentDir()
CPPPATH = [cwd]

if GetDepend('PKG_USING_SOUNDPLUS'):
    src = Glob('*.c')

group = DefineGroup('audio', src,depend = ['PKG_USING_SOUNDPLUS'],CPPPATH = CPPPATH)

Return('group')
