from building import *
Import('rtconfig')

src   = []
CPPPATH = []
cwd   = GetCurrentDir()

src += ['bf0_common.c']
if GetDepend(['BSP_USING_PM']):
    src += ['bf0_pm.c']
if GetDepend(['GUI_APP_PM']):
    src += ['gui_app_pm.c']
  
if (GetDepend(['SOC_SF32LB58X']) or GetDepend(['SOC_SF32LB56X'])) and  ((GetDepend(['BF0_LCPU']) and GetDepend(['FPGA'])) or GetDepend(['CFG_EMB'])):
    if not GetDepend('BSP_USING_PC_SIMULATOR'):
        CPPPATH += [cwd+'/../gap']    

CPPPATH += [cwd+'/../include']    

# add src and include to group.
group = DefineGroup('m_system', src,depend = ['BSP_USING_RTTHREAD'],CPPPATH = CPPPATH)
    
Return('group')
