#ifndef __JPEGENC_H
#define __JPEGENC_H

typedef struct
{
    __IO uint32_t SWREG0;
    __IO uint32_t SWREG1;
    __IO uint32_t SWREG2;
    __IO uint32_t SWREG3;
    __IO uint32_t RSVD11;
    __IO uint32_t SWREG5;
    __IO uint32_t SWREG6;
    __IO uint32_t SWREG7;
    __IO uint32_t SWREG8;
    __IO uint32_t SWREG9;
    __IO uint32_t SWREG10;
    __IO uint32_t SWREG11;
    __IO uint32_t SWREG12;
    __IO uint32_t SWREG13;
    __IO uint32_t SWREG14;
    __IO uint32_t SWREG15;
    __IO uint32_t SWREG16;
    __IO uint32_t SWREG17;
    __IO uint32_t SWREG18;
    __IO uint32_t SWREG19;
    __IO uint32_t SWREG20;
    __IO uint32_t SWREG21;
    __IO uint32_t SWREG22;
    __IO uint32_t SWREG23;
    __IO uint32_t SWREG24;
    __IO uint32_t SWREG25;
    __IO uint32_t SWREG26;
    __IO uint32_t SWREG27;
    __IO uint32_t SWREG28;
    __IO uint32_t SWREG29;
    __IO uint32_t SWREG30;
    __IO uint32_t SWREG31;
    __IO uint32_t SWREG32;
    __IO uint32_t SWREG33;
    __IO uint32_t SWREG34;
    __IO uint32_t SWREG35;
    __IO uint32_t SWREG36;
    __IO uint32_t SWREG37;
    __IO uint32_t SWREG38;
    __IO uint32_t SWREG39;
    __IO uint32_t RSVD10[11];
    __IO uint32_t SWREG51;
    __IO uint32_t SWREG52;
    __IO uint32_t SWREG53;
    __IO uint32_t SWREG54;
    __IO uint32_t SWREG55;
    __IO uint32_t SWREG56;
    __IO uint32_t SWREG57;
    __IO uint32_t SWREG58;
    __IO uint32_t SWREG59;
    __IO uint32_t SWREG60;
    __IO uint32_t SWREG61;
    __IO uint32_t SWREG62;
    __IO uint32_t SWREG63;
    __IO uint32_t SWREG64;
    __IO uint32_t SWREG65;
    __IO uint32_t SWREG66;
    __IO uint32_t SWREG67;
    __IO uint32_t SWREG68;
    __IO uint32_t SWREG69;
    __IO uint32_t SWREG70;
    __IO uint32_t SWREG71;
    __IO uint32_t SWREG72;
    __IO uint32_t SWREG73;
    __IO uint32_t SWREG74;
    __IO uint32_t SWREG75;
    __IO uint32_t SWREG76;
    __IO uint32_t SWREG77;
    __IO uint32_t SWREG78;
    __IO uint32_t SWREG79;
    __IO uint32_t SWREG80;
    __IO uint32_t SWREG81;
    __IO uint32_t SWREG82;
    __IO uint32_t SWREG83;
    __IO uint32_t SWREG84;
    __IO uint32_t SWREG85;
    __IO uint32_t SWREG86;
    __IO uint32_t SWREG87;
    __IO uint32_t SWREG88;
    __IO uint32_t SWREG89;
    __IO uint32_t SWREG90;
    __IO uint32_t SWREG91;
    __IO uint32_t SWREG92;
    __IO uint32_t SWREG93;
    __IO uint32_t SWREG94;
    __IO uint32_t SWREG95;
    __IO uint32_t RSVD9[64];
    __IO uint32_t SWREG160;
    __IO uint32_t RSVD8[70];
    __IO uint32_t SWREG231;
    __IO uint32_t SWREG232;
    __IO uint32_t SWREG233;
    __IO uint32_t RSVD7[10];
    __IO uint32_t SWREG244;
    __IO uint32_t SWREG245;
    __IO uint32_t RSVD6[15];
    __IO uint32_t SWREG261;
    __IO uint32_t SWREG262;
    __IO uint32_t RSVD5[10];
    __IO uint32_t SWREG273;
    __IO uint32_t SWREG274;
    __IO uint32_t RSVD4[10];
    __IO uint32_t SWREG285;
    __IO uint32_t SWREG286;
    __IO uint32_t RSVD3[5];
    __IO uint32_t SWREG292;
    __IO uint32_t SWREG293;
    __IO uint32_t SWREG294;
    __IO uint32_t SWREG295;
    __IO uint32_t SWREG296;
    __IO uint32_t RSVD2[113];
    __IO uint32_t SWREG410;
    __IO uint32_t SWREG411;
    __IO uint32_t SWREG412;
    __IO uint32_t RSVD1[84];
    __IO uint32_t SWREG497;
    __IO uint32_t SWREG498;
} JPEGENC_TypeDef;


/***************** Bit definition for JPEGENC_SWREG0 register *****************/
#define JPEGENC_SWREG0_BN_Pos           (0U)
#define JPEGENC_SWREG0_BN_Msk           (0xFUL << JPEGENC_SWREG0_BN_Pos)
#define JPEGENC_SWREG0_BN               JPEGENC_SWREG0_BN_Msk
#define JPEGENC_SWREG0_MINORN_Pos       (4U)
#define JPEGENC_SWREG0_MINORN_Msk       (0xFFUL << JPEGENC_SWREG0_MINORN_Pos)
#define JPEGENC_SWREG0_MINORN           JPEGENC_SWREG0_MINORN_Msk
#define JPEGENC_SWREG0_MAJORN_Pos       (12U)
#define JPEGENC_SWREG0_MAJORN_Msk       (0xFUL << JPEGENC_SWREG0_MAJORN_Pos)
#define JPEGENC_SWREG0_MAJORN           JPEGENC_SWREG0_MAJORN_Msk
#define JPEGENC_SWREG0_PID_Pos          (16U)
#define JPEGENC_SWREG0_PID_Msk          (0xFFFFUL << JPEGENC_SWREG0_PID_Pos)
#define JPEGENC_SWREG0_PID              JPEGENC_SWREG0_PID_Msk

/***************** Bit definition for JPEGENC_SWREG1 register *****************/
#define JPEGENC_SWREG1_HINTENC_Pos      (0U)
#define JPEGENC_SWREG1_HINTENC_Msk      (0x1UL << JPEGENC_SWREG1_HINTENC_Pos)
#define JPEGENC_SWREG1_HINTENC          JPEGENC_SWREG1_HINTENC_Msk
#define JPEGENC_SWREG1_IRQ_DISABLE_Pos  (1U)
#define JPEGENC_SWREG1_IRQ_DISABLE_Msk  (0x1UL << JPEGENC_SWREG1_IRQ_DISABLE_Pos)
#define JPEGENC_SWREG1_IRQ_DISABLE      JPEGENC_SWREG1_IRQ_DISABLE_Msk
#define JPEGENC_SWREG1_IRQ_FRDY_Pos     (2U)
#define JPEGENC_SWREG1_IRQ_FRDY_Msk     (0x1UL << JPEGENC_SWREG1_IRQ_FRDY_Pos)
#define JPEGENC_SWREG1_IRQ_FRDY         JPEGENC_SWREG1_IRQ_FRDY_Msk
#define JPEGENC_SWREG1_IRQ_BUS_ERR_Pos  (3U)
#define JPEGENC_SWREG1_IRQ_BUS_ERR_Msk  (0x1UL << JPEGENC_SWREG1_IRQ_BUS_ERR_Pos)
#define JPEGENC_SWREG1_IRQ_BUS_ERR      JPEGENC_SWREG1_IRQ_BUS_ERR_Msk
#define JPEGENC_SWREG1_IRQ_SW_RESET_Pos  (4U)
#define JPEGENC_SWREG1_IRQ_SW_RESET_Msk  (0x1UL << JPEGENC_SWREG1_IRQ_SW_RESET_Pos)
#define JPEGENC_SWREG1_IRQ_SW_RESET     JPEGENC_SWREG1_IRQ_SW_RESET_Msk
#define JPEGENC_SWREG1_IRQ_BUF_FUL_Pos  (5U)
#define JPEGENC_SWREG1_IRQ_BUF_FUL_Msk  (0x1UL << JPEGENC_SWREG1_IRQ_BUF_FUL_Pos)
#define JPEGENC_SWREG1_IRQ_BUF_FUL      JPEGENC_SWREG1_IRQ_BUF_FUL_Msk
#define JPEGENC_SWREG1_IRQ_HW_TO_Pos    (6U)
#define JPEGENC_SWREG1_IRQ_HW_TO_Msk    (0x1UL << JPEGENC_SWREG1_IRQ_HW_TO_Pos)
#define JPEGENC_SWREG1_IRQ_HW_TO        JPEGENC_SWREG1_IRQ_HW_TO_Msk
#define JPEGENC_SWREG1_IRQ_SLICE_RDY_Pos  (8U)
#define JPEGENC_SWREG1_IRQ_SLICE_RDY_Msk  (0x1UL << JPEGENC_SWREG1_IRQ_SLICE_RDY_Pos)
#define JPEGENC_SWREG1_IRQ_SLICE_RDY    JPEGENC_SWREG1_IRQ_SLICE_RDY_Msk
#define JPEGENC_SWREG1_IRQ_SF_FUSE_Pos  (9U)
#define JPEGENC_SWREG1_IRQ_SF_FUSE_Msk  (0x1UL << JPEGENC_SWREG1_IRQ_SF_FUSE_Pos)
#define JPEGENC_SWREG1_IRQ_SF_FUSE      JPEGENC_SWREG1_IRQ_SF_FUSE_Msk

/***************** Bit definition for JPEGENC_SWREG2 register *****************/
#define JPEGENC_SWREG2_ISWAP8_Pos       (0U)
#define JPEGENC_SWREG2_ISWAP8_Msk       (0x1UL << JPEGENC_SWREG2_ISWAP8_Pos)
#define JPEGENC_SWREG2_ISWAP8           JPEGENC_SWREG2_ISWAP8_Msk
#define JPEGENC_SWREG2_OSWAP8_Pos       (1U)
#define JPEGENC_SWREG2_OSWAP8_Msk       (0x1UL << JPEGENC_SWREG2_OSWAP8_Pos)
#define JPEGENC_SWREG2_OSWAP8           JPEGENC_SWREG2_OSWAP8_Msk
#define JPEGENC_SWREG2_ISWAP32_Pos      (2U)
#define JPEGENC_SWREG2_ISWAP32_Msk      (0x1UL << JPEGENC_SWREG2_ISWAP32_Pos)
#define JPEGENC_SWREG2_ISWAP32          JPEGENC_SWREG2_ISWAP32_Msk
#define JPEGENC_SWREG2_OSWAP32_Pos      (3U)
#define JPEGENC_SWREG2_OSWAP32_Msk      (0x1UL << JPEGENC_SWREG2_OSWAP32_Pos)
#define JPEGENC_SWREG2_OSWAP32          JPEGENC_SWREG2_OSWAP32_Msk
#define JPEGENC_SWREG2_CG_EN_Pos        (4U)
#define JPEGENC_SWREG2_CG_EN_Msk        (0x1UL << JPEGENC_SWREG2_CG_EN_Pos)
#define JPEGENC_SWREG2_CG_EN            JPEGENC_SWREG2_CG_EN_Msk
#define JPEGENC_SWREG2_DATA_DIS_EN_Pos  (5U)
#define JPEGENC_SWREG2_DATA_DIS_EN_Msk  (0x1UL << JPEGENC_SWREG2_DATA_DIS_EN_Pos)
#define JPEGENC_SWREG2_DATA_DIS_EN      JPEGENC_SWREG2_DATA_DIS_EN_Msk
#define JPEGENC_SWREG2_BURST_INC_Pos    (6U)
#define JPEGENC_SWREG2_BURST_INC_Msk    (0x1UL << JPEGENC_SWREG2_BURST_INC_Pos)
#define JPEGENC_SWREG2_BURST_INC        JPEGENC_SWREG2_BURST_INC_Msk
#define JPEGENC_SWREG2_BURST_DIS_Pos    (7U)
#define JPEGENC_SWREG2_BURST_DIS_Msk    (0x1UL << JPEGENC_SWREG2_BURST_DIS_Pos)
#define JPEGENC_SWREG2_BURST_DIS        JPEGENC_SWREG2_BURST_DIS_Msk
#define JPEGENC_SWREG2_BURST_LEN_Pos    (8U)
#define JPEGENC_SWREG2_BURST_LEN_Msk    (0x3FUL << JPEGENC_SWREG2_BURST_LEN_Pos)
#define JPEGENC_SWREG2_BURST_LEN        JPEGENC_SWREG2_BURST_LEN_Msk
#define JPEGENC_SWREG2_ISWAP16_Pos      (14U)
#define JPEGENC_SWREG2_ISWAP16_Msk      (0x1UL << JPEGENC_SWREG2_ISWAP16_Pos)
#define JPEGENC_SWREG2_ISWAP16          JPEGENC_SWREG2_ISWAP16_Msk
#define JPEGENC_SWREG2_OSWAP16_Pos      (15U)
#define JPEGENC_SWREG2_OSWAP16_Msk      (0x1UL << JPEGENC_SWREG2_OSWAP16_Pos)
#define JPEGENC_SWREG2_OSWAP16          JPEGENC_SWREG2_OSWAP16_Msk
#define JPEGENC_SWREG2_AXI_RID_Pos      (16U)
#define JPEGENC_SWREG2_AXI_RID_Msk      (0xFFUL << JPEGENC_SWREG2_AXI_RID_Pos)
#define JPEGENC_SWREG2_AXI_RID          JPEGENC_SWREG2_AXI_RID_Msk
#define JPEGENC_SWREG2_AXI_WID_Pos      (24U)
#define JPEGENC_SWREG2_AXI_WID_Msk      (0xFFUL << JPEGENC_SWREG2_AXI_WID_Pos)
#define JPEGENC_SWREG2_AXI_WID          JPEGENC_SWREG2_AXI_WID_Msk

/***************** Bit definition for JPEGENC_SWREG3 register *****************/
#define JPEGENC_SWREG3_BUS_TIM_EN_Pos   (0U)
#define JPEGENC_SWREG3_BUS_TIM_EN_Msk   (0x1UL << JPEGENC_SWREG3_BUS_TIM_EN_Pos)
#define JPEGENC_SWREG3_BUS_TIM_EN       JPEGENC_SWREG3_BUS_TIM_EN_Msk
#define JPEGENC_SWREG3_DUAL_CH_DIS_Pos  (20U)
#define JPEGENC_SWREG3_DUAL_CH_DIS_Msk  (0x1UL << JPEGENC_SWREG3_DUAL_CH_DIS_Pos)
#define JPEGENC_SWREG3_DUAL_CH_DIS      JPEGENC_SWREG3_DUAL_CH_DIS_Msk
#define JPEGENC_SWREG3_CHK_SIZE_Pos     (21U)
#define JPEGENC_SWREG3_CHK_SIZE_Msk     (0x1UL << JPEGENC_SWREG3_CHK_SIZE_Pos)
#define JPEGENC_SWREG3_CHK_SIZE         JPEGENC_SWREG3_CHK_SIZE_Msk
#define JPEGENC_SWREG3_OM_SWAP32_Pos    (22U)
#define JPEGENC_SWREG3_OM_SWAP32_Msk    (0x1UL << JPEGENC_SWREG3_OM_SWAP32_Pos)
#define JPEGENC_SWREG3_OM_SWAP32        JPEGENC_SWREG3_OM_SWAP32_Msk
#define JPEGENC_SWREG3_OM_SWAP16_Pos    (23U)
#define JPEGENC_SWREG3_OM_SWAP16_Msk    (0x1UL << JPEGENC_SWREG3_OM_SWAP16_Pos)
#define JPEGENC_SWREG3_OM_SWAP16        JPEGENC_SWREG3_OM_SWAP16_Msk
#define JPEGENC_SWREG3_OM_SWAP8_Pos     (24U)
#define JPEGENC_SWREG3_OM_SWAP8_Msk     (0x1UL << JPEGENC_SWREG3_OM_SWAP8_Pos)
#define JPEGENC_SWREG3_OM_SWAP8         JPEGENC_SWREG3_OM_SWAP8_Msk
#define JPEGENC_SWREG3_OSI_SWAP32_Pos   (25U)
#define JPEGENC_SWREG3_OSI_SWAP32_Msk   (0x1UL << JPEGENC_SWREG3_OSI_SWAP32_Pos)
#define JPEGENC_SWREG3_OSI_SWAP32       JPEGENC_SWREG3_OSI_SWAP32_Msk
#define JPEGENC_SWREG3_OSI_SWAP16_Pos   (26U)
#define JPEGENC_SWREG3_OSI_SWAP16_Msk   (0x1UL << JPEGENC_SWREG3_OSI_SWAP16_Pos)
#define JPEGENC_SWREG3_OSI_SWAP16       JPEGENC_SWREG3_OSI_SWAP16_Msk
#define JPEGENC_SWREG3_OSI_SWAP8_Pos    (27U)
#define JPEGENC_SWREG3_OSI_SWAP8_Msk    (0x1UL << JPEGENC_SWREG3_OSI_SWAP8_Pos)
#define JPEGENC_SWREG3_OSI_SWAP8        JPEGENC_SWREG3_OSI_SWAP8_Msk

/***************** Bit definition for JPEGENC_SWREG5 register *****************/
#define JPEGENC_SWREG5_OS_ADDR_Pos      (0U)
#define JPEGENC_SWREG5_OS_ADDR_Msk      (0xFFFFFFFFUL << JPEGENC_SWREG5_OS_ADDR_Pos)
#define JPEGENC_SWREG5_OS_ADDR          JPEGENC_SWREG5_OS_ADDR_Msk

/***************** Bit definition for JPEGENC_SWREG6 register *****************/
#define JPEGENC_SWREG6_OC_ADDR_Pos      (0U)
#define JPEGENC_SWREG6_OC_ADDR_Msk      (0xFFFFFFFFUL << JPEGENC_SWREG6_OC_ADDR_Pos)
#define JPEGENC_SWREG6_OC_ADDR          JPEGENC_SWREG6_OC_ADDR_Msk

/***************** Bit definition for JPEGENC_SWREG7 register *****************/
#define JPEGENC_SWREG7_RL_ADDR_Pos      (0U)
#define JPEGENC_SWREG7_RL_ADDR_Msk      (0xFFFFFFFFUL << JPEGENC_SWREG7_RL_ADDR_Pos)
#define JPEGENC_SWREG7_RL_ADDR          JPEGENC_SWREG7_RL_ADDR_Msk

/***************** Bit definition for JPEGENC_SWREG8 register *****************/
#define JPEGENC_SWREG8_RC_ADDR_Pos      (0U)
#define JPEGENC_SWREG8_RC_ADDR_Msk      (0xFFFFFFFFUL << JPEGENC_SWREG8_RC_ADDR_Pos)
#define JPEGENC_SWREG8_RC_ADDR          JPEGENC_SWREG8_RC_ADDR_Msk

/***************** Bit definition for JPEGENC_SWREG9 register *****************/
#define JPEGENC_SWREG9_RECL_ADDR_Pos    (0U)
#define JPEGENC_SWREG9_RECL_ADDR_Msk    (0xFFFFFFFFUL << JPEGENC_SWREG9_RECL_ADDR_Pos)
#define JPEGENC_SWREG9_RECL_ADDR        JPEGENC_SWREG9_RECL_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG10 register *****************/
#define JPEGENC_SWREG10_RECC_ADDR_Pos   (0U)
#define JPEGENC_SWREG10_RECC_ADDR_Msk   (0xFFFFFFFFUL << JPEGENC_SWREG10_RECC_ADDR_Pos)
#define JPEGENC_SWREG10_RECC_ADDR       JPEGENC_SWREG10_RECC_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG11 register *****************/
#define JPEGENC_SWREG11_IPL_ADDR_Pos    (0U)
#define JPEGENC_SWREG11_IPL_ADDR_Msk    (0xFFFFFFFFUL << JPEGENC_SWREG11_IPL_ADDR_Pos)
#define JPEGENC_SWREG11_IPL_ADDR        JPEGENC_SWREG11_IPL_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG12 register *****************/
#define JPEGENC_SWREG12_IPCB_ADDR_Pos   (0U)
#define JPEGENC_SWREG12_IPCB_ADDR_Msk   (0xFFFFFFFFUL << JPEGENC_SWREG12_IPCB_ADDR_Pos)
#define JPEGENC_SWREG12_IPCB_ADDR       JPEGENC_SWREG12_IPCB_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG13 register *****************/
#define JPEGENC_SWREG13_IPCR_ADDR_Pos   (0U)
#define JPEGENC_SWREG13_IPCR_ADDR_Msk   (0xFFFFFFFFUL << JPEGENC_SWREG13_IPCR_ADDR_Pos)
#define JPEGENC_SWREG13_IPCR_ADDR       JPEGENC_SWREG13_IPCR_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG14 register *****************/
#define JPEGENC_SWREG14_ENC_EN_Pos      (0U)
#define JPEGENC_SWREG14_ENC_EN_Msk      (0x1UL << JPEGENC_SWREG14_ENC_EN_Pos)
#define JPEGENC_SWREG14_ENC_EN          JPEGENC_SWREG14_ENC_EN_Msk
#define JPEGENC_SWREG14_ENC_MODE_Pos    (1U)
#define JPEGENC_SWREG14_ENC_MODE_Msk    (0x3UL << JPEGENC_SWREG14_ENC_MODE_Pos)
#define JPEGENC_SWREG14_ENC_MODE        JPEGENC_SWREG14_ENC_MODE_Msk
#define JPEGENC_SWREG14_ENC_PT_Pos      (3U)
#define JPEGENC_SWREG14_ENC_PT_Msk      (0x3UL << JPEGENC_SWREG14_ENC_PT_Pos)
#define JPEGENC_SWREG14_ENC_PT          JPEGENC_SWREG14_ENC_PT_Msk
#define JPEGENC_SWREG14_REGWR_DIS_Pos   (6U)
#define JPEGENC_SWREG14_REGWR_DIS_Msk   (0x1UL << JPEGENC_SWREG14_REGWR_DIS_Pos)
#define JPEGENC_SWREG14_REGWR_DIS       JPEGENC_SWREG14_REGWR_DIS_Msk
#define JPEGENC_SWREG14_REC_IMG_SIZE_Pos  (7U)
#define JPEGENC_SWREG14_REC_IMG_SIZE_Msk  (0x1UL << JPEGENC_SWREG14_REC_IMG_SIZE_Pos)
#define JPEGENC_SWREG14_REC_IMG_SIZE    JPEGENC_SWREG14_REC_IMG_SIZE_Msk
#define JPEGENC_SWREG14_ENC_HEIGHT_Pos  (10U)
#define JPEGENC_SWREG14_ENC_HEIGHT_Msk  (0x1FFUL << JPEGENC_SWREG14_ENC_HEIGHT_Pos)
#define JPEGENC_SWREG14_ENC_HEIGHT      JPEGENC_SWREG14_ENC_HEIGHT_Msk
#define JPEGENC_SWREG14_ENC_WIDTH_Pos   (19U)
#define JPEGENC_SWREG14_ENC_WIDTH_Msk   (0x1FFUL << JPEGENC_SWREG14_ENC_WIDTH_Pos)
#define JPEGENC_SWREG14_ENC_WIDTH       JPEGENC_SWREG14_ENC_WIDTH_Msk
#define JPEGENC_SWREG14_SR_IRQ_EN_Pos   (28U)
#define JPEGENC_SWREG14_SR_IRQ_EN_Msk   (0x1UL << JPEGENC_SWREG14_SR_IRQ_EN_Pos)
#define JPEGENC_SWREG14_SR_IRQ_EN       JPEGENC_SWREG14_SR_IRQ_EN_Msk
#define JPEGENC_SWREG14_WS_EN_Pos       (29U)
#define JPEGENC_SWREG14_WS_EN_Msk       (0x1UL << JPEGENC_SWREG14_WS_EN_Pos)
#define JPEGENC_SWREG14_WS_EN           JPEGENC_SWREG14_WS_EN_Msk
#define JPEGENC_SWREG14_MV_SAD_EN_Pos   (30U)
#define JPEGENC_SWREG14_MV_SAD_EN_Msk   (0x1UL << JPEGENC_SWREG14_MV_SAD_EN_Pos)
#define JPEGENC_SWREG14_MV_SAD_EN       JPEGENC_SWREG14_MV_SAD_EN_Msk
#define JPEGENC_SWREG14_TO_IRQ_EN_Pos   (31U)
#define JPEGENC_SWREG14_TO_IRQ_EN_Msk   (0x1UL << JPEGENC_SWREG14_TO_IRQ_EN_Pos)
#define JPEGENC_SWREG14_TO_IRQ_EN       JPEGENC_SWREG14_TO_IRQ_EN_Msk

/**************** Bit definition for JPEGENC_SWREG15 register *****************/
#define JPEGENC_SWREG15_II_ROT_Pos      (0U)
#define JPEGENC_SWREG15_II_ROT_Msk      (0x3UL << JPEGENC_SWREG15_II_ROT_Pos)
#define JPEGENC_SWREG15_II_ROT          JPEGENC_SWREG15_II_ROT_Msk
#define JPEGENC_SWREG15_IIF_Pos         (2U)
#define JPEGENC_SWREG15_IIF_Msk         (0xFUL << JPEGENC_SWREG15_IIF_Pos)
#define JPEGENC_SWREG15_IIF             JPEGENC_SWREG15_IIF_Msk
#define JPEGENC_SWREG15_OVERFIL_PIX_BOT_Pos  (6U)
#define JPEGENC_SWREG15_OVERFIL_PIX_BOT_Msk  (0xFUL << JPEGENC_SWREG15_OVERFIL_PIX_BOT_Pos)
#define JPEGENC_SWREG15_OVERFIL_PIX_BOT  JPEGENC_SWREG15_OVERFIL_PIX_BOT_Msk
#define JPEGENC_SWREG15_OVERFILL_PIX_R_Pos  (10U)
#define JPEGENC_SWREG15_OVERFILL_PIX_R_Msk  (0x3UL << JPEGENC_SWREG15_OVERFILL_PIX_R_Pos)
#define JPEGENC_SWREG15_OVERFILL_PIX_R  JPEGENC_SWREG15_OVERFILL_PIX_R_Msk
#define JPEGENC_SWREG15_IL_ROW_LEN_Pos  (12U)
#define JPEGENC_SWREG15_IL_ROW_LEN_Msk  (0x3FFFUL << JPEGENC_SWREG15_IL_ROW_LEN_Pos)
#define JPEGENC_SWREG15_IL_ROW_LEN      JPEGENC_SWREG15_IL_ROW_LEN_Msk
#define JPEGENC_SWREG15_IL_OFFSET_Pos   (26U)
#define JPEGENC_SWREG15_IL_OFFSET_Msk   (0x7UL << JPEGENC_SWREG15_IL_OFFSET_Pos)
#define JPEGENC_SWREG15_IL_OFFSET       JPEGENC_SWREG15_IL_OFFSET_Msk
#define JPEGENC_SWREG15_IC_OFFSET_Pos   (29U)
#define JPEGENC_SWREG15_IC_OFFSET_Msk   (0x7UL << JPEGENC_SWREG15_IC_OFFSET_Pos)
#define JPEGENC_SWREG15_IC_OFFSET       JPEGENC_SWREG15_IC_OFFSET_Msk

/**************** Bit definition for JPEGENC_SWREG16 register *****************/
#define JPEGENC_SWREG16_SRL_ADDR_Pos    (0U)
#define JPEGENC_SWREG16_SRL_ADDR_Msk    (0xFFFFFFFFUL << JPEGENC_SWREG16_SRL_ADDR_Pos)
#define JPEGENC_SWREG16_SRL_ADDR        JPEGENC_SWREG16_SRL_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG17 register *****************/
#define JPEGENC_SWREG17_SRC_ADDR_Pos    (0U)
#define JPEGENC_SWREG17_SRC_ADDR_Msk    (0xFFFFFFFFUL << JPEGENC_SWREG17_SRC_ADDR_Pos)
#define JPEGENC_SWREG17_SRC_ADDR        JPEGENC_SWREG17_SRC_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG18 register *****************/
#define JPEGENC_SWREG18_IP_MODE_FAVOR_Pos  (0U)
#define JPEGENC_SWREG18_IP_MODE_FAVOR_Msk  (0xFFFFUL << JPEGENC_SWREG18_IP_MODE_FAVOR_Pos)
#define JPEGENC_SWREG18_IP_MODE_FAVOR   JPEGENC_SWREG18_IP_MODE_FAVOR_Msk
#define JPEGENC_SWREG18_S_MODE_Pos      (16U)
#define JPEGENC_SWREG18_S_MODE_Msk      (0x1UL << JPEGENC_SWREG18_S_MODE_Pos)
#define JPEGENC_SWREG18_S_MODE          JPEGENC_SWREG18_S_MODE_Msk
#define JPEGENC_SWREG18_RESTRICT_44_MODE_Pos  (17U)
#define JPEGENC_SWREG18_RESTRICT_44_MODE_Msk  (0x1UL << JPEGENC_SWREG18_RESTRICT_44_MODE_Pos)
#define JPEGENC_SWREG18_RESTRICT_44_MODE  JPEGENC_SWREG18_RESTRICT_44_MODE_Msk
#define JPEGENC_SWREG18_BOOLENC_EN_Pos  (18U)
#define JPEGENC_SWREG18_BOOLENC_EN_Msk  (0x1UL << JPEGENC_SWREG18_BOOLENC_EN_Pos)
#define JPEGENC_SWREG18_BOOLENC_EN      JPEGENC_SWREG18_BOOLENC_EN_Msk
#define JPEGENC_SWREG18_CABAC_INIT_Pos  (19U)
#define JPEGENC_SWREG18_CABAC_INIT_Msk  (0x3UL << JPEGENC_SWREG18_CABAC_INIT_Pos)
#define JPEGENC_SWREG18_CABAC_INIT      JPEGENC_SWREG18_CABAC_INIT_Msk
#define JPEGENC_SWREG18_TRANS_EN_Pos    (21U)
#define JPEGENC_SWREG18_TRANS_EN_Msk    (0x1UL << JPEGENC_SWREG18_TRANS_EN_Pos)
#define JPEGENC_SWREG18_TRANS_EN        JPEGENC_SWREG18_TRANS_EN_Msk
#define JPEGENC_SWREG18_DIS_QPM_Pos     (22U)
#define JPEGENC_SWREG18_DIS_QPM_Msk     (0x1UL << JPEGENC_SWREG18_DIS_QPM_Pos)
#define JPEGENC_SWREG18_DIS_QPM         JPEGENC_SWREG18_DIS_QPM_Msk
#define JPEGENC_SWREG18_SLICE_SIZE_Pos  (23U)
#define JPEGENC_SWREG18_SLICE_SIZE_Msk  (0x7FUL << JPEGENC_SWREG18_SLICE_SIZE_Pos)
#define JPEGENC_SWREG18_SLICE_SIZE      JPEGENC_SWREG18_SLICE_SIZE_Msk
#define JPEGENC_SWREG18_DFM_Pos         (30U)
#define JPEGENC_SWREG18_DFM_Msk         (0x3UL << JPEGENC_SWREG18_DFM_Pos)
#define JPEGENC_SWREG18_DFM             JPEGENC_SWREG18_DFM_Msk

/**************** Bit definition for JPEGENC_SWREG19 register *****************/
#define JPEGENC_SWREG19_DMVP1P_Pos      (0U)
#define JPEGENC_SWREG19_DMVP1P_Msk      (0x3FFUL << JPEGENC_SWREG19_DMVP1P_Pos)
#define JPEGENC_SWREG19_DMVP1P          JPEGENC_SWREG19_DMVP1P_Msk
#define JPEGENC_SWREG19_DMVP4P_Pos      (10U)
#define JPEGENC_SWREG19_DMVP4P_Msk      (0x3FFUL << JPEGENC_SWREG19_DMVP4P_Pos)
#define JPEGENC_SWREG19_DMVP4P          JPEGENC_SWREG19_DMVP4P_Msk
#define JPEGENC_SWREG19_DMVPQP_Pos      (20U)
#define JPEGENC_SWREG19_DMVPQP_Msk      (0x3FFUL << JPEGENC_SWREG19_DMVPQP_Pos)
#define JPEGENC_SWREG19_DMVPQP          JPEGENC_SWREG19_DMVPQP_Msk
#define JPEGENC_SWREG19_MMP_EN_Pos      (30U)
#define JPEGENC_SWREG19_MMP_EN_Msk      (0x1UL << JPEGENC_SWREG19_MMP_EN_Pos)
#define JPEGENC_SWREG19_MMP_EN          JPEGENC_SWREG19_MMP_EN_Msk
#define JPEGENC_SWREG19_CB_SWAP_Pos     (31U)
#define JPEGENC_SWREG19_CB_SWAP_Msk     (0x1UL << JPEGENC_SWREG19_CB_SWAP_Pos)
#define JPEGENC_SWREG19_CB_SWAP         JPEGENC_SWREG19_CB_SWAP_Msk

/**************** Bit definition for JPEGENC_SWREG20 register *****************/
#define JPEGENC_SWREG20_RES_MK_FR_Pos   (0U)
#define JPEGENC_SWREG20_RES_MK_FR_Msk   (0xFFFFUL << JPEGENC_SWREG20_RES_MK_FR_Pos)
#define JPEGENC_SWREG20_RES_MK_FR       JPEGENC_SWREG20_RES_MK_FR_Msk
#define JPEGENC_SWREG20_RES_MK_SD_Pos   (16U)
#define JPEGENC_SWREG20_RES_MK_SD_Msk   (0xFFUL << JPEGENC_SWREG20_RES_MK_SD_Pos)
#define JPEGENC_SWREG20_RES_MK_SD       JPEGENC_SWREG20_RES_MK_SD_Msk
#define JPEGENC_SWREG20_JPEGS_EN_Pos    (24U)
#define JPEGENC_SWREG20_JPEGS_EN_Msk    (0x1UL << JPEGENC_SWREG20_JPEGS_EN_Pos)
#define JPEGENC_SWREG20_JPEGS_EN        JPEGENC_SWREG20_JPEGS_EN_Msk
#define JPEGENC_SWREG20_JPEG_MODE_Pos   (25U)
#define JPEGENC_SWREG20_JPEG_MODE_Msk   (0x1UL << JPEGENC_SWREG20_JPEG_MODE_Pos)
#define JPEGENC_SWREG20_JPEG_MODE       JPEGENC_SWREG20_JPEG_MODE_Msk

/**************** Bit definition for JPEGENC_SWREG21 register *****************/
#define JPEGENC_SWREG21_IM_MODE_FAVOR_Pos  (0U)
#define JPEGENC_SWREG21_IM_MODE_FAVOR_Msk  (0xFFFFUL << JPEGENC_SWREG21_IM_MODE_FAVOR_Pos)
#define JPEGENC_SWREG21_IM_MODE_FAVOR   JPEGENC_SWREG21_IM_MODE_FAVOR_Msk
#define JPEGENC_SWREG21_COM_SLICE_Pos   (16U)
#define JPEGENC_SWREG21_COM_SLICE_Msk   (0xFFUL << JPEGENC_SWREG21_COM_SLICE_Pos)
#define JPEGENC_SWREG21_COM_SLICE       JPEGENC_SWREG21_COM_SLICE_Msk
#define JPEGENC_SWREG21_SKIP_PEN_Pos    (24U)
#define JPEGENC_SWREG21_SKIP_PEN_Msk    (0xFFUL << JPEGENC_SWREG21_SKIP_PEN_Pos)
#define JPEGENC_SWREG21_SKIP_PEN        JPEGENC_SWREG21_SKIP_PEN_Msk

/**************** Bit definition for JPEGENC_SWREG22 register *****************/
#define JPEGENC_SWREG22_SHRM_BITS_MSB_Pos  (0U)
#define JPEGENC_SWREG22_SHRM_BITS_MSB_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG22_SHRM_BITS_MSB_Pos)
#define JPEGENC_SWREG22_SHRM_BITS_MSB   JPEGENC_SWREG22_SHRM_BITS_MSB_Msk

/**************** Bit definition for JPEGENC_SWREG23 register *****************/
#define JPEGENC_SWREG23_SHRM_BITS_LSB_Pos  (0U)
#define JPEGENC_SWREG23_SHRM_BITS_LSB_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG23_SHRM_BITS_LSB_Pos)
#define JPEGENC_SWREG23_SHRM_BITS_LSB   JPEGENC_SWREG23_SHRM_BITS_LSB_Msk

/**************** Bit definition for JPEGENC_SWREG24 register *****************/
#define JPEGENC_SWREG24_SBUF_LIMIT_Pos  (0U)
#define JPEGENC_SWREG24_SBUF_LIMIT_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG24_SBUF_LIMIT_Pos)
#define JPEGENC_SWREG24_SBUF_LIMIT      JPEGENC_SWREG24_SBUF_LIMIT_Msk

/**************** Bit definition for JPEGENC_SWREG25 register *****************/
#define JPEGENC_SWREG25_QPSUM_Pos       (0U)
#define JPEGENC_SWREG25_QPSUM_Msk       (0x3FFFFFUL << JPEGENC_SWREG25_QPSUM_Pos)
#define JPEGENC_SWREG25_QPSUM           JPEGENC_SWREG25_QPSUM_Msk
#define JPEGENC_SWREG25_MADTH_Pos       (22U)
#define JPEGENC_SWREG25_MADTH_Msk       (0x3FUL << JPEGENC_SWREG25_MADTH_Pos)
#define JPEGENC_SWREG25_MADTH           JPEGENC_SWREG25_MADTH_Msk
#define JPEGENC_SWREG25_MADQPCHANGE_Pos  (28U)
#define JPEGENC_SWREG25_MADQPCHANGE_Msk  (0xFUL << JPEGENC_SWREG25_MADQPCHANGE_Pos)
#define JPEGENC_SWREG25_MADQPCHANGE     JPEGENC_SWREG25_MADQPCHANGE_Msk

/**************** Bit definition for JPEGENC_SWREG26 register *****************/
#define JPEGENC_SWREG26_INTRASLC_BM_Pos  (0U)
#define JPEGENC_SWREG26_INTRASLC_BM_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG26_INTRASLC_BM_Pos)
#define JPEGENC_SWREG26_INTRASLC_BM     JPEGENC_SWREG26_INTRASLC_BM_Msk

/**************** Bit definition for JPEGENC_SWREG27 register *****************/
#define JPEGENC_SWREG27_CHK_DIST_Pos    (0U)
#define JPEGENC_SWREG27_CHK_DIST_Msk    (0x1FFFUL << JPEGENC_SWREG27_CHK_DIST_Pos)
#define JPEGENC_SWREG27_CHK_DIST        JPEGENC_SWREG27_CHK_DIST_Msk
#define JPEGENC_SWREG27_QPMIN_Pos       (14U)
#define JPEGENC_SWREG27_QPMIN_Msk       (0x3FUL << JPEGENC_SWREG27_QPMIN_Pos)
#define JPEGENC_SWREG27_QPMIN           JPEGENC_SWREG27_QPMIN_Msk
#define JPEGENC_SWREG27_QPMAX_Pos       (20U)
#define JPEGENC_SWREG27_QPMAX_Msk       (0x3FUL << JPEGENC_SWREG27_QPMAX_Pos)
#define JPEGENC_SWREG27_QPMAX           JPEGENC_SWREG27_QPMAX_Msk
#define JPEGENC_SWREG27_QPLUM_Pos       (26U)
#define JPEGENC_SWREG27_QPLUM_Msk       (0x3FUL << JPEGENC_SWREG27_QPLUM_Pos)
#define JPEGENC_SWREG27_QPLUM           JPEGENC_SWREG27_QPLUM_Msk

/**************** Bit definition for JPEGENC_SWREG28 register *****************/
#define JPEGENC_SWREG28_CHK2_WT_Pos     (0U)
#define JPEGENC_SWREG28_CHK2_WT_Msk     (0xFFFFUL << JPEGENC_SWREG28_CHK2_WT_Pos)
#define JPEGENC_SWREG28_CHK2_WT         JPEGENC_SWREG28_CHK2_WT_Msk
#define JPEGENC_SWREG28_CHK1_WT_Pos     (16U)
#define JPEGENC_SWREG28_CHK1_WT_Msk     (0xFFFFUL << JPEGENC_SWREG28_CHK1_WT_Pos)
#define JPEGENC_SWREG28_CHK1_WT         JPEGENC_SWREG28_CHK1_WT_Msk

/**************** Bit definition for JPEGENC_SWREG29 register *****************/
#define JPEGENC_SWREG29_CHK4_WT_Pos     (0U)
#define JPEGENC_SWREG29_CHK4_WT_Msk     (0xFFFFUL << JPEGENC_SWREG29_CHK4_WT_Pos)
#define JPEGENC_SWREG29_CHK4_WT         JPEGENC_SWREG29_CHK4_WT_Msk
#define JPEGENC_SWREG29_CHK3_WT_Pos     (16U)
#define JPEGENC_SWREG29_CHK3_WT_Msk     (0xFFFFUL << JPEGENC_SWREG29_CHK3_WT_Pos)
#define JPEGENC_SWREG29_CHK3_WT         JPEGENC_SWREG29_CHK3_WT_Msk

/**************** Bit definition for JPEGENC_SWREG30 register *****************/
#define JPEGENC_SWREG30_CHK6_WT_Pos     (0U)
#define JPEGENC_SWREG30_CHK6_WT_Msk     (0xFFFFUL << JPEGENC_SWREG30_CHK6_WT_Pos)
#define JPEGENC_SWREG30_CHK6_WT         JPEGENC_SWREG30_CHK6_WT_Msk
#define JPEGENC_SWREG30_CHK5_WT_Pos     (16U)
#define JPEGENC_SWREG30_CHK5_WT_Msk     (0xFFFFUL << JPEGENC_SWREG30_CHK5_WT_Pos)
#define JPEGENC_SWREG30_CHK5_WT         JPEGENC_SWREG30_CHK5_WT_Msk

/**************** Bit definition for JPEGENC_SWREG31 register *****************/
#define JPEGENC_SWREG31_CHK8_WT_Pos     (0U)
#define JPEGENC_SWREG31_CHK8_WT_Msk     (0xFFFFUL << JPEGENC_SWREG31_CHK8_WT_Pos)
#define JPEGENC_SWREG31_CHK8_WT         JPEGENC_SWREG31_CHK8_WT_Msk
#define JPEGENC_SWREG31_CHK7_WT_Pos     (16U)
#define JPEGENC_SWREG31_CHK7_WT_Msk     (0xFFFFUL << JPEGENC_SWREG31_CHK7_WT_Pos)
#define JPEGENC_SWREG31_CHK7_WT         JPEGENC_SWREG31_CHK7_WT_Msk

/**************** Bit definition for JPEGENC_SWREG32 register *****************/
#define JPEGENC_SWREG32_CHK10_WT_Pos    (0U)
#define JPEGENC_SWREG32_CHK10_WT_Msk    (0xFFFFUL << JPEGENC_SWREG32_CHK10_WT_Pos)
#define JPEGENC_SWREG32_CHK10_WT        JPEGENC_SWREG32_CHK10_WT_Msk
#define JPEGENC_SWREG32_CHK9_WT_Pos     (16U)
#define JPEGENC_SWREG32_CHK9_WT_Msk     (0xFFFFUL << JPEGENC_SWREG32_CHK9_WT_Pos)
#define JPEGENC_SWREG32_CHK9_WT         JPEGENC_SWREG32_CHK9_WT_Msk

/**************** Bit definition for JPEGENC_SWREG33 register *****************/
#define JPEGENC_SWREG33_CP_WE2_Pos      (0U)
#define JPEGENC_SWREG33_CP_WE2_Msk      (0xFFFFUL << JPEGENC_SWREG33_CP_WE2_Pos)
#define JPEGENC_SWREG33_CP_WE2          JPEGENC_SWREG33_CP_WE2_Msk
#define JPEGENC_SWREG33_CP_WE1_Pos      (16U)
#define JPEGENC_SWREG33_CP_WE1_Msk      (0xFFFFUL << JPEGENC_SWREG33_CP_WE1_Pos)
#define JPEGENC_SWREG33_CP_WE1          JPEGENC_SWREG33_CP_WE1_Msk

/**************** Bit definition for JPEGENC_SWREG34 register *****************/
#define JPEGENC_SWREG34_CP_WE4_Pos      (0U)
#define JPEGENC_SWREG34_CP_WE4_Msk      (0xFFFFUL << JPEGENC_SWREG34_CP_WE4_Pos)
#define JPEGENC_SWREG34_CP_WE4          JPEGENC_SWREG34_CP_WE4_Msk
#define JPEGENC_SWREG34_CP_WE3_Pos      (16U)
#define JPEGENC_SWREG34_CP_WE3_Msk      (0xFFFFUL << JPEGENC_SWREG34_CP_WE3_Pos)
#define JPEGENC_SWREG34_CP_WE3          JPEGENC_SWREG34_CP_WE3_Msk

/**************** Bit definition for JPEGENC_SWREG35 register *****************/
#define JPEGENC_SWREG35_CP_WE6_Pos      (0U)
#define JPEGENC_SWREG35_CP_WE6_Msk      (0xFFFFUL << JPEGENC_SWREG35_CP_WE6_Pos)
#define JPEGENC_SWREG35_CP_WE6          JPEGENC_SWREG35_CP_WE6_Msk
#define JPEGENC_SWREG35_CP_WE5_Pos      (16U)
#define JPEGENC_SWREG35_CP_WE5_Msk      (0xFFFFUL << JPEGENC_SWREG35_CP_WE5_Pos)
#define JPEGENC_SWREG35_CP_WE5          JPEGENC_SWREG35_CP_WE5_Msk

/**************** Bit definition for JPEGENC_SWREG36 register *****************/
#define JPEGENC_SWREG36_QPCHK_D7_Pos    (0U)
#define JPEGENC_SWREG36_QPCHK_D7_Msk    (0xFUL << JPEGENC_SWREG36_QPCHK_D7_Pos)
#define JPEGENC_SWREG36_QPCHK_D7        JPEGENC_SWREG36_QPCHK_D7_Msk
#define JPEGENC_SWREG36_QPCHK_D6_Pos    (4U)
#define JPEGENC_SWREG36_QPCHK_D6_Msk    (0xFUL << JPEGENC_SWREG36_QPCHK_D6_Pos)
#define JPEGENC_SWREG36_QPCHK_D6        JPEGENC_SWREG36_QPCHK_D6_Msk
#define JPEGENC_SWREG36_QPCHK_D5_Pos    (8U)
#define JPEGENC_SWREG36_QPCHK_D5_Msk    (0xFUL << JPEGENC_SWREG36_QPCHK_D5_Pos)
#define JPEGENC_SWREG36_QPCHK_D5        JPEGENC_SWREG36_QPCHK_D5_Msk
#define JPEGENC_SWREG36_QPCHK_D4_Pos    (12U)
#define JPEGENC_SWREG36_QPCHK_D4_Msk    (0xFUL << JPEGENC_SWREG36_QPCHK_D4_Pos)
#define JPEGENC_SWREG36_QPCHK_D4        JPEGENC_SWREG36_QPCHK_D4_Msk
#define JPEGENC_SWREG36_QPCHK_D3_Pos    (16U)
#define JPEGENC_SWREG36_QPCHK_D3_Msk    (0xFUL << JPEGENC_SWREG36_QPCHK_D3_Pos)
#define JPEGENC_SWREG36_QPCHK_D3        JPEGENC_SWREG36_QPCHK_D3_Msk
#define JPEGENC_SWREG36_QPCHK_D2_Pos    (20U)
#define JPEGENC_SWREG36_QPCHK_D2_Msk    (0xFUL << JPEGENC_SWREG36_QPCHK_D2_Pos)
#define JPEGENC_SWREG36_QPCHK_D2        JPEGENC_SWREG36_QPCHK_D2_Msk
#define JPEGENC_SWREG36_QPCHK_D1_Pos    (24U)
#define JPEGENC_SWREG36_QPCHK_D1_Msk    (0xFUL << JPEGENC_SWREG36_QPCHK_D1_Pos)
#define JPEGENC_SWREG36_QPCHK_D1        JPEGENC_SWREG36_QPCHK_D1_Msk

/**************** Bit definition for JPEGENC_SWREG37 register *****************/
#define JPEGENC_SWREG37_RLC_CW_CNT_Pos  (0U)
#define JPEGENC_SWREG37_RLC_CW_CNT_Msk  (0x7FFFFFUL << JPEGENC_SWREG37_RLC_CW_CNT_Pos)
#define JPEGENC_SWREG37_RLC_CW_CNT      JPEGENC_SWREG37_RLC_CW_CNT_Msk
#define JPEGENC_SWREG37_SS_OFFSET_Pos   (23U)
#define JPEGENC_SWREG37_SS_OFFSET_Msk   (0x3FUL << JPEGENC_SWREG37_SS_OFFSET_Pos)
#define JPEGENC_SWREG37_SS_OFFSET       JPEGENC_SWREG37_SS_OFFSET_Msk
#define JPEGENC_SWREG37_VP8_INT_MODE_Pos  (31U)
#define JPEGENC_SWREG37_VP8_INT_MODE_Msk  (0x1UL << JPEGENC_SWREG37_VP8_INT_MODE_Pos)
#define JPEGENC_SWREG37_VP8_INT_MODE    JPEGENC_SWREG37_VP8_INT_MODE_Msk

/**************** Bit definition for JPEGENC_SWREG38 register *****************/
#define JPEGENC_SWREG38_MB_CNT_OUT_Pos  (0U)
#define JPEGENC_SWREG38_MB_CNT_OUT_Msk  (0xFFFFUL << JPEGENC_SWREG38_MB_CNT_OUT_Pos)
#define JPEGENC_SWREG38_MB_CNT_OUT      JPEGENC_SWREG38_MB_CNT_OUT_Msk
#define JPEGENC_SWREG38_MB_CNT_W_MAD_Pos  (16U)
#define JPEGENC_SWREG38_MB_CNT_W_MAD_Msk  (0xFFFFUL << JPEGENC_SWREG38_MB_CNT_W_MAD_Pos)
#define JPEGENC_SWREG38_MB_CNT_W_MAD    JPEGENC_SWREG38_MB_CNT_W_MAD_Msk

/**************** Bit definition for JPEGENC_SWREG39 register *****************/
#define JPEGENC_SWREG39_NPL_ADDR_Pos    (0U)
#define JPEGENC_SWREG39_NPL_ADDR_Msk    (0xFFFFFFFFUL << JPEGENC_SWREG39_NPL_ADDR_Pos)
#define JPEGENC_SWREG39_NPL_ADDR        JPEGENC_SWREG39_NPL_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG51 register *****************/
#define JPEGENC_SWREG51_CCT_PT_ADDR_Pos  (0U)
#define JPEGENC_SWREG51_CCT_PT_ADDR_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG51_CCT_PT_ADDR_Pos)
#define JPEGENC_SWREG51_CCT_PT_ADDR     JPEGENC_SWREG51_CCT_PT_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG52 register *****************/
#define JPEGENC_SWREG52_MVO_WR_ADDR_Pos  (0U)
#define JPEGENC_SWREG52_MVO_WR_ADDR_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG52_MVO_WR_ADDR_Pos)
#define JPEGENC_SWREG52_MVO_WR_ADDR     JPEGENC_SWREG52_MVO_WR_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG53 register *****************/
#define JPEGENC_SWREG53_R2Y_COEFA_Pos   (0U)
#define JPEGENC_SWREG53_R2Y_COEFA_Msk   (0xFFFFUL << JPEGENC_SWREG53_R2Y_COEFA_Pos)
#define JPEGENC_SWREG53_R2Y_COEFA       JPEGENC_SWREG53_R2Y_COEFA_Msk
#define JPEGENC_SWREG53_R2Y_COEFB_Pos   (16U)
#define JPEGENC_SWREG53_R2Y_COEFB_Msk   (0xFFFFUL << JPEGENC_SWREG53_R2Y_COEFB_Pos)
#define JPEGENC_SWREG53_R2Y_COEFB       JPEGENC_SWREG53_R2Y_COEFB_Msk

/**************** Bit definition for JPEGENC_SWREG54 register *****************/
#define JPEGENC_SWREG54_R2Y_COEFC_Pos   (0U)
#define JPEGENC_SWREG54_R2Y_COEFC_Msk   (0xFFFFUL << JPEGENC_SWREG54_R2Y_COEFC_Pos)
#define JPEGENC_SWREG54_R2Y_COEFC       JPEGENC_SWREG54_R2Y_COEFC_Msk
#define JPEGENC_SWREG54_R2Y_COEFE_Pos   (16U)
#define JPEGENC_SWREG54_R2Y_COEFE_Msk   (0xFFFFUL << JPEGENC_SWREG54_R2Y_COEFE_Pos)
#define JPEGENC_SWREG54_R2Y_COEFE       JPEGENC_SWREG54_R2Y_COEFE_Msk

/**************** Bit definition for JPEGENC_SWREG55 register *****************/
#define JPEGENC_SWREG55_R2Y_COEFF_Pos   (0U)
#define JPEGENC_SWREG55_R2Y_COEFF_Msk   (0xFFFFUL << JPEGENC_SWREG55_R2Y_COEFF_Pos)
#define JPEGENC_SWREG55_R2Y_COEFF       JPEGENC_SWREG55_R2Y_COEFF_Msk
#define JPEGENC_SWREG55_RGB_RM_Pos      (16U)
#define JPEGENC_SWREG55_RGB_RM_Msk      (0x1FUL << JPEGENC_SWREG55_RGB_RM_Pos)
#define JPEGENC_SWREG55_RGB_RM          JPEGENC_SWREG55_RGB_RM_Msk
#define JPEGENC_SWREG55_RGB_GM_Pos      (21U)
#define JPEGENC_SWREG55_RGB_GM_Msk      (0x1FUL << JPEGENC_SWREG55_RGB_GM_Pos)
#define JPEGENC_SWREG55_RGB_GM          JPEGENC_SWREG55_RGB_GM_Msk
#define JPEGENC_SWREG55_RGB_BM_Pos      (26U)
#define JPEGENC_SWREG55_RGB_BM_Msk      (0x1FUL << JPEGENC_SWREG55_RGB_BM_Pos)
#define JPEGENC_SWREG55_RGB_BM          JPEGENC_SWREG55_RGB_BM_Msk

/**************** Bit definition for JPEGENC_SWREG56 register *****************/
#define JPEGENC_SWREG56_BOTTOM_MBCOL_Pos  (0U)
#define JPEGENC_SWREG56_BOTTOM_MBCOL_Msk  (0xFFUL << JPEGENC_SWREG56_BOTTOM_MBCOL_Pos)
#define JPEGENC_SWREG56_BOTTOM_MBCOL    JPEGENC_SWREG56_BOTTOM_MBCOL_Msk
#define JPEGENC_SWREG56_TOP_MBCOL_Pos   (8U)
#define JPEGENC_SWREG56_TOP_MBCOL_Msk   (0xFFUL << JPEGENC_SWREG56_TOP_MBCOL_Pos)
#define JPEGENC_SWREG56_TOP_MBCOL       JPEGENC_SWREG56_TOP_MBCOL_Msk
#define JPEGENC_SWREG56_RIGHT_MBCOL_Pos  (16U)
#define JPEGENC_SWREG56_RIGHT_MBCOL_Msk  (0xFFUL << JPEGENC_SWREG56_RIGHT_MBCOL_Pos)
#define JPEGENC_SWREG56_RIGHT_MBCOL     JPEGENC_SWREG56_RIGHT_MBCOL_Msk
#define JPEGENC_SWREG56_LEFT_MBCOL_Pos  (24U)
#define JPEGENC_SWREG56_LEFT_MBCOL_Msk  (0xFFUL << JPEGENC_SWREG56_LEFT_MBCOL_Pos)
#define JPEGENC_SWREG56_LEFT_MBCOL      JPEGENC_SWREG56_LEFT_MBCOL_Msk

/**************** Bit definition for JPEGENC_SWREG57 register *****************/
#define JPEGENC_SWREG57_CIR_MB_INT_Pos  (0U)
#define JPEGENC_SWREG57_CIR_MB_INT_Msk  (0xFFFFUL << JPEGENC_SWREG57_CIR_MB_INT_Pos)
#define JPEGENC_SWREG57_CIR_MB_INT      JPEGENC_SWREG57_CIR_MB_INT_Msk
#define JPEGENC_SWREG57_CIR_FIRST_MB_Pos  (16U)
#define JPEGENC_SWREG57_CIR_FIRST_MB_Msk  (0xFFFFUL << JPEGENC_SWREG57_CIR_FIRST_MB_Pos)
#define JPEGENC_SWREG57_CIR_FIRST_MB    JPEGENC_SWREG57_CIR_FIRST_MB_Msk

/**************** Bit definition for JPEGENC_SWREG58 register *****************/
#define JPEGENC_SWREG58_INTRASLC_BM_Pos  (0U)
#define JPEGENC_SWREG58_INTRASLC_BM_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG58_INTRASLC_BM_Pos)
#define JPEGENC_SWREG58_INTRASLC_BM     JPEGENC_SWREG58_INTRASLC_BM_Msk

/**************** Bit definition for JPEGENC_SWREG59 register *****************/
#define JPEGENC_SWREG59_INTRASLC_BM_Pos  (0U)
#define JPEGENC_SWREG59_INTRASLC_BM_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG59_INTRASLC_BM_Pos)
#define JPEGENC_SWREG59_INTRASLC_BM     JPEGENC_SWREG59_INTRASLC_BM_Msk

/**************** Bit definition for JPEGENC_SWREG60 register *****************/
#define JPEGENC_SWREG60_ROI1_BOT_MBRWO_Pos  (0U)
#define JPEGENC_SWREG60_ROI1_BOT_MBRWO_Msk  (0xFFUL << JPEGENC_SWREG60_ROI1_BOT_MBRWO_Pos)
#define JPEGENC_SWREG60_ROI1_BOT_MBRWO  JPEGENC_SWREG60_ROI1_BOT_MBRWO_Msk
#define JPEGENC_SWREG60_ROI1_TOP_MBROW_Pos  (8U)
#define JPEGENC_SWREG60_ROI1_TOP_MBROW_Msk  (0xFFUL << JPEGENC_SWREG60_ROI1_TOP_MBROW_Pos)
#define JPEGENC_SWREG60_ROI1_TOP_MBROW  JPEGENC_SWREG60_ROI1_TOP_MBROW_Msk
#define JPEGENC_SWREG60_ROI1_RIGHT_MBCOL_Pos  (16U)
#define JPEGENC_SWREG60_ROI1_RIGHT_MBCOL_Msk  (0xFFUL << JPEGENC_SWREG60_ROI1_RIGHT_MBCOL_Pos)
#define JPEGENC_SWREG60_ROI1_RIGHT_MBCOL  JPEGENC_SWREG60_ROI1_RIGHT_MBCOL_Msk
#define JPEGENC_SWREG60_ROI1_LEFT_MBCOL_Pos  (24U)
#define JPEGENC_SWREG60_ROI1_LEFT_MBCOL_Msk  (0xFFUL << JPEGENC_SWREG60_ROI1_LEFT_MBCOL_Pos)
#define JPEGENC_SWREG60_ROI1_LEFT_MBCOL  JPEGENC_SWREG60_ROI1_LEFT_MBCOL_Msk

/**************** Bit definition for JPEGENC_SWREG61 register *****************/
#define JPEGENC_SWREG61_ROI2_BOT_MBRWO_Pos  (0U)
#define JPEGENC_SWREG61_ROI2_BOT_MBRWO_Msk  (0xFFUL << JPEGENC_SWREG61_ROI2_BOT_MBRWO_Pos)
#define JPEGENC_SWREG61_ROI2_BOT_MBRWO  JPEGENC_SWREG61_ROI2_BOT_MBRWO_Msk
#define JPEGENC_SWREG61_ROI2_TOP_MBROW_Pos  (8U)
#define JPEGENC_SWREG61_ROI2_TOP_MBROW_Msk  (0xFFUL << JPEGENC_SWREG61_ROI2_TOP_MBROW_Pos)
#define JPEGENC_SWREG61_ROI2_TOP_MBROW  JPEGENC_SWREG61_ROI2_TOP_MBROW_Msk
#define JPEGENC_SWREG61_ROI2_RIGHT_MBCOL_Pos  (16U)
#define JPEGENC_SWREG61_ROI2_RIGHT_MBCOL_Msk  (0xFFUL << JPEGENC_SWREG61_ROI2_RIGHT_MBCOL_Pos)
#define JPEGENC_SWREG61_ROI2_RIGHT_MBCOL  JPEGENC_SWREG61_ROI2_RIGHT_MBCOL_Msk
#define JPEGENC_SWREG61_ROI2_LEFT_MBCOL_Pos  (24U)
#define JPEGENC_SWREG61_ROI2_LEFT_MBCOL_Msk  (0xFFUL << JPEGENC_SWREG61_ROI2_LEFT_MBCOL_Pos)
#define JPEGENC_SWREG61_ROI2_LEFT_MBCOL  JPEGENC_SWREG61_ROI2_LEFT_MBCOL_Msk

/**************** Bit definition for JPEGENC_SWREG62 register *****************/
#define JPEGENC_SWREG62_ROI2_DELTAQP_Pos  (0U)
#define JPEGENC_SWREG62_ROI2_DELTAQP_Msk  (0xFUL << JPEGENC_SWREG62_ROI2_DELTAQP_Pos)
#define JPEGENC_SWREG62_ROI2_DELTAQP    JPEGENC_SWREG62_ROI2_DELTAQP_Msk
#define JPEGENC_SWREG62_ROI1_DELTAQP_Pos  (4U)
#define JPEGENC_SWREG62_ROI1_DELTAQP_Msk  (0xFUL << JPEGENC_SWREG62_ROI1_DELTAQP_Pos)
#define JPEGENC_SWREG62_ROI1_DELTAQP    JPEGENC_SWREG62_ROI1_DELTAQP_Msk
#define JPEGENC_SWREG62_MVC_IVF_Pos     (8U)
#define JPEGENC_SWREG62_MVC_IVF_Msk     (0x1UL << JPEGENC_SWREG62_MVC_IVF_Pos)
#define JPEGENC_SWREG62_MVC_IVF         JPEGENC_SWREG62_MVC_IVF_Msk
#define JPEGENC_SWREG62_MVC_APF_Pos     (9U)
#define JPEGENC_SWREG62_MVC_APF_Msk     (0x1UL << JPEGENC_SWREG62_MVC_APF_Pos)
#define JPEGENC_SWREG62_MVC_APF         JPEGENC_SWREG62_MVC_APF_Msk
#define JPEGENC_SWREG62_MVC_TID_Pos     (10U)
#define JPEGENC_SWREG62_MVC_TID_Msk     (0x7UL << JPEGENC_SWREG62_MVC_TID_Pos)
#define JPEGENC_SWREG62_MVC_TID         JPEGENC_SWREG62_MVC_TID_Msk
#define JPEGENC_SWREG62_MVC_VID_Pos     (13U)
#define JPEGENC_SWREG62_MVC_VID_Msk     (0x7UL << JPEGENC_SWREG62_MVC_VID_Pos)
#define JPEGENC_SWREG62_MVC_VID         JPEGENC_SWREG62_MVC_VID_Msk
#define JPEGENC_SWREG62_MVC_PID_Pos     (16U)
#define JPEGENC_SWREG62_MVC_PID_Msk     (0x7UL << JPEGENC_SWREG62_MVC_PID_Pos)
#define JPEGENC_SWREG62_MVC_PID         JPEGENC_SWREG62_MVC_PID_Msk
#define JPEGENC_SWREG62_PEN_MV_Pos      (19U)
#define JPEGENC_SWREG62_PEN_MV_Msk      (0x1FFUL << JPEGENC_SWREG62_PEN_MV_Pos)
#define JPEGENC_SWREG62_PEN_MV          JPEGENC_SWREG62_PEN_MV_Msk
#define JPEGENC_SWREG62_ZERO_MV_FAVOR_Pos  (28U)
#define JPEGENC_SWREG62_ZERO_MV_FAVOR_Msk  (0xFUL << JPEGENC_SWREG62_ZERO_MV_FAVOR_Pos)
#define JPEGENC_SWREG62_ZERO_MV_FAVOR   JPEGENC_SWREG62_ZERO_MV_FAVOR_Msk

/**************** Bit definition for JPEGENC_SWREG63 register *****************/
#define JPEGENC_SWREG63_HW_MAX_V_WIDTH_Pos  (0U)
#define JPEGENC_SWREG63_HW_MAX_V_WIDTH_Msk  (0xFFFUL << JPEGENC_SWREG63_HW_MAX_V_WIDTH_Pos)
#define JPEGENC_SWREG63_HW_MAX_V_WIDTH  JPEGENC_SWREG63_HW_MAX_V_WIDTH_Msk
#define JPEGENC_SWREG63_HW_BUS_WIDTH_Pos  (12U)
#define JPEGENC_SWREG63_HW_BUS_WIDTH_Msk  (0xFUL << JPEGENC_SWREG63_HW_BUS_WIDTH_Pos)
#define JPEGENC_SWREG63_HW_BUS_WIDTH    JPEGENC_SWREG63_HW_BUS_WIDTH_Msk
#define JPEGENC_SWREG63_HW_LANGUAGE_Pos  (16U)
#define JPEGENC_SWREG63_HW_LANGUAGE_Msk  (0xFUL << JPEGENC_SWREG63_HW_LANGUAGE_Pos)
#define JPEGENC_SWREG63_HW_LANGUAGE     JPEGENC_SWREG63_HW_LANGUAGE_Msk
#define JPEGENC_SWREG63_HW_BUS_CON_Pos  (20U)
#define JPEGENC_SWREG63_HW_BUS_CON_Msk  (0xFUL << JPEGENC_SWREG63_HW_BUS_CON_Pos)
#define JPEGENC_SWREG63_HW_BUS_CON      JPEGENC_SWREG63_HW_BUS_CON_Msk
#define JPEGENC_SWREG63_HW_STAB_Pos     (24U)
#define JPEGENC_SWREG63_HW_STAB_Msk     (0x1UL << JPEGENC_SWREG63_HW_STAB_Pos)
#define JPEGENC_SWREG63_HW_STAB         JPEGENC_SWREG63_HW_STAB_Msk
#define JPEGENC_SWREG63_HW_JPEG_ENC_Pos  (25U)
#define JPEGENC_SWREG63_HW_JPEG_ENC_Msk  (0x1UL << JPEGENC_SWREG63_HW_JPEG_ENC_Pos)
#define JPEGENC_SWREG63_HW_JPEG_ENC     JPEGENC_SWREG63_HW_JPEG_ENC_Msk
#define JPEGENC_SWREG63_HW_VP8_ENC_Pos  (26U)
#define JPEGENC_SWREG63_HW_VP8_ENC_Msk  (0x1UL << JPEGENC_SWREG63_HW_VP8_ENC_Pos)
#define JPEGENC_SWREG63_HW_VP8_ENC      JPEGENC_SWREG63_HW_VP8_ENC_Msk
#define JPEGENC_SWREG63_HW_H264_ENC_Pos  (27U)
#define JPEGENC_SWREG63_HW_H264_ENC_Msk  (0x1UL << JPEGENC_SWREG63_HW_H264_ENC_Pos)
#define JPEGENC_SWREG63_HW_H264_ENC     JPEGENC_SWREG63_HW_H264_ENC_Msk
#define JPEGENC_SWREG63_HW_R2Y_Pos      (28U)
#define JPEGENC_SWREG63_HW_R2Y_Msk      (0x1UL << JPEGENC_SWREG63_HW_R2Y_Pos)
#define JPEGENC_SWREG63_HW_R2Y          JPEGENC_SWREG63_HW_R2Y_Msk
#define JPEGENC_SWREG63_HW_SEARCH_H_Pos  (29U)
#define JPEGENC_SWREG63_HW_SEARCH_H_Msk  (0x1UL << JPEGENC_SWREG63_HW_SEARCH_H_Pos)
#define JPEGENC_SWREG63_HW_SEARCH_H     JPEGENC_SWREG63_HW_SEARCH_H_Msk
#define JPEGENC_SWREG63_HW_DS_Pos       (30U)
#define JPEGENC_SWREG63_HW_DS_Msk       (0x1UL << JPEGENC_SWREG63_HW_DS_Pos)
#define JPEGENC_SWREG63_HW_DS           JPEGENC_SWREG63_HW_DS_Msk
#define JPEGENC_SWREG63_HW_INT_BUF_Pos  (31U)
#define JPEGENC_SWREG63_HW_INT_BUF_Msk  (0x1UL << JPEGENC_SWREG63_HW_INT_BUF_Pos)
#define JPEGENC_SWREG63_HW_INT_BUF      JPEGENC_SWREG63_HW_INT_BUF_Msk

/**************** Bit definition for JPEGENC_SWREG64 register *****************/
#define JPEGENC_SWREG64_JLQ1_Pos        (0U)
#define JPEGENC_SWREG64_JLQ1_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG64_JLQ1_Pos)
#define JPEGENC_SWREG64_JLQ1            JPEGENC_SWREG64_JLQ1_Msk

/**************** Bit definition for JPEGENC_SWREG65 register *****************/
#define JPEGENC_SWREG65_JLQ2_Pos        (0U)
#define JPEGENC_SWREG65_JLQ2_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG65_JLQ2_Pos)
#define JPEGENC_SWREG65_JLQ2            JPEGENC_SWREG65_JLQ2_Msk

/**************** Bit definition for JPEGENC_SWREG66 register *****************/
#define JPEGENC_SWREG66_JLQ3_Pos        (0U)
#define JPEGENC_SWREG66_JLQ3_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG66_JLQ3_Pos)
#define JPEGENC_SWREG66_JLQ3            JPEGENC_SWREG66_JLQ3_Msk

/**************** Bit definition for JPEGENC_SWREG67 register *****************/
#define JPEGENC_SWREG67_JLQ4_Pos        (0U)
#define JPEGENC_SWREG67_JLQ4_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG67_JLQ4_Pos)
#define JPEGENC_SWREG67_JLQ4            JPEGENC_SWREG67_JLQ4_Msk

/**************** Bit definition for JPEGENC_SWREG68 register *****************/
#define JPEGENC_SWREG68_JLQ5_Pos        (0U)
#define JPEGENC_SWREG68_JLQ5_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG68_JLQ5_Pos)
#define JPEGENC_SWREG68_JLQ5            JPEGENC_SWREG68_JLQ5_Msk

/**************** Bit definition for JPEGENC_SWREG69 register *****************/
#define JPEGENC_SWREG69_JLQ6_Pos        (0U)
#define JPEGENC_SWREG69_JLQ6_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG69_JLQ6_Pos)
#define JPEGENC_SWREG69_JLQ6            JPEGENC_SWREG69_JLQ6_Msk

/**************** Bit definition for JPEGENC_SWREG70 register *****************/
#define JPEGENC_SWREG70_JLQ7_Pos        (0U)
#define JPEGENC_SWREG70_JLQ7_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG70_JLQ7_Pos)
#define JPEGENC_SWREG70_JLQ7            JPEGENC_SWREG70_JLQ7_Msk

/**************** Bit definition for JPEGENC_SWREG71 register *****************/
#define JPEGENC_SWREG71_JLQ8_Pos        (0U)
#define JPEGENC_SWREG71_JLQ8_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG71_JLQ8_Pos)
#define JPEGENC_SWREG71_JLQ8            JPEGENC_SWREG71_JLQ8_Msk

/**************** Bit definition for JPEGENC_SWREG72 register *****************/
#define JPEGENC_SWREG72_JLQ9_Pos        (0U)
#define JPEGENC_SWREG72_JLQ9_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG72_JLQ9_Pos)
#define JPEGENC_SWREG72_JLQ9            JPEGENC_SWREG72_JLQ9_Msk

/**************** Bit definition for JPEGENC_SWREG73 register *****************/
#define JPEGENC_SWREG73_JLQ10_Pos       (0U)
#define JPEGENC_SWREG73_JLQ10_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG73_JLQ10_Pos)
#define JPEGENC_SWREG73_JLQ10           JPEGENC_SWREG73_JLQ10_Msk

/**************** Bit definition for JPEGENC_SWREG74 register *****************/
#define JPEGENC_SWREG74_JLQ11_Pos       (0U)
#define JPEGENC_SWREG74_JLQ11_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG74_JLQ11_Pos)
#define JPEGENC_SWREG74_JLQ11           JPEGENC_SWREG74_JLQ11_Msk

/**************** Bit definition for JPEGENC_SWREG75 register *****************/
#define JPEGENC_SWREG75_JLQ12_Pos       (0U)
#define JPEGENC_SWREG75_JLQ12_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG75_JLQ12_Pos)
#define JPEGENC_SWREG75_JLQ12           JPEGENC_SWREG75_JLQ12_Msk

/**************** Bit definition for JPEGENC_SWREG76 register *****************/
#define JPEGENC_SWREG76_JLQ13_Pos       (0U)
#define JPEGENC_SWREG76_JLQ13_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG76_JLQ13_Pos)
#define JPEGENC_SWREG76_JLQ13           JPEGENC_SWREG76_JLQ13_Msk

/**************** Bit definition for JPEGENC_SWREG77 register *****************/
#define JPEGENC_SWREG77_JLQ14_Pos       (0U)
#define JPEGENC_SWREG77_JLQ14_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG77_JLQ14_Pos)
#define JPEGENC_SWREG77_JLQ14           JPEGENC_SWREG77_JLQ14_Msk

/**************** Bit definition for JPEGENC_SWREG78 register *****************/
#define JPEGENC_SWREG78_JLQ15_Pos       (0U)
#define JPEGENC_SWREG78_JLQ15_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG78_JLQ15_Pos)
#define JPEGENC_SWREG78_JLQ15           JPEGENC_SWREG78_JLQ15_Msk

/**************** Bit definition for JPEGENC_SWREG79 register *****************/
#define JPEGENC_SWREG79_JLQ16_Pos       (0U)
#define JPEGENC_SWREG79_JLQ16_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG79_JLQ16_Pos)
#define JPEGENC_SWREG79_JLQ16           JPEGENC_SWREG79_JLQ16_Msk

/**************** Bit definition for JPEGENC_SWREG80 register *****************/
#define JPEGENC_SWREG80_JCQ1_Pos        (0U)
#define JPEGENC_SWREG80_JCQ1_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG80_JCQ1_Pos)
#define JPEGENC_SWREG80_JCQ1            JPEGENC_SWREG80_JCQ1_Msk

/**************** Bit definition for JPEGENC_SWREG81 register *****************/
#define JPEGENC_SWREG81_JCQ2_Pos        (0U)
#define JPEGENC_SWREG81_JCQ2_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG81_JCQ2_Pos)
#define JPEGENC_SWREG81_JCQ2            JPEGENC_SWREG81_JCQ2_Msk

/**************** Bit definition for JPEGENC_SWREG82 register *****************/
#define JPEGENC_SWREG82_JCQ3_Pos        (0U)
#define JPEGENC_SWREG82_JCQ3_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG82_JCQ3_Pos)
#define JPEGENC_SWREG82_JCQ3            JPEGENC_SWREG82_JCQ3_Msk

/**************** Bit definition for JPEGENC_SWREG83 register *****************/
#define JPEGENC_SWREG83_JCQ4_Pos        (0U)
#define JPEGENC_SWREG83_JCQ4_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG83_JCQ4_Pos)
#define JPEGENC_SWREG83_JCQ4            JPEGENC_SWREG83_JCQ4_Msk

/**************** Bit definition for JPEGENC_SWREG84 register *****************/
#define JPEGENC_SWREG84_JCQ5_Pos        (0U)
#define JPEGENC_SWREG84_JCQ5_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG84_JCQ5_Pos)
#define JPEGENC_SWREG84_JCQ5            JPEGENC_SWREG84_JCQ5_Msk

/**************** Bit definition for JPEGENC_SWREG85 register *****************/
#define JPEGENC_SWREG85_JCQ6_Pos        (0U)
#define JPEGENC_SWREG85_JCQ6_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG85_JCQ6_Pos)
#define JPEGENC_SWREG85_JCQ6            JPEGENC_SWREG85_JCQ6_Msk

/**************** Bit definition for JPEGENC_SWREG86 register *****************/
#define JPEGENC_SWREG86_JCQ7_Pos        (0U)
#define JPEGENC_SWREG86_JCQ7_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG86_JCQ7_Pos)
#define JPEGENC_SWREG86_JCQ7            JPEGENC_SWREG86_JCQ7_Msk

/**************** Bit definition for JPEGENC_SWREG87 register *****************/
#define JPEGENC_SWREG87_JCQ8_Pos        (0U)
#define JPEGENC_SWREG87_JCQ8_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG87_JCQ8_Pos)
#define JPEGENC_SWREG87_JCQ8            JPEGENC_SWREG87_JCQ8_Msk

/**************** Bit definition for JPEGENC_SWREG88 register *****************/
#define JPEGENC_SWREG88_JCQ9_Pos        (0U)
#define JPEGENC_SWREG88_JCQ9_Msk        (0xFFFFFFFFUL << JPEGENC_SWREG88_JCQ9_Pos)
#define JPEGENC_SWREG88_JCQ9            JPEGENC_SWREG88_JCQ9_Msk

/**************** Bit definition for JPEGENC_SWREG89 register *****************/
#define JPEGENC_SWREG89_JCQ10_Pos       (0U)
#define JPEGENC_SWREG89_JCQ10_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG89_JCQ10_Pos)
#define JPEGENC_SWREG89_JCQ10           JPEGENC_SWREG89_JCQ10_Msk

/**************** Bit definition for JPEGENC_SWREG90 register *****************/
#define JPEGENC_SWREG90_JCQ11_Pos       (0U)
#define JPEGENC_SWREG90_JCQ11_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG90_JCQ11_Pos)
#define JPEGENC_SWREG90_JCQ11           JPEGENC_SWREG90_JCQ11_Msk

/**************** Bit definition for JPEGENC_SWREG91 register *****************/
#define JPEGENC_SWREG91_JCQ12_Pos       (0U)
#define JPEGENC_SWREG91_JCQ12_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG91_JCQ12_Pos)
#define JPEGENC_SWREG91_JCQ12           JPEGENC_SWREG91_JCQ12_Msk

/**************** Bit definition for JPEGENC_SWREG92 register *****************/
#define JPEGENC_SWREG92_JCQ13_Pos       (0U)
#define JPEGENC_SWREG92_JCQ13_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG92_JCQ13_Pos)
#define JPEGENC_SWREG92_JCQ13           JPEGENC_SWREG92_JCQ13_Msk

/**************** Bit definition for JPEGENC_SWREG93 register *****************/
#define JPEGENC_SWREG93_JCQ14_Pos       (0U)
#define JPEGENC_SWREG93_JCQ14_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG93_JCQ14_Pos)
#define JPEGENC_SWREG93_JCQ14           JPEGENC_SWREG93_JCQ14_Msk

/**************** Bit definition for JPEGENC_SWREG94 register *****************/
#define JPEGENC_SWREG94_JCQ15_Pos       (0U)
#define JPEGENC_SWREG94_JCQ15_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG94_JCQ15_Pos)
#define JPEGENC_SWREG94_JCQ15           JPEGENC_SWREG94_JCQ15_Msk

/**************** Bit definition for JPEGENC_SWREG95 register *****************/
#define JPEGENC_SWREG95_JCQ16_Pos       (0U)
#define JPEGENC_SWREG95_JCQ16_Msk       (0xFFFFFFFFUL << JPEGENC_SWREG95_JCQ16_Pos)
#define JPEGENC_SWREG95_JCQ16           JPEGENC_SWREG95_JCQ16_Msk

/**************** Bit definition for JPEGENC_SWREG160 register ****************/
#define JPEGENC_SWREG160_VP8_BIT_COST_Pos  (0U)
#define JPEGENC_SWREG160_VP8_BIT_COST_Msk  (0xFFFUL << JPEGENC_SWREG160_VP8_BIT_COST_Pos)
#define JPEGENC_SWREG160_VP8_BIT_COST   JPEGENC_SWREG160_VP8_BIT_COST_Msk
#define JPEGENC_SWREG160_VP8_COEF_Pos   (12U)
#define JPEGENC_SWREG160_VP8_COEF_Msk   (0xFFFUL << JPEGENC_SWREG160_VP8_COEF_Pos)
#define JPEGENC_SWREG160_VP8_COEF       JPEGENC_SWREG160_VP8_COEF_Msk
#define JPEGENC_SWREG160_ZERO_MV_PEN_Pos  (24U)
#define JPEGENC_SWREG160_ZERO_MV_PEN_Msk  (0xFFUL << JPEGENC_SWREG160_ZERO_MV_PEN_Pos)
#define JPEGENC_SWREG160_ZERO_MV_PEN    JPEGENC_SWREG160_ZERO_MV_PEN_Msk

/**************** Bit definition for JPEGENC_SWREG231 register ****************/
#define JPEGENC_SWREG231_DS_ENC_IMG_ADDR_Pos  (0U)
#define JPEGENC_SWREG231_DS_ENC_IMG_ADDR_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG231_DS_ENC_IMG_ADDR_Pos)
#define JPEGENC_SWREG231_DS_ENC_IMG_ADDR  JPEGENC_SWREG231_DS_ENC_IMG_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG232 register ****************/
#define JPEGENC_SWREG232_SCALE_RATIO_W_Pos  (0U)
#define JPEGENC_SWREG232_SCALE_RATIO_W_Msk  (0x1FFFFUL << JPEGENC_SWREG232_SCALE_RATIO_W_Pos)
#define JPEGENC_SWREG232_SCALE_RATIO_W  JPEGENC_SWREG232_SCALE_RATIO_W_Msk
#define JPEGENC_SWREG232_SCALE_WIDTH_Pos  (17U)
#define JPEGENC_SWREG232_SCALE_WIDTH_Msk  (0x1FFFUL << JPEGENC_SWREG232_SCALE_WIDTH_Pos)
#define JPEGENC_SWREG232_SCALE_WIDTH    JPEGENC_SWREG232_SCALE_WIDTH_Msk
#define JPEGENC_SWREG232_SCALE_MODE_Pos  (30U)
#define JPEGENC_SWREG232_SCALE_MODE_Msk  (0x3UL << JPEGENC_SWREG232_SCALE_MODE_Pos)
#define JPEGENC_SWREG232_SCALE_MODE     JPEGENC_SWREG232_SCALE_MODE_Msk

/**************** Bit definition for JPEGENC_SWREG233 register ****************/
#define JPEGENC_SWREG233_SCALE_RATIO_H_Pos  (0U)
#define JPEGENC_SWREG233_SCALE_RATIO_H_Msk  (0x1FFFFUL << JPEGENC_SWREG233_SCALE_RATIO_H_Pos)
#define JPEGENC_SWREG233_SCALE_RATIO_H  JPEGENC_SWREG233_SCALE_RATIO_H_Msk
#define JPEGENC_SWREG233_SCALE_HEIGHT_Pos  (17U)
#define JPEGENC_SWREG233_SCALE_HEIGHT_Msk  (0x1FFFUL << JPEGENC_SWREG233_SCALE_HEIGHT_Pos)
#define JPEGENC_SWREG233_SCALE_HEIGHT   JPEGENC_SWREG233_SCALE_HEIGHT_Msk

/**************** Bit definition for JPEGENC_SWREG244 register ****************/
#define JPEGENC_SWREG244_VP8_3RD_DCT_ADDR_Pos  (0U)
#define JPEGENC_SWREG244_VP8_3RD_DCT_ADDR_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG244_VP8_3RD_DCT_ADDR_Pos)
#define JPEGENC_SWREG244_VP8_3RD_DCT_ADDR  JPEGENC_SWREG244_VP8_3RD_DCT_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG245 register ****************/
#define JPEGENC_SWREG245_VP8_4TH_DCT_ADDR_Pos  (0U)
#define JPEGENC_SWREG245_VP8_4TH_DCT_ADDR_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG245_VP8_4TH_DCT_ADDR_Pos)
#define JPEGENC_SWREG245_VP8_4TH_DCT_ADDR  JPEGENC_SWREG245_VP8_4TH_DCT_ADDR_Msk

/**************** Bit definition for JPEGENC_SWREG261 register ****************/
#define JPEGENC_SWREG261_BIT_COST_S1_Pos  (0U)
#define JPEGENC_SWREG261_BIT_COST_S1_Msk  (0xFFFUL << JPEGENC_SWREG261_BIT_COST_S1_Pos)
#define JPEGENC_SWREG261_BIT_COST_S1    JPEGENC_SWREG261_BIT_COST_S1_Msk
#define JPEGENC_SWREG261_MODE_FAVOR_S1_Pos  (12U)
#define JPEGENC_SWREG261_MODE_FAVOR_S1_Msk  (0xFFFFUL << JPEGENC_SWREG261_MODE_FAVOR_S1_Pos)
#define JPEGENC_SWREG261_MODE_FAVOR_S1  JPEGENC_SWREG261_MODE_FAVOR_S1_Msk

/**************** Bit definition for JPEGENC_SWREG262 register ****************/
#define JPEGENC_SWREG262_MB_MODE_FAVOR_S1_Pos  (0U)
#define JPEGENC_SWREG262_MB_MODE_FAVOR_S1_Msk  (0xFFFFUL << JPEGENC_SWREG262_MB_MODE_FAVOR_S1_Pos)
#define JPEGENC_SWREG262_MB_MODE_FAVOR_S1  JPEGENC_SWREG262_MB_MODE_FAVOR_S1_Msk
#define JPEGENC_SWREG262_SKIP_MODE_PEN_S1_Pos  (16U)
#define JPEGENC_SWREG262_SKIP_MODE_PEN_S1_Msk  (0xFFUL << JPEGENC_SWREG262_SKIP_MODE_PEN_S1_Pos)
#define JPEGENC_SWREG262_SKIP_MODE_PEN_S1  JPEGENC_SWREG262_SKIP_MODE_PEN_S1_Msk
#define JPEGENC_SWREG262_PVAL_S1_Pos    (24U)
#define JPEGENC_SWREG262_PVAL_S1_Msk    (0xFFUL << JPEGENC_SWREG262_PVAL_S1_Pos)
#define JPEGENC_SWREG262_PVAL_S1        JPEGENC_SWREG262_PVAL_S1_Msk

/**************** Bit definition for JPEGENC_SWREG273 register ****************/
#define JPEGENC_SWREG273_BIT_COST_S2_Pos  (0U)
#define JPEGENC_SWREG273_BIT_COST_S2_Msk  (0xFFFUL << JPEGENC_SWREG273_BIT_COST_S2_Pos)
#define JPEGENC_SWREG273_BIT_COST_S2    JPEGENC_SWREG273_BIT_COST_S2_Msk
#define JPEGENC_SWREG273_MODE_FAVOR_S2_Pos  (12U)
#define JPEGENC_SWREG273_MODE_FAVOR_S2_Msk  (0xFFFFUL << JPEGENC_SWREG273_MODE_FAVOR_S2_Pos)
#define JPEGENC_SWREG273_MODE_FAVOR_S2  JPEGENC_SWREG273_MODE_FAVOR_S2_Msk

/**************** Bit definition for JPEGENC_SWREG274 register ****************/
#define JPEGENC_SWREG274_MB_MODE_FAVOR_S2_Pos  (0U)
#define JPEGENC_SWREG274_MB_MODE_FAVOR_S2_Msk  (0xFFFFUL << JPEGENC_SWREG274_MB_MODE_FAVOR_S2_Pos)
#define JPEGENC_SWREG274_MB_MODE_FAVOR_S2  JPEGENC_SWREG274_MB_MODE_FAVOR_S2_Msk
#define JPEGENC_SWREG274_SKIP_MODE_PEN_S2_Pos  (16U)
#define JPEGENC_SWREG274_SKIP_MODE_PEN_S2_Msk  (0xFFUL << JPEGENC_SWREG274_SKIP_MODE_PEN_S2_Pos)
#define JPEGENC_SWREG274_SKIP_MODE_PEN_S2  JPEGENC_SWREG274_SKIP_MODE_PEN_S2_Msk
#define JPEGENC_SWREG274_PVAL_S2_Pos    (24U)
#define JPEGENC_SWREG274_PVAL_S2_Msk    (0xFFUL << JPEGENC_SWREG274_PVAL_S2_Pos)
#define JPEGENC_SWREG274_PVAL_S2        JPEGENC_SWREG274_PVAL_S2_Msk

/**************** Bit definition for JPEGENC_SWREG285 register ****************/
#define JPEGENC_SWREG285_BIT_COST_S3_Pos  (0U)
#define JPEGENC_SWREG285_BIT_COST_S3_Msk  (0xFFFUL << JPEGENC_SWREG285_BIT_COST_S3_Pos)
#define JPEGENC_SWREG285_BIT_COST_S3    JPEGENC_SWREG285_BIT_COST_S3_Msk
#define JPEGENC_SWREG285_MODE_FAVOR_S3_Pos  (12U)
#define JPEGENC_SWREG285_MODE_FAVOR_S3_Msk  (0xFFFFUL << JPEGENC_SWREG285_MODE_FAVOR_S3_Pos)
#define JPEGENC_SWREG285_MODE_FAVOR_S3  JPEGENC_SWREG285_MODE_FAVOR_S3_Msk

/**************** Bit definition for JPEGENC_SWREG286 register ****************/
#define JPEGENC_SWREG286_MB_MODE_FAVOR_S3_Pos  (0U)
#define JPEGENC_SWREG286_MB_MODE_FAVOR_S3_Msk  (0xFFFFUL << JPEGENC_SWREG286_MB_MODE_FAVOR_S3_Pos)
#define JPEGENC_SWREG286_MB_MODE_FAVOR_S3  JPEGENC_SWREG286_MB_MODE_FAVOR_S3_Msk
#define JPEGENC_SWREG286_SKIP_MODE_PEN_S3_Pos  (16U)
#define JPEGENC_SWREG286_SKIP_MODE_PEN_S3_Msk  (0xFFUL << JPEGENC_SWREG286_SKIP_MODE_PEN_S3_Pos)
#define JPEGENC_SWREG286_SKIP_MODE_PEN_S3  JPEGENC_SWREG286_SKIP_MODE_PEN_S3_Msk
#define JPEGENC_SWREG286_PVAL_S3_Pos    (24U)
#define JPEGENC_SWREG286_PVAL_S3_Msk    (0xFFUL << JPEGENC_SWREG286_PVAL_S3_Pos)
#define JPEGENC_SWREG286_PVAL_S3        JPEGENC_SWREG286_PVAL_S3_Msk

/**************** Bit definition for JPEGENC_SWREG292 register ****************/
#define JPEGENC_SWREG292_VP8_AVG_VAR_Pos  (0U)
#define JPEGENC_SWREG292_VP8_AVG_VAR_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG292_VP8_AVG_VAR_Pos)
#define JPEGENC_SWREG292_VP8_AVG_VAR    JPEGENC_SWREG292_VP8_AVG_VAR_Msk

/**************** Bit definition for JPEGENC_SWREG293 register ****************/
#define JPEGENC_SWREG293_VP8_AVG_VAR_DIV_Pos  (0U)
#define JPEGENC_SWREG293_VP8_AVG_VAR_DIV_Msk  (0xFFFFUL << JPEGENC_SWREG293_VP8_AVG_VAR_DIV_Pos)
#define JPEGENC_SWREG293_VP8_AVG_VAR_DIV  JPEGENC_SWREG293_VP8_AVG_VAR_DIV_Msk
#define JPEGENC_SWREG293_H264_FIELDPICFLAG_Pos  (16U)
#define JPEGENC_SWREG293_H264_FIELDPICFLAG_Msk  (0x1UL << JPEGENC_SWREG293_H264_FIELDPICFLAG_Pos)
#define JPEGENC_SWREG293_H264_FIELDPICFLAG  JPEGENC_SWREG293_H264_FIELDPICFLAG_Msk
#define JPEGENC_SWREG293_H264_BOTFIELDFLAG_Pos  (17U)
#define JPEGENC_SWREG293_H264_BOTFIELDFLAG_Msk  (0x1UL << JPEGENC_SWREG293_H264_BOTFIELDFLAG_Pos)
#define JPEGENC_SWREG293_H264_BOTFIELDFLAG  JPEGENC_SWREG293_H264_BOTFIELDFLAG_Msk
#define JPEGENC_SWREG293_H264_FP_COND_Pos  (18U)
#define JPEGENC_SWREG293_H264_FP_COND_Msk  (0x3UL << JPEGENC_SWREG293_H264_FP_COND_Pos)
#define JPEGENC_SWREG293_H264_FP_COND   JPEGENC_SWREG293_H264_FP_COND_Msk

/**************** Bit definition for JPEGENC_SWREG294 register ****************/
#define JPEGENC_SWREG294_MB_BQP_Pos     (0U)
#define JPEGENC_SWREG294_MB_BQP_Msk     (0x3FUL << JPEGENC_SWREG294_MB_BQP_Pos)
#define JPEGENC_SWREG294_MB_BQP         JPEGENC_SWREG294_MB_BQP_Msk
#define JPEGENC_SWREG294_MB_BVAR1_Pos   (6U)
#define JPEGENC_SWREG294_MB_BVAR1_Msk   (0x1FFFUL << JPEGENC_SWREG294_MB_BVAR1_Pos)
#define JPEGENC_SWREG294_MB_BVAR1       JPEGENC_SWREG294_MB_BVAR1_Msk
#define JPEGENC_SWREG294_MB_BVAR2_Pos   (19U)
#define JPEGENC_SWREG294_MB_BVAR2_Msk   (0x1FFFUL << JPEGENC_SWREG294_MB_BVAR2_Pos)
#define JPEGENC_SWREG294_MB_BVAR2       JPEGENC_SWREG294_MB_BVAR2_Msk

/**************** Bit definition for JPEGENC_SWREG295 register ****************/
#define JPEGENC_SWREG295_VAR_LIMIT_Pos  (0U)
#define JPEGENC_SWREG295_VAR_LIMIT_Msk  (0xFUL << JPEGENC_SWREG295_VAR_LIMIT_Pos)
#define JPEGENC_SWREG295_VAR_LIMIT      JPEGENC_SWREG295_VAR_LIMIT_Msk
#define JPEGENC_SWREG295_VAR_INTERFAVOR_Pos  (4U)
#define JPEGENC_SWREG295_VAR_INTERFAVOR_Msk  (0xFUL << JPEGENC_SWREG295_VAR_INTERFAVOR_Pos)
#define JPEGENC_SWREG295_VAR_INTERFAVOR  JPEGENC_SWREG295_VAR_INTERFAVOR_Msk
#define JPEGENC_SWREG295_VAR_MULT_Pos   (8U)
#define JPEGENC_SWREG295_VAR_MULT_Msk   (0x1FUL << JPEGENC_SWREG295_VAR_MULT_Pos)
#define JPEGENC_SWREG295_VAR_MULT       JPEGENC_SWREG295_VAR_MULT_Msk
#define JPEGENC_SWREG295_VAR_ADD_Pos    (13U)
#define JPEGENC_SWREG295_VAR_ADD_Msk    (0x7UL << JPEGENC_SWREG295_VAR_ADD_Pos)
#define JPEGENC_SWREG295_VAR_ADD        JPEGENC_SWREG295_VAR_ADD_Msk
#define JPEGENC_SWREG295_PSKIP_CODING_MODE_Pos  (16U)
#define JPEGENC_SWREG295_PSKIP_CODING_MODE_Msk  (0x1UL << JPEGENC_SWREG295_PSKIP_CODING_MODE_Pos)
#define JPEGENC_SWREG295_PSKIP_CODING_MODE  JPEGENC_SWREG295_PSKIP_CODING_MODE_Msk

/**************** Bit definition for JPEGENC_SWREG296 register ****************/
#define JPEGENC_SWREG296_HW_IN_LB_Pos   (22U)
#define JPEGENC_SWREG296_HW_IN_LB_Msk   (0x1UL << JPEGENC_SWREG296_HW_IN_LB_Pos)
#define JPEGENC_SWREG296_HW_IN_LB       JPEGENC_SWREG296_HW_IN_LB_Msk
#define JPEGENC_SWREG296_HW_IRQ_CLR_Pos  (23U)
#define JPEGENC_SWREG296_HW_IRQ_CLR_Msk  (0x1UL << JPEGENC_SWREG296_HW_IRQ_CLR_Pos)
#define JPEGENC_SWREG296_HW_IRQ_CLR     JPEGENC_SWREG296_HW_IRQ_CLR_Msk
#define JPEGENC_SWREG296_HW_AXI_RID_Pos  (24U)
#define JPEGENC_SWREG296_HW_AXI_RID_Msk  (0x1UL << JPEGENC_SWREG296_HW_AXI_RID_Pos)
#define JPEGENC_SWREG296_HW_AXI_RID     JPEGENC_SWREG296_HW_AXI_RID_Msk
#define JPEGENC_SWREG296_HW_SVCT_Pos    (25U)
#define JPEGENC_SWREG296_HW_SVCT_Msk    (0x1UL << JPEGENC_SWREG296_HW_SVCT_Pos)
#define JPEGENC_SWREG296_HW_SVCT        JPEGENC_SWREG296_HW_SVCT_Msk
#define JPEGENC_SWREG296_HW_LOW_LAT_Pos  (26U)
#define JPEGENC_SWREG296_HW_LOW_LAT_Msk  (0x1UL << JPEGENC_SWREG296_HW_LOW_LAT_Pos)
#define JPEGENC_SWREG296_HW_LOW_LAT     JPEGENC_SWREG296_HW_LOW_LAT_Msk
#define JPEGENC_SWREG296_HW_ENHANCE_Pos  (27U)
#define JPEGENC_SWREG296_HW_ENHANCE_Msk  (0x1UL << JPEGENC_SWREG296_HW_ENHANCE_Pos)
#define JPEGENC_SWREG296_HW_ENHANCE     JPEGENC_SWREG296_HW_ENHANCE_Msk
#define JPEGENC_SWREG296_HW_REF_COMP_Pos  (28U)
#define JPEGENC_SWREG296_HW_REF_COMP_Msk  (0x3UL << JPEGENC_SWREG296_HW_REF_COMP_Pos)
#define JPEGENC_SWREG296_HW_REF_COMP    JPEGENC_SWREG296_HW_REF_COMP_Msk
#define JPEGENC_SWREG296_HW_DENOISE_Pos  (30U)
#define JPEGENC_SWREG296_HW_DENOISE_Msk  (0x1UL << JPEGENC_SWREG296_HW_DENOISE_Pos)
#define JPEGENC_SWREG296_HW_DENOISE     JPEGENC_SWREG296_HW_DENOISE_Msk
#define JPEGENC_SWREG296_HW_ADDR_BW_Pos  (31U)
#define JPEGENC_SWREG296_HW_ADDR_BW_Msk  (0x1UL << JPEGENC_SWREG296_HW_ADDR_BW_Pos)
#define JPEGENC_SWREG296_HW_ADDR_BW     JPEGENC_SWREG296_HW_ADDR_BW_Msk

/**************** Bit definition for JPEGENC_SWREG410 register ****************/
#define JPEGENC_SWREG410_MB_RC_EN_Pos   (0U)
#define JPEGENC_SWREG410_MB_RC_EN_Msk   (0x3UL << JPEGENC_SWREG410_MB_RC_EN_Pos)
#define JPEGENC_SWREG410_MB_RC_EN       JPEGENC_SWREG410_MB_RC_EN_Msk
#define JPEGENC_SWREG410_MB_COMP_OFFSET_Pos  (7U)
#define JPEGENC_SWREG410_MB_COMP_OFFSET_Msk  (0x1FUL << JPEGENC_SWREG410_MB_COMP_OFFSET_Pos)
#define JPEGENC_SWREG410_MB_COMP_OFFSET  JPEGENC_SWREG410_MB_COMP_OFFSET_Msk
#define JPEGENC_SWREG410_FFP_Pos        (16U)
#define JPEGENC_SWREG410_FFP_Msk        (0xFFFFUL << JPEGENC_SWREG410_FFP_Pos)
#define JPEGENC_SWREG410_FFP            JPEGENC_SWREG410_FFP_Msk

/**************** Bit definition for JPEGENC_SWREG411 register ****************/
#define JPEGENC_SWREG411_MB_GAIN_Pos    (0U)
#define JPEGENC_SWREG411_MB_GAIN_Msk    (0xFFFFUL << JPEGENC_SWREG411_MB_GAIN_Pos)
#define JPEGENC_SWREG411_MB_GAIN        JPEGENC_SWREG411_MB_GAIN_Msk

/**************** Bit definition for JPEGENC_SWREG412 register ****************/
#define JPEGENC_SWREG412_AVG_MB_COMP_Pos  (0U)
#define JPEGENC_SWREG412_AVG_MB_COMP_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG412_AVG_MB_COMP_Pos)
#define JPEGENC_SWREG412_AVG_MB_COMP    JPEGENC_SWREG412_AVG_MB_COMP_Msk

/**************** Bit definition for JPEGENC_SWREG497 register ****************/
#define JPEGENC_SWREG497_FILLED_MB_ROWS_Pos  (0U)
#define JPEGENC_SWREG497_FILLED_MB_ROWS_Msk  (0x1FFUL << JPEGENC_SWREG497_FILLED_MB_ROWS_Pos)
#define JPEGENC_SWREG497_FILLED_MB_ROWS  JPEGENC_SWREG497_FILLED_MB_ROWS_Msk
#define JPEGENC_SWREG497_RDOUT_MB_ROWS_Pos  (9U)
#define JPEGENC_SWREG497_RDOUT_MB_ROWS_Msk  (0x1FFUL << JPEGENC_SWREG497_RDOUT_MB_ROWS_Pos)
#define JPEGENC_SWREG497_RDOUT_MB_ROWS  JPEGENC_SWREG497_RDOUT_MB_ROWS_Msk
#define JPEGENC_SWREG497_FETCHED_MB_ROWS_Pos  (18U)
#define JPEGENC_SWREG497_FETCHED_MB_ROWS_Msk  (0x1FFUL << JPEGENC_SWREG497_FETCHED_MB_ROWS_Pos)
#define JPEGENC_SWREG497_FETCHED_MB_ROWS  JPEGENC_SWREG497_FETCHED_MB_ROWS_Msk
#define JPEGENC_SWREG497_LB_EN_Pos      (27U)
#define JPEGENC_SWREG497_LB_EN_Msk      (0x1UL << JPEGENC_SWREG497_LB_EN_Pos)
#define JPEGENC_SWREG497_LB_EN          JPEGENC_SWREG497_LB_EN_Msk
#define JPEGENC_SWREG497_IB_LB_EN_Pos   (28U)
#define JPEGENC_SWREG497_IB_LB_EN_Msk   (0x1UL << JPEGENC_SWREG497_IB_LB_EN_Pos)
#define JPEGENC_SWREG497_IB_LB_EN       JPEGENC_SWREG497_IB_LB_EN_Msk
#define JPEGENC_SWREG497_LLHW_INTF_EN_Pos  (29U)
#define JPEGENC_SWREG497_LLHW_INTF_EN_Msk  (0x1UL << JPEGENC_SWREG497_LLHW_INTF_EN_Pos)
#define JPEGENC_SWREG497_LLHW_INTF_EN   JPEGENC_SWREG497_LLHW_INTF_EN_Msk
#define JPEGENC_SWREG497_IB_UF_INT_EN_Pos  (30U)
#define JPEGENC_SWREG497_IB_UF_INT_EN_Msk  (0x1UL << JPEGENC_SWREG497_IB_UF_INT_EN_Pos)
#define JPEGENC_SWREG497_IB_UF_INT_EN   JPEGENC_SWREG497_IB_UF_INT_EN_Msk

/**************** Bit definition for JPEGENC_SWREG498 register ****************/
#define JPEGENC_SWREG498_LB_OFFSET_Pos  (0U)
#define JPEGENC_SWREG498_LB_OFFSET_Msk  (0xFFFFFFFFUL << JPEGENC_SWREG498_LB_OFFSET_Pos)
#define JPEGENC_SWREG498_LB_OFFSET      JPEGENC_SWREG498_LB_OFFSET_Msk

#endif
