#ifndef __JPEGDEC_H
#define __JPEGDEC_H

typedef struct
{
    __IO uint32_t SWREG0;
    __IO uint32_t SWREG1;
    __IO uint32_t SWREG2;
    __IO uint32_t SWREG3;
    __IO uint32_t SWREG4;
    __IO uint32_t SWREG5;
    __IO uint32_t SWREG6;
    __IO uint32_t RSVD8[5];
    __IO uint32_t SWREG12;
    __IO uint32_t SWREG13;
    __IO uint32_t SWREG14;
    __IO uint32_t SWREG15;
    __IO uint32_t SWREG16;
    __IO uint32_t SWREG17;
    __IO uint32_t SWREG18;
    __IO uint32_t SWREG19;
    __IO uint32_t SWREG20;
    __IO uint32_t SWREG21;
    __IO uint32_t SWREG22;
    __IO uint32_t SWREG23;
    __IO uint32_t SWREG24;
    __IO uint32_t SWREG25;
    __IO uint32_t SWREG26;
    __IO uint32_t SWREG27;
    __IO uint32_t SWREG28;
    __IO uint32_t RSVD7[11];
    __IO uint32_t SWREG40;
    __IO uint32_t SWREG41;
    __IO uint32_t RSVD6[8];
    __IO uint32_t SWREG50;
    __IO uint32_t RSVD5[3];
    __IO uint32_t SWREG54;
    __IO uint32_t RSVD4[2];
    __IO uint32_t SWREG57;
    __IO uint32_t SWREG58;
    __IO uint32_t RSVD3;
    __IO uint32_t SWREG60;
    __IO uint32_t SWREG61;
    __IO uint32_t SWREG62;
    __IO uint32_t SWREG63;
    __IO uint32_t SWREG64;
    __IO uint32_t SWREG65;
    __IO uint32_t SWREG66;
    __IO uint32_t SWREG67;
    __IO uint32_t SWREG68;
    __IO uint32_t SWREG69;
    __IO uint32_t SWREG70;
    __IO uint32_t SWREG71;
    __IO uint32_t SWREG72;
    __IO uint32_t SWREG73;
    __IO uint32_t SWREG74;
    __IO uint32_t RSVD2[4];
    __IO uint32_t SWREG79;
    __IO uint32_t SWREG80;
    __IO uint32_t SWREG81;
    __IO uint32_t SWREG82;
    __IO uint32_t SWREG83;
    __IO uint32_t SWREG84;
    __IO uint32_t SWREG85;
    __IO uint32_t SWREG86;
    __IO uint32_t SWREG87;
    __IO uint32_t SWREG88;
    __IO uint32_t SWREG89;
    __IO uint32_t SWREG90;
    __IO uint32_t SWREG91;
    __IO uint32_t SWREG92;
    __IO uint32_t SWREG93;
    __IO uint32_t SWREG94;
    __IO uint32_t SWREG95;
    __IO uint32_t RSVD1[3];
    __IO uint32_t SWREG99;
    __IO uint32_t SWREG100;
} JPEGDEC_TypeDef;


/***************** Bit definition for JPEGDEC_SWREG0 register *****************/
#define JPEGDEC_SWREG0_BD_VER_Pos       (0U)
#define JPEGDEC_SWREG0_BD_VER_Msk       (0xFUL << JPEGDEC_SWREG0_BD_VER_Pos)
#define JPEGDEC_SWREG0_BD_VER           JPEGDEC_SWREG0_BD_VER_Msk
#define JPEGDEC_SWREG0_MAJ_VER_Pos      (12U)
#define JPEGDEC_SWREG0_MAJ_VER_Msk      (0xFUL << JPEGDEC_SWREG0_MAJ_VER_Pos)
#define JPEGDEC_SWREG0_MAJ_VER          JPEGDEC_SWREG0_MAJ_VER_Msk
#define JPEGDEC_SWREG0_PN_Pos           (16U)
#define JPEGDEC_SWREG0_PN_Msk           (0xFFFFUL << JPEGDEC_SWREG0_PN_Pos)
#define JPEGDEC_SWREG0_PN               JPEGDEC_SWREG0_PN_Msk

/***************** Bit definition for JPEGDEC_SWREG1 register *****************/
#define JPEGDEC_SWREG1_DEC_EN_Pos       (0U)
#define JPEGDEC_SWREG1_DEC_EN_Msk       (0x1UL << JPEGDEC_SWREG1_DEC_EN_Pos)
#define JPEGDEC_SWREG1_DEC_EN           JPEGDEC_SWREG1_DEC_EN_Msk
#define JPEGDEC_SWREG1_DEC_IRQ_DIS_Pos  (4U)
#define JPEGDEC_SWREG1_DEC_IRQ_DIS_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_IRQ_DIS_Pos)
#define JPEGDEC_SWREG1_DEC_IRQ_DIS      JPEGDEC_SWREG1_DEC_IRQ_DIS_Msk
#define JPEGDEC_SWREG1_DEC_ABORT_EN_Pos  (5U)
#define JPEGDEC_SWREG1_DEC_ABORT_EN_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_ABORT_EN_Pos)
#define JPEGDEC_SWREG1_DEC_ABORT_EN     JPEGDEC_SWREG1_DEC_ABORT_EN_Msk
#define JPEGDEC_SWREG1_DEC_IRQ_Pos      (8U)
#define JPEGDEC_SWREG1_DEC_IRQ_Msk      (0x1UL << JPEGDEC_SWREG1_DEC_IRQ_Pos)
#define JPEGDEC_SWREG1_DEC_IRQ          JPEGDEC_SWREG1_DEC_IRQ_Msk
#define JPEGDEC_SWREG1_DEC_ABORT_INT_Pos  (11U)
#define JPEGDEC_SWREG1_DEC_ABORT_INT_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_ABORT_INT_Pos)
#define JPEGDEC_SWREG1_DEC_ABORT_INT    JPEGDEC_SWREG1_DEC_ABORT_INT_Msk
#define JPEGDEC_SWREG1_DEC_RDY_INT_Pos  (12U)
#define JPEGDEC_SWREG1_DEC_RDY_INT_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_RDY_INT_Pos)
#define JPEGDEC_SWREG1_DEC_RDY_INT      JPEGDEC_SWREG1_DEC_RDY_INT_Msk
#define JPEGDEC_SWREG1_DEC_BUS_INT_Pos  (13U)
#define JPEGDEC_SWREG1_DEC_BUS_INT_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_BUS_INT_Pos)
#define JPEGDEC_SWREG1_DEC_BUS_INT      JPEGDEC_SWREG1_DEC_BUS_INT_Msk
#define JPEGDEC_SWREG1_DEC_BUFFER_INT_Pos  (14U)
#define JPEGDEC_SWREG1_DEC_BUFFER_INT_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_BUFFER_INT_Pos)
#define JPEGDEC_SWREG1_DEC_BUFFER_INT   JPEGDEC_SWREG1_DEC_BUFFER_INT_Msk
#define JPEGDEC_SWREG1_DEC_ERROR_INT_Pos  (16U)
#define JPEGDEC_SWREG1_DEC_ERROR_INT_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_ERROR_INT_Pos)
#define JPEGDEC_SWREG1_DEC_ERROR_INT    JPEGDEC_SWREG1_DEC_ERROR_INT_Msk
#define JPEGDEC_SWREG1_DEC_SLICE_INT_Pos  (17U)
#define JPEGDEC_SWREG1_DEC_SLICE_INT_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_SLICE_INT_Pos)
#define JPEGDEC_SWREG1_DEC_SLICE_INT    JPEGDEC_SWREG1_DEC_SLICE_INT_Msk
#define JPEGDEC_SWREG1_DEC_TIMEOUT_Pos  (18U)
#define JPEGDEC_SWREG1_DEC_TIMEOUT_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_TIMEOUT_Pos)
#define JPEGDEC_SWREG1_DEC_TIMEOUT      JPEGDEC_SWREG1_DEC_TIMEOUT_Msk
#define JPEGDEC_SWREG1_DEC_PIC_INF_Pos  (24U)
#define JPEGDEC_SWREG1_DEC_PIC_INF_Msk  (0x1UL << JPEGDEC_SWREG1_DEC_PIC_INF_Pos)
#define JPEGDEC_SWREG1_DEC_PIC_INF      JPEGDEC_SWREG1_DEC_PIC_INF_Msk

/***************** Bit definition for JPEGDEC_SWREG2 register *****************/
#define JPEGDEC_SWREG2_DEC_MAX_BURST_Pos  (0U)
#define JPEGDEC_SWREG2_DEC_MAX_BURST_Msk  (0x1FUL << JPEGDEC_SWREG2_DEC_MAX_BURST_Pos)
#define JPEGDEC_SWREG2_DEC_MAX_BURST    JPEGDEC_SWREG2_DEC_MAX_BURST_Msk
#define JPEGDEC_SWREG2_DEC_SCMD_DIS_Pos  (5U)
#define JPEGDEC_SWREG2_DEC_SCMD_DIS_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_SCMD_DIS_Pos)
#define JPEGDEC_SWREG2_DEC_SCMD_DIS     JPEGDEC_SWREG2_DEC_SCMD_DIS_Msk
#define JPEGDEC_SWREG2_DEC_ADV_PRE_DIS_Pos  (6U)
#define JPEGDEC_SWREG2_DEC_ADV_PRE_DIS_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_ADV_PRE_DIS_Pos)
#define JPEGDEC_SWREG2_DEC_ADV_PRE_DIS  JPEGDEC_SWREG2_DEC_ADV_PRE_DIS_Msk
#define JPEGDEC_SWREG2_TILED_MODE_LSB_Pos  (7U)
#define JPEGDEC_SWREG2_TILED_MODE_LSB_Msk  (0x1UL << JPEGDEC_SWREG2_TILED_MODE_LSB_Pos)
#define JPEGDEC_SWREG2_TILED_MODE_LSB   JPEGDEC_SWREG2_TILED_MODE_LSB_Msk
#define JPEGDEC_SWREG2_DEC_OUT_ENDIAN_Pos  (8U)
#define JPEGDEC_SWREG2_DEC_OUT_ENDIAN_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_OUT_ENDIAN_Pos)
#define JPEGDEC_SWREG2_DEC_OUT_ENDIAN   JPEGDEC_SWREG2_DEC_OUT_ENDIAN_Msk
#define JPEGDEC_SWREG2_DEC_IN_ENDIAN_Pos  (9U)
#define JPEGDEC_SWREG2_DEC_IN_ENDIAN_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_IN_ENDIAN_Pos)
#define JPEGDEC_SWREG2_DEC_IN_ENDIAN    JPEGDEC_SWREG2_DEC_IN_ENDIAN_Msk
#define JPEGDEC_SWREG2_DEC_CLK_GATE_EN_Pos  (10U)
#define JPEGDEC_SWREG2_DEC_CLK_GATE_EN_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_CLK_GATE_EN_Pos)
#define JPEGDEC_SWREG2_DEC_CLK_GATE_EN  JPEGDEC_SWREG2_DEC_CLK_GATE_EN_Msk
#define JPEGDEC_SWREG2_DEC_LATENCY_Pos  (11U)
#define JPEGDEC_SWREG2_DEC_LATENCY_Msk  (0x3FUL << JPEGDEC_SWREG2_DEC_LATENCY_Pos)
#define JPEGDEC_SWREG2_DEC_LATENCY      JPEGDEC_SWREG2_DEC_LATENCY_Msk
#define JPEGDEC_SWREG2_DEC_DATA_DISC_EN_Pos  (18U)
#define JPEGDEC_SWREG2_DEC_DATA_DISC_EN_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_DATA_DISC_EN_Pos)
#define JPEGDEC_SWREG2_DEC_DATA_DISC_EN  JPEGDEC_SWREG2_DEC_DATA_DISC_EN_Msk
#define JPEGDEC_SWREG2_DEC_OUTSWAP32_EN_Pos  (19U)
#define JPEGDEC_SWREG2_DEC_OUTSWAP32_EN_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_OUTSWAP32_EN_Pos)
#define JPEGDEC_SWREG2_DEC_OUTSWAP32_EN  JPEGDEC_SWREG2_DEC_OUTSWAP32_EN_Msk
#define JPEGDEC_SWREG2_DEC_INSWAP32_EN_Pos  (20U)
#define JPEGDEC_SWREG2_DEC_INSWAP32_EN_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_INSWAP32_EN_Pos)
#define JPEGDEC_SWREG2_DEC_INSWAP32_EN  JPEGDEC_SWREG2_DEC_INSWAP32_EN_Msk
#define JPEGDEC_SWREG2_DEC_STRENDIAN_EN_Pos  (21U)
#define JPEGDEC_SWREG2_DEC_STRENDIAN_EN_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_STRENDIAN_EN_Pos)
#define JPEGDEC_SWREG2_DEC_STRENDIAN_EN  JPEGDEC_SWREG2_DEC_STRENDIAN_EN_Msk
#define JPEGDEC_SWREG2_DEC_STRSWAP32_EN_Pos  (22U)
#define JPEGDEC_SWREG2_DEC_STRSWAP32_EN_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_STRSWAP32_EN_Pos)
#define JPEGDEC_SWREG2_DEC_STRSWAP32_EN  JPEGDEC_SWREG2_DEC_STRSWAP32_EN_Msk
#define JPEGDEC_SWREG2_DEC_TIMEOUT_EN_Pos  (23U)
#define JPEGDEC_SWREG2_DEC_TIMEOUT_EN_Msk  (0x1UL << JPEGDEC_SWREG2_DEC_TIMEOUT_EN_Pos)
#define JPEGDEC_SWREG2_DEC_TIMEOUT_EN   JPEGDEC_SWREG2_DEC_TIMEOUT_EN_Msk

/***************** Bit definition for JPEGDEC_SWREG3 register *****************/
#define JPEGDEC_SWREG3_DEC_AHB_HLOCK_EN_Pos  (8U)
#define JPEGDEC_SWREG3_DEC_AHB_HLOCK_EN_Msk  (0x1UL << JPEGDEC_SWREG3_DEC_AHB_HLOCK_EN_Pos)
#define JPEGDEC_SWREG3_DEC_AHB_HLOCK_EN  JPEGDEC_SWREG3_DEC_AHB_HLOCK_EN_Msk
#define JPEGDEC_SWREG3_DEC_OUT_DIS_Pos  (15U)
#define JPEGDEC_SWREG3_DEC_OUT_DIS_Msk  (0x1UL << JPEGDEC_SWREG3_DEC_OUT_DIS_Pos)
#define JPEGDEC_SWREG3_DEC_OUT_DIS      JPEGDEC_SWREG3_DEC_OUT_DIS_Msk
#define JPEGDEC_SWREG3_PJPEG_EN_Pos     (24U)
#define JPEGDEC_SWREG3_PJPEG_EN_Msk     (0x1UL << JPEGDEC_SWREG3_PJPEG_EN_Pos)
#define JPEGDEC_SWREG3_PJPEG_EN         JPEGDEC_SWREG3_PJPEG_EN_Msk
#define JPEGDEC_SWREG3_DEC_MODE_Pos     (28U)
#define JPEGDEC_SWREG3_DEC_MODE_Msk     (0xFUL << JPEGDEC_SWREG3_DEC_MODE_Pos)
#define JPEGDEC_SWREG3_DEC_MODE         JPEGDEC_SWREG3_DEC_MODE_Msk

/***************** Bit definition for JPEGDEC_SWREG4 register *****************/
#define JPEGDEC_SWREG4_PIC_MB_H_EXT_Pos  (0U)
#define JPEGDEC_SWREG4_PIC_MB_H_EXT_Msk  (0x7UL << JPEGDEC_SWREG4_PIC_MB_H_EXT_Pos)
#define JPEGDEC_SWREG4_PIC_MB_H_EXT     JPEGDEC_SWREG4_PIC_MB_H_EXT_Msk
#define JPEGDEC_SWREG4_PIC_MB_W_EXT_Pos  (3U)
#define JPEGDEC_SWREG4_PIC_MB_W_EXT_Msk  (0x7UL << JPEGDEC_SWREG4_PIC_MB_W_EXT_Pos)
#define JPEGDEC_SWREG4_PIC_MB_W_EXT     JPEGDEC_SWREG4_PIC_MB_W_EXT_Msk
#define JPEGDEC_SWREG4_PIC_MB_HEIGHT_P_Pos  (11U)
#define JPEGDEC_SWREG4_PIC_MB_HEIGHT_P_Msk  (0xFFUL << JPEGDEC_SWREG4_PIC_MB_HEIGHT_P_Pos)
#define JPEGDEC_SWREG4_PIC_MB_HEIGHT_P  JPEGDEC_SWREG4_PIC_MB_HEIGHT_P_Msk
#define JPEGDEC_SWREG4_PIC_MB_WIDTH_Pos  (23U)
#define JPEGDEC_SWREG4_PIC_MB_WIDTH_Msk  (0x1FFUL << JPEGDEC_SWREG4_PIC_MB_WIDTH_Pos)
#define JPEGDEC_SWREG4_PIC_MB_WIDTH     JPEGDEC_SWREG4_PIC_MB_WIDTH_Msk

/***************** Bit definition for JPEGDEC_SWREG5 register *****************/
#define JPEGDEC_SWREG5_CB_DC_VLCTABLE3_Pos  (0U)
#define JPEGDEC_SWREG5_CB_DC_VLCTABLE3_Msk  (0x1UL << JPEGDEC_SWREG5_CB_DC_VLCTABLE3_Pos)
#define JPEGDEC_SWREG5_CB_DC_VLCTABLE3  JPEGDEC_SWREG5_CB_DC_VLCTABLE3_Msk
#define JPEGDEC_SWREG5_CR_DC_VLCTABLE3_Pos  (1U)
#define JPEGDEC_SWREG5_CR_DC_VLCTABLE3_Msk  (0x1UL << JPEGDEC_SWREG5_CR_DC_VLCTABLE3_Pos)
#define JPEGDEC_SWREG5_CR_DC_VLCTABLE3  JPEGDEC_SWREG5_CR_DC_VLCTABLE3_Msk
#define JPEGDEC_SWREG5_CB_DC_VLCTABLE_Pos  (2U)
#define JPEGDEC_SWREG5_CB_DC_VLCTABLE_Msk  (0x1UL << JPEGDEC_SWREG5_CB_DC_VLCTABLE_Pos)
#define JPEGDEC_SWREG5_CB_DC_VLCTABLE   JPEGDEC_SWREG5_CB_DC_VLCTABLE_Msk
#define JPEGDEC_SWREG5_CR_DC_VLCTABLE_Pos  (3U)
#define JPEGDEC_SWREG5_CR_DC_VLCTABLE_Msk  (0x1UL << JPEGDEC_SWREG5_CR_DC_VLCTABLE_Pos)
#define JPEGDEC_SWREG5_CR_DC_VLCTABLE   JPEGDEC_SWREG5_CR_DC_VLCTABLE_Msk
#define JPEGDEC_SWREG5_CB_AC_VLCTABLE_Pos  (4U)
#define JPEGDEC_SWREG5_CB_AC_VLCTABLE_Msk  (0x1UL << JPEGDEC_SWREG5_CB_AC_VLCTABLE_Pos)
#define JPEGDEC_SWREG5_CB_AC_VLCTABLE   JPEGDEC_SWREG5_CB_AC_VLCTABLE_Msk
#define JPEGDEC_SWREG5_CR_AC_VLCTABLE_Pos  (5U)
#define JPEGDEC_SWREG5_CR_AC_VLCTABLE_Msk  (0x1UL << JPEGDEC_SWREG5_CR_AC_VLCTABLE_Pos)
#define JPEGDEC_SWREG5_CR_AC_VLCTABLE   JPEGDEC_SWREG5_CR_AC_VLCTABLE_Msk
#define JPEGDEC_SWREG5_JPEG_STREAM_ALL_Pos  (6U)
#define JPEGDEC_SWREG5_JPEG_STREAM_ALL_Msk  (0x1UL << JPEGDEC_SWREG5_JPEG_STREAM_ALL_Pos)
#define JPEGDEC_SWREG5_JPEG_STREAM_ALL  JPEGDEC_SWREG5_JPEG_STREAM_ALL_Msk
#define JPEGDEC_SWREG5_JPEG_FILRIGHT_E_Pos  (7U)
#define JPEGDEC_SWREG5_JPEG_FILRIGHT_E_Msk  (0x1UL << JPEGDEC_SWREG5_JPEG_FILRIGHT_E_Pos)
#define JPEGDEC_SWREG5_JPEG_FILRIGHT_E  JPEGDEC_SWREG5_JPEG_FILRIGHT_E_Msk
#define JPEGDEC_SWREG5_JPEG_MODE_Pos    (8U)
#define JPEGDEC_SWREG5_JPEG_MODE_Msk    (0x7UL << JPEGDEC_SWREG5_JPEG_MODE_Pos)
#define JPEGDEC_SWREG5_JPEG_MODE        JPEGDEC_SWREG5_JPEG_MODE_Msk
#define JPEGDEC_SWREG5_JPEG_QTABLES_Pos  (11U)
#define JPEGDEC_SWREG5_JPEG_QTABLES_Msk  (0x3UL << JPEGDEC_SWREG5_JPEG_QTABLES_Pos)
#define JPEGDEC_SWREG5_JPEG_QTABLES     JPEGDEC_SWREG5_JPEG_QTABLES_Msk
#define JPEGDEC_SWREG5_SYNC_MARKER_EN_Pos  (25U)
#define JPEGDEC_SWREG5_SYNC_MARKER_EN_Msk  (0x1UL << JPEGDEC_SWREG5_SYNC_MARKER_EN_Pos)
#define JPEGDEC_SWREG5_SYNC_MARKER_EN   JPEGDEC_SWREG5_SYNC_MARKER_EN_Msk
#define JPEGDEC_SWREG5_STRM_START_BIT_Pos  (26U)
#define JPEGDEC_SWREG5_STRM_START_BIT_Msk  (0x3FUL << JPEGDEC_SWREG5_STRM_START_BIT_Pos)
#define JPEGDEC_SWREG5_STRM_START_BIT   JPEGDEC_SWREG5_STRM_START_BIT_Msk

/***************** Bit definition for JPEGDEC_SWREG6 register *****************/
#define JPEGDEC_SWREG6_STREAM_LEN_Pos   (0U)
#define JPEGDEC_SWREG6_STREAM_LEN_Msk   (0xFFFFFFUL << JPEGDEC_SWREG6_STREAM_LEN_Pos)
#define JPEGDEC_SWREG6_STREAM_LEN       JPEGDEC_SWREG6_STREAM_LEN_Msk

/**************** Bit definition for JPEGDEC_SWREG12 register *****************/
#define JPEGDEC_SWREG12_RLC_VLC_BASE_Pos  (2U)
#define JPEGDEC_SWREG12_RLC_VLC_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG12_RLC_VLC_BASE_Pos)
#define JPEGDEC_SWREG12_RLC_VLC_BASE    JPEGDEC_SWREG12_RLC_VLC_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG13 register *****************/
#define JPEGDEC_SWREG13_DEC_OUT_BASE_Pos  (2U)
#define JPEGDEC_SWREG13_DEC_OUT_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG13_DEC_OUT_BASE_Pos)
#define JPEGDEC_SWREG13_DEC_OUT_BASE    JPEGDEC_SWREG13_DEC_OUT_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG14 register *****************/
#define JPEGDEC_SWREG14_JPG_CH_OUT_BASE_Pos  (2U)
#define JPEGDEC_SWREG14_JPG_CH_OUT_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG14_JPG_CH_OUT_BASE_Pos)
#define JPEGDEC_SWREG14_JPG_CH_OUT_BASE  JPEGDEC_SWREG14_JPG_CH_OUT_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG15 register *****************/
#define JPEGDEC_SWREG15_JPEG_SLICE_H_Pos  (0U)
#define JPEGDEC_SWREG15_JPEG_SLICE_H_Msk  (0xFFUL << JPEGDEC_SWREG15_JPEG_SLICE_H_Pos)
#define JPEGDEC_SWREG15_JPEG_SLICE_H    JPEGDEC_SWREG15_JPEG_SLICE_H_Msk

/**************** Bit definition for JPEGDEC_SWREG16 register *****************/
#define JPEGDEC_SWREG16_AC1_CODE1_CNT_Pos  (0U)
#define JPEGDEC_SWREG16_AC1_CODE1_CNT_Msk  (0x3UL << JPEGDEC_SWREG16_AC1_CODE1_CNT_Pos)
#define JPEGDEC_SWREG16_AC1_CODE1_CNT   JPEGDEC_SWREG16_AC1_CODE1_CNT_Msk
#define JPEGDEC_SWREG16_AC1_CODE2_CNT_Pos  (3U)
#define JPEGDEC_SWREG16_AC1_CODE2_CNT_Msk  (0x7UL << JPEGDEC_SWREG16_AC1_CODE2_CNT_Pos)
#define JPEGDEC_SWREG16_AC1_CODE2_CNT   JPEGDEC_SWREG16_AC1_CODE2_CNT_Msk
#define JPEGDEC_SWREG16_AC1_CODE3_CNT_Pos  (7U)
#define JPEGDEC_SWREG16_AC1_CODE3_CNT_Msk  (0xFUL << JPEGDEC_SWREG16_AC1_CODE3_CNT_Pos)
#define JPEGDEC_SWREG16_AC1_CODE3_CNT   JPEGDEC_SWREG16_AC1_CODE3_CNT_Msk
#define JPEGDEC_SWREG16_AC1_CODE4_CNT_Pos  (11U)
#define JPEGDEC_SWREG16_AC1_CODE4_CNT_Msk  (0x1FUL << JPEGDEC_SWREG16_AC1_CODE4_CNT_Pos)
#define JPEGDEC_SWREG16_AC1_CODE4_CNT   JPEGDEC_SWREG16_AC1_CODE4_CNT_Msk
#define JPEGDEC_SWREG16_AC1_CODE5_CNT_Pos  (16U)
#define JPEGDEC_SWREG16_AC1_CODE5_CNT_Msk  (0x3FUL << JPEGDEC_SWREG16_AC1_CODE5_CNT_Pos)
#define JPEGDEC_SWREG16_AC1_CODE5_CNT   JPEGDEC_SWREG16_AC1_CODE5_CNT_Msk
#define JPEGDEC_SWREG16_AC1_CODE6_CNT_Pos  (24U)
#define JPEGDEC_SWREG16_AC1_CODE6_CNT_Msk  (0x7FUL << JPEGDEC_SWREG16_AC1_CODE6_CNT_Pos)
#define JPEGDEC_SWREG16_AC1_CODE6_CNT   JPEGDEC_SWREG16_AC1_CODE6_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG17 register *****************/
#define JPEGDEC_SWREG17_AC1_CODE7_CNT_Pos  (0U)
#define JPEGDEC_SWREG17_AC1_CODE7_CNT_Msk  (0xFFUL << JPEGDEC_SWREG17_AC1_CODE7_CNT_Pos)
#define JPEGDEC_SWREG17_AC1_CODE7_CNT   JPEGDEC_SWREG17_AC1_CODE7_CNT_Msk
#define JPEGDEC_SWREG17_AC1_CODE8_CNT_Pos  (8U)
#define JPEGDEC_SWREG17_AC1_CODE8_CNT_Msk  (0xFFUL << JPEGDEC_SWREG17_AC1_CODE8_CNT_Pos)
#define JPEGDEC_SWREG17_AC1_CODE8_CNT   JPEGDEC_SWREG17_AC1_CODE8_CNT_Msk
#define JPEGDEC_SWREG17_AC1_CODE9_CNT_Pos  (16U)
#define JPEGDEC_SWREG17_AC1_CODE9_CNT_Msk  (0xFFUL << JPEGDEC_SWREG17_AC1_CODE9_CNT_Pos)
#define JPEGDEC_SWREG17_AC1_CODE9_CNT   JPEGDEC_SWREG17_AC1_CODE9_CNT_Msk
#define JPEGDEC_SWREG17_AC1_CODE10_CNT_Pos  (24U)
#define JPEGDEC_SWREG17_AC1_CODE10_CNT_Msk  (0xFFUL << JPEGDEC_SWREG17_AC1_CODE10_CNT_Pos)
#define JPEGDEC_SWREG17_AC1_CODE10_CNT  JPEGDEC_SWREG17_AC1_CODE10_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG18 register *****************/
#define JPEGDEC_SWREG18_AC1_CODE11_CNT_Pos  (0U)
#define JPEGDEC_SWREG18_AC1_CODE11_CNT_Msk  (0xFFUL << JPEGDEC_SWREG18_AC1_CODE11_CNT_Pos)
#define JPEGDEC_SWREG18_AC1_CODE11_CNT  JPEGDEC_SWREG18_AC1_CODE11_CNT_Msk
#define JPEGDEC_SWREG18_AC1_CODE12_CNT_Pos  (8U)
#define JPEGDEC_SWREG18_AC1_CODE12_CNT_Msk  (0xFFUL << JPEGDEC_SWREG18_AC1_CODE12_CNT_Pos)
#define JPEGDEC_SWREG18_AC1_CODE12_CNT  JPEGDEC_SWREG18_AC1_CODE12_CNT_Msk
#define JPEGDEC_SWREG18_AC1_CODE13_CNT_Pos  (16U)
#define JPEGDEC_SWREG18_AC1_CODE13_CNT_Msk  (0xFFUL << JPEGDEC_SWREG18_AC1_CODE13_CNT_Pos)
#define JPEGDEC_SWREG18_AC1_CODE13_CNT  JPEGDEC_SWREG18_AC1_CODE13_CNT_Msk
#define JPEGDEC_SWREG18_AC1_CODE14_CNT_Pos  (24U)
#define JPEGDEC_SWREG18_AC1_CODE14_CNT_Msk  (0xFFUL << JPEGDEC_SWREG18_AC1_CODE14_CNT_Pos)
#define JPEGDEC_SWREG18_AC1_CODE14_CNT  JPEGDEC_SWREG18_AC1_CODE14_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG19 register *****************/
#define JPEGDEC_SWREG19_AC1_CODE15_CNT_Pos  (0U)
#define JPEGDEC_SWREG19_AC1_CODE15_CNT_Msk  (0xFFUL << JPEGDEC_SWREG19_AC1_CODE15_CNT_Pos)
#define JPEGDEC_SWREG19_AC1_CODE15_CNT  JPEGDEC_SWREG19_AC1_CODE15_CNT_Msk
#define JPEGDEC_SWREG19_AC1_CODE16_CNT_Pos  (8U)
#define JPEGDEC_SWREG19_AC1_CODE16_CNT_Msk  (0xFFUL << JPEGDEC_SWREG19_AC1_CODE16_CNT_Pos)
#define JPEGDEC_SWREG19_AC1_CODE16_CNT  JPEGDEC_SWREG19_AC1_CODE16_CNT_Msk
#define JPEGDEC_SWREG19_AC2_CODE1_CNT_Pos  (16U)
#define JPEGDEC_SWREG19_AC2_CODE1_CNT_Msk  (0x3UL << JPEGDEC_SWREG19_AC2_CODE1_CNT_Pos)
#define JPEGDEC_SWREG19_AC2_CODE1_CNT   JPEGDEC_SWREG19_AC2_CODE1_CNT_Msk
#define JPEGDEC_SWREG19_AC2_CODE2_CNT_Pos  (19U)
#define JPEGDEC_SWREG19_AC2_CODE2_CNT_Msk  (0x7UL << JPEGDEC_SWREG19_AC2_CODE2_CNT_Pos)
#define JPEGDEC_SWREG19_AC2_CODE2_CNT   JPEGDEC_SWREG19_AC2_CODE2_CNT_Msk
#define JPEGDEC_SWREG19_AC2_CODE3_CNT_Pos  (23U)
#define JPEGDEC_SWREG19_AC2_CODE3_CNT_Msk  (0xFUL << JPEGDEC_SWREG19_AC2_CODE3_CNT_Pos)
#define JPEGDEC_SWREG19_AC2_CODE3_CNT   JPEGDEC_SWREG19_AC2_CODE3_CNT_Msk
#define JPEGDEC_SWREG19_AC2_CODE4_CNT_Pos  (27U)
#define JPEGDEC_SWREG19_AC2_CODE4_CNT_Msk  (0x1FUL << JPEGDEC_SWREG19_AC2_CODE4_CNT_Pos)
#define JPEGDEC_SWREG19_AC2_CODE4_CNT   JPEGDEC_SWREG19_AC2_CODE4_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG20 register *****************/
#define JPEGDEC_SWREG20_AC2_CODE5_CNT_Pos  (0U)
#define JPEGDEC_SWREG20_AC2_CODE5_CNT_Msk  (0x3FUL << JPEGDEC_SWREG20_AC2_CODE5_CNT_Pos)
#define JPEGDEC_SWREG20_AC2_CODE5_CNT   JPEGDEC_SWREG20_AC2_CODE5_CNT_Msk
#define JPEGDEC_SWREG20_AC2_CODE6_CNT_Pos  (8U)
#define JPEGDEC_SWREG20_AC2_CODE6_CNT_Msk  (0x7FUL << JPEGDEC_SWREG20_AC2_CODE6_CNT_Pos)
#define JPEGDEC_SWREG20_AC2_CODE6_CNT   JPEGDEC_SWREG20_AC2_CODE6_CNT_Msk
#define JPEGDEC_SWREG20_AC2_CODE7_CNT_Pos  (16U)
#define JPEGDEC_SWREG20_AC2_CODE7_CNT_Msk  (0xFFUL << JPEGDEC_SWREG20_AC2_CODE7_CNT_Pos)
#define JPEGDEC_SWREG20_AC2_CODE7_CNT   JPEGDEC_SWREG20_AC2_CODE7_CNT_Msk
#define JPEGDEC_SWREG20_AC2_CODE8_CNT_Pos  (24U)
#define JPEGDEC_SWREG20_AC2_CODE8_CNT_Msk  (0xFFUL << JPEGDEC_SWREG20_AC2_CODE8_CNT_Pos)
#define JPEGDEC_SWREG20_AC2_CODE8_CNT   JPEGDEC_SWREG20_AC2_CODE8_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG21 register *****************/
#define JPEGDEC_SWREG21_AC2_CODE9_CNT_Pos  (0U)
#define JPEGDEC_SWREG21_AC2_CODE9_CNT_Msk  (0xFFUL << JPEGDEC_SWREG21_AC2_CODE9_CNT_Pos)
#define JPEGDEC_SWREG21_AC2_CODE9_CNT   JPEGDEC_SWREG21_AC2_CODE9_CNT_Msk
#define JPEGDEC_SWREG21_AC2_CODE10_CNT_Pos  (8U)
#define JPEGDEC_SWREG21_AC2_CODE10_CNT_Msk  (0xFFUL << JPEGDEC_SWREG21_AC2_CODE10_CNT_Pos)
#define JPEGDEC_SWREG21_AC2_CODE10_CNT  JPEGDEC_SWREG21_AC2_CODE10_CNT_Msk
#define JPEGDEC_SWREG21_AC2_CODE11_CNT_Pos  (16U)
#define JPEGDEC_SWREG21_AC2_CODE11_CNT_Msk  (0xFFUL << JPEGDEC_SWREG21_AC2_CODE11_CNT_Pos)
#define JPEGDEC_SWREG21_AC2_CODE11_CNT  JPEGDEC_SWREG21_AC2_CODE11_CNT_Msk
#define JPEGDEC_SWREG21_AC2_CODE12_CNT_Pos  (24U)
#define JPEGDEC_SWREG21_AC2_CODE12_CNT_Msk  (0xFFUL << JPEGDEC_SWREG21_AC2_CODE12_CNT_Pos)
#define JPEGDEC_SWREG21_AC2_CODE12_CNT  JPEGDEC_SWREG21_AC2_CODE12_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG22 register *****************/
#define JPEGDEC_SWREG22_AC2_CODE13_CNT_Pos  (0U)
#define JPEGDEC_SWREG22_AC2_CODE13_CNT_Msk  (0xFFUL << JPEGDEC_SWREG22_AC2_CODE13_CNT_Pos)
#define JPEGDEC_SWREG22_AC2_CODE13_CNT  JPEGDEC_SWREG22_AC2_CODE13_CNT_Msk
#define JPEGDEC_SWREG22_AC2_CODE14_CNT_Pos  (8U)
#define JPEGDEC_SWREG22_AC2_CODE14_CNT_Msk  (0xFFUL << JPEGDEC_SWREG22_AC2_CODE14_CNT_Pos)
#define JPEGDEC_SWREG22_AC2_CODE14_CNT  JPEGDEC_SWREG22_AC2_CODE14_CNT_Msk
#define JPEGDEC_SWREG22_AC2_CODE15_CNT_Pos  (16U)
#define JPEGDEC_SWREG22_AC2_CODE15_CNT_Msk  (0xFFUL << JPEGDEC_SWREG22_AC2_CODE15_CNT_Pos)
#define JPEGDEC_SWREG22_AC2_CODE15_CNT  JPEGDEC_SWREG22_AC2_CODE15_CNT_Msk
#define JPEGDEC_SWREG22_AC2_CODE16_CNT_Pos  (24U)
#define JPEGDEC_SWREG22_AC2_CODE16_CNT_Msk  (0xFFUL << JPEGDEC_SWREG22_AC2_CODE16_CNT_Pos)
#define JPEGDEC_SWREG22_AC2_CODE16_CNT  JPEGDEC_SWREG22_AC2_CODE16_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG23 register *****************/
#define JPEGDEC_SWREG23_DC1_CODE1_CNT_Pos  (0U)
#define JPEGDEC_SWREG23_DC1_CODE1_CNT_Msk  (0x3UL << JPEGDEC_SWREG23_DC1_CODE1_CNT_Pos)
#define JPEGDEC_SWREG23_DC1_CODE1_CNT   JPEGDEC_SWREG23_DC1_CODE1_CNT_Msk
#define JPEGDEC_SWREG23_DC1_CODE2_CNT_Pos  (4U)
#define JPEGDEC_SWREG23_DC1_CODE2_CNT_Msk  (0x7UL << JPEGDEC_SWREG23_DC1_CODE2_CNT_Pos)
#define JPEGDEC_SWREG23_DC1_CODE2_CNT   JPEGDEC_SWREG23_DC1_CODE2_CNT_Msk
#define JPEGDEC_SWREG23_DC1_CODE3_CNT_Pos  (8U)
#define JPEGDEC_SWREG23_DC1_CODE3_CNT_Msk  (0xFUL << JPEGDEC_SWREG23_DC1_CODE3_CNT_Pos)
#define JPEGDEC_SWREG23_DC1_CODE3_CNT   JPEGDEC_SWREG23_DC1_CODE3_CNT_Msk
#define JPEGDEC_SWREG23_DC1_CODE4_CNT_Pos  (12U)
#define JPEGDEC_SWREG23_DC1_CODE4_CNT_Msk  (0xFUL << JPEGDEC_SWREG23_DC1_CODE4_CNT_Pos)
#define JPEGDEC_SWREG23_DC1_CODE4_CNT   JPEGDEC_SWREG23_DC1_CODE4_CNT_Msk
#define JPEGDEC_SWREG23_DC1_CODE5_CNT_Pos  (16U)
#define JPEGDEC_SWREG23_DC1_CODE5_CNT_Msk  (0xFUL << JPEGDEC_SWREG23_DC1_CODE5_CNT_Pos)
#define JPEGDEC_SWREG23_DC1_CODE5_CNT   JPEGDEC_SWREG23_DC1_CODE5_CNT_Msk
#define JPEGDEC_SWREG23_DC1_CODE6_CNT_Pos  (20U)
#define JPEGDEC_SWREG23_DC1_CODE6_CNT_Msk  (0xFUL << JPEGDEC_SWREG23_DC1_CODE6_CNT_Pos)
#define JPEGDEC_SWREG23_DC1_CODE6_CNT   JPEGDEC_SWREG23_DC1_CODE6_CNT_Msk
#define JPEGDEC_SWREG23_DC1_CODE7_CNT_Pos  (24U)
#define JPEGDEC_SWREG23_DC1_CODE7_CNT_Msk  (0xFUL << JPEGDEC_SWREG23_DC1_CODE7_CNT_Pos)
#define JPEGDEC_SWREG23_DC1_CODE7_CNT   JPEGDEC_SWREG23_DC1_CODE7_CNT_Msk
#define JPEGDEC_SWREG23_DC1_CODE8_CNT_Pos  (28U)
#define JPEGDEC_SWREG23_DC1_CODE8_CNT_Msk  (0xFUL << JPEGDEC_SWREG23_DC1_CODE8_CNT_Pos)
#define JPEGDEC_SWREG23_DC1_CODE8_CNT   JPEGDEC_SWREG23_DC1_CODE8_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG24 register *****************/
#define JPEGDEC_SWREG24_DC1_CODE9_CNT_Pos  (0U)
#define JPEGDEC_SWREG24_DC1_CODE9_CNT_Msk  (0xFUL << JPEGDEC_SWREG24_DC1_CODE9_CNT_Pos)
#define JPEGDEC_SWREG24_DC1_CODE9_CNT   JPEGDEC_SWREG24_DC1_CODE9_CNT_Msk
#define JPEGDEC_SWREG24_DC1_CODE10_CNT_Pos  (4U)
#define JPEGDEC_SWREG24_DC1_CODE10_CNT_Msk  (0xFUL << JPEGDEC_SWREG24_DC1_CODE10_CNT_Pos)
#define JPEGDEC_SWREG24_DC1_CODE10_CNT  JPEGDEC_SWREG24_DC1_CODE10_CNT_Msk
#define JPEGDEC_SWREG24_DC1_CODE11_CNT_Pos  (8U)
#define JPEGDEC_SWREG24_DC1_CODE11_CNT_Msk  (0xFUL << JPEGDEC_SWREG24_DC1_CODE11_CNT_Pos)
#define JPEGDEC_SWREG24_DC1_CODE11_CNT  JPEGDEC_SWREG24_DC1_CODE11_CNT_Msk
#define JPEGDEC_SWREG24_DC1_CODE12_CNT_Pos  (12U)
#define JPEGDEC_SWREG24_DC1_CODE12_CNT_Msk  (0xFUL << JPEGDEC_SWREG24_DC1_CODE12_CNT_Pos)
#define JPEGDEC_SWREG24_DC1_CODE12_CNT  JPEGDEC_SWREG24_DC1_CODE12_CNT_Msk
#define JPEGDEC_SWREG24_DC1_CODE13_CNT_Pos  (16U)
#define JPEGDEC_SWREG24_DC1_CODE13_CNT_Msk  (0xFUL << JPEGDEC_SWREG24_DC1_CODE13_CNT_Pos)
#define JPEGDEC_SWREG24_DC1_CODE13_CNT  JPEGDEC_SWREG24_DC1_CODE13_CNT_Msk
#define JPEGDEC_SWREG24_DC1_CODE14_CNT_Pos  (20U)
#define JPEGDEC_SWREG24_DC1_CODE14_CNT_Msk  (0xFUL << JPEGDEC_SWREG24_DC1_CODE14_CNT_Pos)
#define JPEGDEC_SWREG24_DC1_CODE14_CNT  JPEGDEC_SWREG24_DC1_CODE14_CNT_Msk
#define JPEGDEC_SWREG24_DC1_CODE15_CNT_Pos  (24U)
#define JPEGDEC_SWREG24_DC1_CODE15_CNT_Msk  (0xFUL << JPEGDEC_SWREG24_DC1_CODE15_CNT_Pos)
#define JPEGDEC_SWREG24_DC1_CODE15_CNT  JPEGDEC_SWREG24_DC1_CODE15_CNT_Msk
#define JPEGDEC_SWREG24_DC1_CODE16_CNT_Pos  (28U)
#define JPEGDEC_SWREG24_DC1_CODE16_CNT_Msk  (0xFUL << JPEGDEC_SWREG24_DC1_CODE16_CNT_Pos)
#define JPEGDEC_SWREG24_DC1_CODE16_CNT  JPEGDEC_SWREG24_DC1_CODE16_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG25 register *****************/
#define JPEGDEC_SWREG25_DC2_CODE1_CNT_Pos  (0U)
#define JPEGDEC_SWREG25_DC2_CODE1_CNT_Msk  (0x3UL << JPEGDEC_SWREG25_DC2_CODE1_CNT_Pos)
#define JPEGDEC_SWREG25_DC2_CODE1_CNT   JPEGDEC_SWREG25_DC2_CODE1_CNT_Msk
#define JPEGDEC_SWREG25_DC2_CODE2_CNT_Pos  (4U)
#define JPEGDEC_SWREG25_DC2_CODE2_CNT_Msk  (0x7UL << JPEGDEC_SWREG25_DC2_CODE2_CNT_Pos)
#define JPEGDEC_SWREG25_DC2_CODE2_CNT   JPEGDEC_SWREG25_DC2_CODE2_CNT_Msk
#define JPEGDEC_SWREG25_DC2_CODE3_CNT_Pos  (8U)
#define JPEGDEC_SWREG25_DC2_CODE3_CNT_Msk  (0xFUL << JPEGDEC_SWREG25_DC2_CODE3_CNT_Pos)
#define JPEGDEC_SWREG25_DC2_CODE3_CNT   JPEGDEC_SWREG25_DC2_CODE3_CNT_Msk
#define JPEGDEC_SWREG25_DC2_CODE4_CNT_Pos  (12U)
#define JPEGDEC_SWREG25_DC2_CODE4_CNT_Msk  (0xFUL << JPEGDEC_SWREG25_DC2_CODE4_CNT_Pos)
#define JPEGDEC_SWREG25_DC2_CODE4_CNT   JPEGDEC_SWREG25_DC2_CODE4_CNT_Msk
#define JPEGDEC_SWREG25_DC2_CODE5_CNT_Pos  (16U)
#define JPEGDEC_SWREG25_DC2_CODE5_CNT_Msk  (0xFUL << JPEGDEC_SWREG25_DC2_CODE5_CNT_Pos)
#define JPEGDEC_SWREG25_DC2_CODE5_CNT   JPEGDEC_SWREG25_DC2_CODE5_CNT_Msk
#define JPEGDEC_SWREG25_DC2_CODE6_CNT_Pos  (20U)
#define JPEGDEC_SWREG25_DC2_CODE6_CNT_Msk  (0xFUL << JPEGDEC_SWREG25_DC2_CODE6_CNT_Pos)
#define JPEGDEC_SWREG25_DC2_CODE6_CNT   JPEGDEC_SWREG25_DC2_CODE6_CNT_Msk
#define JPEGDEC_SWREG25_DC2_CODE7_CNT_Pos  (24U)
#define JPEGDEC_SWREG25_DC2_CODE7_CNT_Msk  (0xFUL << JPEGDEC_SWREG25_DC2_CODE7_CNT_Pos)
#define JPEGDEC_SWREG25_DC2_CODE7_CNT   JPEGDEC_SWREG25_DC2_CODE7_CNT_Msk
#define JPEGDEC_SWREG25_DC2_CODE8_CNT_Pos  (28U)
#define JPEGDEC_SWREG25_DC2_CODE8_CNT_Msk  (0xFUL << JPEGDEC_SWREG25_DC2_CODE8_CNT_Pos)
#define JPEGDEC_SWREG25_DC2_CODE8_CNT   JPEGDEC_SWREG25_DC2_CODE8_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG26 register *****************/
#define JPEGDEC_SWREG26_DC2_CODE9_CNT_Pos  (0U)
#define JPEGDEC_SWREG26_DC2_CODE9_CNT_Msk  (0xFUL << JPEGDEC_SWREG26_DC2_CODE9_CNT_Pos)
#define JPEGDEC_SWREG26_DC2_CODE9_CNT   JPEGDEC_SWREG26_DC2_CODE9_CNT_Msk
#define JPEGDEC_SWREG26_DC2_CODE10_CNT_Pos  (4U)
#define JPEGDEC_SWREG26_DC2_CODE10_CNT_Msk  (0xFUL << JPEGDEC_SWREG26_DC2_CODE10_CNT_Pos)
#define JPEGDEC_SWREG26_DC2_CODE10_CNT  JPEGDEC_SWREG26_DC2_CODE10_CNT_Msk
#define JPEGDEC_SWREG26_DC2_CODE11_CNT_Pos  (8U)
#define JPEGDEC_SWREG26_DC2_CODE11_CNT_Msk  (0xFUL << JPEGDEC_SWREG26_DC2_CODE11_CNT_Pos)
#define JPEGDEC_SWREG26_DC2_CODE11_CNT  JPEGDEC_SWREG26_DC2_CODE11_CNT_Msk
#define JPEGDEC_SWREG26_DC2_CODE12_CNT_Pos  (12U)
#define JPEGDEC_SWREG26_DC2_CODE12_CNT_Msk  (0xFUL << JPEGDEC_SWREG26_DC2_CODE12_CNT_Pos)
#define JPEGDEC_SWREG26_DC2_CODE12_CNT  JPEGDEC_SWREG26_DC2_CODE12_CNT_Msk
#define JPEGDEC_SWREG26_DC2_CODE13_CNT_Pos  (16U)
#define JPEGDEC_SWREG26_DC2_CODE13_CNT_Msk  (0xFUL << JPEGDEC_SWREG26_DC2_CODE13_CNT_Pos)
#define JPEGDEC_SWREG26_DC2_CODE13_CNT  JPEGDEC_SWREG26_DC2_CODE13_CNT_Msk
#define JPEGDEC_SWREG26_DC2_CODE14_CNT_Pos  (20U)
#define JPEGDEC_SWREG26_DC2_CODE14_CNT_Msk  (0xFUL << JPEGDEC_SWREG26_DC2_CODE14_CNT_Pos)
#define JPEGDEC_SWREG26_DC2_CODE14_CNT  JPEGDEC_SWREG26_DC2_CODE14_CNT_Msk
#define JPEGDEC_SWREG26_DC2_CODE15_CNT_Pos  (24U)
#define JPEGDEC_SWREG26_DC2_CODE15_CNT_Msk  (0xFUL << JPEGDEC_SWREG26_DC2_CODE15_CNT_Pos)
#define JPEGDEC_SWREG26_DC2_CODE15_CNT  JPEGDEC_SWREG26_DC2_CODE15_CNT_Msk
#define JPEGDEC_SWREG26_DC2_CODE16_CNT_Pos  (28U)
#define JPEGDEC_SWREG26_DC2_CODE16_CNT_Msk  (0xFUL << JPEGDEC_SWREG26_DC2_CODE16_CNT_Pos)
#define JPEGDEC_SWREG26_DC2_CODE16_CNT  JPEGDEC_SWREG26_DC2_CODE16_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG27 register *****************/
#define JPEGDEC_SWREG27_DC3_CODE1_CNT_Pos  (0U)
#define JPEGDEC_SWREG27_DC3_CODE1_CNT_Msk  (0x3UL << JPEGDEC_SWREG27_DC3_CODE1_CNT_Pos)
#define JPEGDEC_SWREG27_DC3_CODE1_CNT   JPEGDEC_SWREG27_DC3_CODE1_CNT_Msk
#define JPEGDEC_SWREG27_DC3_CODE2_CNT_Pos  (4U)
#define JPEGDEC_SWREG27_DC3_CODE2_CNT_Msk  (0x7UL << JPEGDEC_SWREG27_DC3_CODE2_CNT_Pos)
#define JPEGDEC_SWREG27_DC3_CODE2_CNT   JPEGDEC_SWREG27_DC3_CODE2_CNT_Msk
#define JPEGDEC_SWREG27_DC3_CODE3_CNT_Pos  (8U)
#define JPEGDEC_SWREG27_DC3_CODE3_CNT_Msk  (0xFUL << JPEGDEC_SWREG27_DC3_CODE3_CNT_Pos)
#define JPEGDEC_SWREG27_DC3_CODE3_CNT   JPEGDEC_SWREG27_DC3_CODE3_CNT_Msk
#define JPEGDEC_SWREG27_DC3_CODE4_CNT_Pos  (12U)
#define JPEGDEC_SWREG27_DC3_CODE4_CNT_Msk  (0xFUL << JPEGDEC_SWREG27_DC3_CODE4_CNT_Pos)
#define JPEGDEC_SWREG27_DC3_CODE4_CNT   JPEGDEC_SWREG27_DC3_CODE4_CNT_Msk
#define JPEGDEC_SWREG27_DC3_CODE5_CNT_Pos  (16U)
#define JPEGDEC_SWREG27_DC3_CODE5_CNT_Msk  (0xFUL << JPEGDEC_SWREG27_DC3_CODE5_CNT_Pos)
#define JPEGDEC_SWREG27_DC3_CODE5_CNT   JPEGDEC_SWREG27_DC3_CODE5_CNT_Msk
#define JPEGDEC_SWREG27_DC3_CODE6_CNT_Pos  (20U)
#define JPEGDEC_SWREG27_DC3_CODE6_CNT_Msk  (0xFUL << JPEGDEC_SWREG27_DC3_CODE6_CNT_Pos)
#define JPEGDEC_SWREG27_DC3_CODE6_CNT   JPEGDEC_SWREG27_DC3_CODE6_CNT_Msk
#define JPEGDEC_SWREG27_DC3_CODE7_CNT_Pos  (24U)
#define JPEGDEC_SWREG27_DC3_CODE7_CNT_Msk  (0xFUL << JPEGDEC_SWREG27_DC3_CODE7_CNT_Pos)
#define JPEGDEC_SWREG27_DC3_CODE7_CNT   JPEGDEC_SWREG27_DC3_CODE7_CNT_Msk
#define JPEGDEC_SWREG27_DC3_CODE8_CNT_Pos  (28U)
#define JPEGDEC_SWREG27_DC3_CODE8_CNT_Msk  (0xFUL << JPEGDEC_SWREG27_DC3_CODE8_CNT_Pos)
#define JPEGDEC_SWREG27_DC3_CODE8_CNT   JPEGDEC_SWREG27_DC3_CODE8_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG28 register *****************/
#define JPEGDEC_SWREG28_DC3_CODE9_CNT_Pos  (0U)
#define JPEGDEC_SWREG28_DC3_CODE9_CNT_Msk  (0xFUL << JPEGDEC_SWREG28_DC3_CODE9_CNT_Pos)
#define JPEGDEC_SWREG28_DC3_CODE9_CNT   JPEGDEC_SWREG28_DC3_CODE9_CNT_Msk
#define JPEGDEC_SWREG28_DC3_CODE10_CNT_Pos  (4U)
#define JPEGDEC_SWREG28_DC3_CODE10_CNT_Msk  (0xFUL << JPEGDEC_SWREG28_DC3_CODE10_CNT_Pos)
#define JPEGDEC_SWREG28_DC3_CODE10_CNT  JPEGDEC_SWREG28_DC3_CODE10_CNT_Msk
#define JPEGDEC_SWREG28_DC3_CODE11_CNT_Pos  (8U)
#define JPEGDEC_SWREG28_DC3_CODE11_CNT_Msk  (0xFUL << JPEGDEC_SWREG28_DC3_CODE11_CNT_Pos)
#define JPEGDEC_SWREG28_DC3_CODE11_CNT  JPEGDEC_SWREG28_DC3_CODE11_CNT_Msk
#define JPEGDEC_SWREG28_DC3_CODE12_CNT_Pos  (12U)
#define JPEGDEC_SWREG28_DC3_CODE12_CNT_Msk  (0xFUL << JPEGDEC_SWREG28_DC3_CODE12_CNT_Pos)
#define JPEGDEC_SWREG28_DC3_CODE12_CNT  JPEGDEC_SWREG28_DC3_CODE12_CNT_Msk
#define JPEGDEC_SWREG28_DC3_CODE13_CNT_Pos  (16U)
#define JPEGDEC_SWREG28_DC3_CODE13_CNT_Msk  (0xFUL << JPEGDEC_SWREG28_DC3_CODE13_CNT_Pos)
#define JPEGDEC_SWREG28_DC3_CODE13_CNT  JPEGDEC_SWREG28_DC3_CODE13_CNT_Msk
#define JPEGDEC_SWREG28_DC3_CODE14_CNT_Pos  (20U)
#define JPEGDEC_SWREG28_DC3_CODE14_CNT_Msk  (0xFUL << JPEGDEC_SWREG28_DC3_CODE14_CNT_Pos)
#define JPEGDEC_SWREG28_DC3_CODE14_CNT  JPEGDEC_SWREG28_DC3_CODE14_CNT_Msk
#define JPEGDEC_SWREG28_DC3_CODE15_CNT_Pos  (24U)
#define JPEGDEC_SWREG28_DC3_CODE15_CNT_Msk  (0xFUL << JPEGDEC_SWREG28_DC3_CODE15_CNT_Pos)
#define JPEGDEC_SWREG28_DC3_CODE15_CNT  JPEGDEC_SWREG28_DC3_CODE15_CNT_Msk
#define JPEGDEC_SWREG28_DC3_CODE16_CNT_Pos  (28U)
#define JPEGDEC_SWREG28_DC3_CODE16_CNT_Msk  (0xFUL << JPEGDEC_SWREG28_DC3_CODE16_CNT_Pos)
#define JPEGDEC_SWREG28_DC3_CODE16_CNT  JPEGDEC_SWREG28_DC3_CODE16_CNT_Msk

/**************** Bit definition for JPEGDEC_SWREG40 register *****************/
#define JPEGDEC_SWREG40_QTABLE_BASE_Pos  (2U)
#define JPEGDEC_SWREG40_QTABLE_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG40_QTABLE_BASE_Pos)
#define JPEGDEC_SWREG40_QTABLE_BASE     JPEGDEC_SWREG40_QTABLE_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG41 register *****************/
#define JPEGDEC_SWREG41_DIR_MV_BASE_Pos  (2U)
#define JPEGDEC_SWREG41_DIR_MV_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG41_DIR_MV_BASE_Pos)
#define JPEGDEC_SWREG41_DIR_MV_BASE     JPEGDEC_SWREG41_DIR_MV_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG50 register *****************/
#define JPEGDEC_SWREG50_DEC_MAX_OWIDTH_Pos  (0U)
#define JPEGDEC_SWREG50_DEC_MAX_OWIDTH_Msk  (0x7FFUL << JPEGDEC_SWREG50_DEC_MAX_OWIDTH_Pos)
#define JPEGDEC_SWREG50_DEC_MAX_OWIDTH  JPEGDEC_SWREG50_DEC_MAX_OWIDTH_Msk
#define JPEGDEC_SWREG50_DEC_BUS_WIDTH_Pos  (12U)
#define JPEGDEC_SWREG50_DEC_BUS_WIDTH_Msk  (0x3UL << JPEGDEC_SWREG50_DEC_BUS_WIDTH_Pos)
#define JPEGDEC_SWREG50_DEC_BUS_WIDTH   JPEGDEC_SWREG50_DEC_BUS_WIDTH_Msk
#define JPEGDEC_SWREG50_DEC_SYNTH_LAN_Pos  (14U)
#define JPEGDEC_SWREG50_DEC_SYNTH_LAN_Msk  (0x3UL << JPEGDEC_SWREG50_DEC_SYNTH_LAN_Pos)
#define JPEGDEC_SWREG50_DEC_SYNTH_LAN   JPEGDEC_SWREG50_DEC_SYNTH_LAN_Msk
#define JPEGDEC_SWREG50_DEC_BUS_STRD_Pos  (16U)
#define JPEGDEC_SWREG50_DEC_BUS_STRD_Msk  (0xFUL << JPEGDEC_SWREG50_DEC_BUS_STRD_Pos)
#define JPEGDEC_SWREG50_DEC_BUS_STRD    JPEGDEC_SWREG50_DEC_BUS_STRD_Msk
#define JPEGDEC_SWREG50_DEC_PJPEG_EXIST_Pos  (22U)
#define JPEGDEC_SWREG50_DEC_PJPEG_EXIST_Msk  (0x1UL << JPEGDEC_SWREG50_DEC_PJPEG_EXIST_Pos)
#define JPEGDEC_SWREG50_DEC_PJPEG_EXIST  JPEGDEC_SWREG50_DEC_PJPEG_EXIST_Msk
#define JPEGDEC_SWREG50_DEC_JPEG_PROF_Pos  (28U)
#define JPEGDEC_SWREG50_DEC_JPEG_PROF_Msk  (0x1UL << JPEGDEC_SWREG50_DEC_JPEG_PROF_Pos)
#define JPEGDEC_SWREG50_DEC_JPEG_PROF   JPEGDEC_SWREG50_DEC_JPEG_PROF_Msk

/**************** Bit definition for JPEGDEC_SWREG54 register *****************/
#define JPEGDEC_SWREG54_DEC_CORE_AM_Pos  (7U)
#define JPEGDEC_SWREG54_DEC_CORE_AM_Msk  (0x7UL << JPEGDEC_SWREG54_DEC_CORE_AM_Pos)
#define JPEGDEC_SWREG54_DEC_CORE_AM     JPEGDEC_SWREG54_DEC_CORE_AM_Msk
#define JPEGDEC_SWREG54_DPB_FIELD_E_Pos  (10U)
#define JPEGDEC_SWREG54_DPB_FIELD_E_Msk  (0x1UL << JPEGDEC_SWREG54_DPB_FIELD_E_Pos)
#define JPEGDEC_SWREG54_DPB_FIELD_E     JPEGDEC_SWREG54_DPB_FIELD_E_Msk
#define JPEGDEC_SWREG54_DEC_JPEG_EXTENS_Pos  (31U)
#define JPEGDEC_SWREG54_DEC_JPEG_EXTENS_Msk  (0x1UL << JPEGDEC_SWREG54_DEC_JPEG_EXTENS_Pos)
#define JPEGDEC_SWREG54_DEC_JPEG_EXTENS  JPEGDEC_SWREG54_DEC_JPEG_EXTENS_Msk

/**************** Bit definition for JPEGDEC_SWREG57 register *****************/
#define JPEGDEC_SWREG57_FUSE_DEC_MAXW_4K_Pos  (16U)
#define JPEGDEC_SWREG57_FUSE_DEC_MAXW_4K_Msk  (0x1UL << JPEGDEC_SWREG57_FUSE_DEC_MAXW_4K_Pos)
#define JPEGDEC_SWREG57_FUSE_DEC_MAXW_4K  JPEGDEC_SWREG57_FUSE_DEC_MAXW_4K_Msk
#define JPEGDEC_SWREG57_FUSE_DEC_PJPEG_Pos  (24U)
#define JPEGDEC_SWREG57_FUSE_DEC_PJPEG_Msk  (0x1UL << JPEGDEC_SWREG57_FUSE_DEC_PJPEG_Pos)
#define JPEGDEC_SWREG57_FUSE_DEC_PJPEG  JPEGDEC_SWREG57_FUSE_DEC_PJPEG_Msk
#define JPEGDEC_SWREG57_FUSE_DEC_JPEG_Pos  (27U)
#define JPEGDEC_SWREG57_FUSE_DEC_JPEG_Msk  (0x1UL << JPEGDEC_SWREG57_FUSE_DEC_JPEG_Pos)
#define JPEGDEC_SWREG57_FUSE_DEC_JPEG   JPEGDEC_SWREG57_FUSE_DEC_JPEG_Msk

/**************** Bit definition for JPEGDEC_SWREG58 register *****************/
#define JPEGDEC_SWREG58_SERV_MERGE_DIS_Pos  (31U)
#define JPEGDEC_SWREG58_SERV_MERGE_DIS_Msk  (0x1UL << JPEGDEC_SWREG58_SERV_MERGE_DIS_Pos)
#define JPEGDEC_SWREG58_SERV_MERGE_DIS  JPEGDEC_SWREG58_SERV_MERGE_DIS_Msk

/**************** Bit definition for JPEGDEC_SWREG60 register *****************/
#define JPEGDEC_SWREG60_PP_EN_Pos       (0U)
#define JPEGDEC_SWREG60_PP_EN_Msk       (0x1UL << JPEGDEC_SWREG60_PP_EN_Pos)
#define JPEGDEC_SWREG60_PP_EN           JPEGDEC_SWREG60_PP_EN_Msk
#define JPEGDEC_SWREG60_PP_PIPELINE_EN_Pos  (1U)
#define JPEGDEC_SWREG60_PP_PIPELINE_EN_Msk  (0x1UL << JPEGDEC_SWREG60_PP_PIPELINE_EN_Pos)
#define JPEGDEC_SWREG60_PP_PIPELINE_EN  JPEGDEC_SWREG60_PP_PIPELINE_EN_Msk
#define JPEGDEC_SWREG60_PP_IRQ_DIS_Pos  (4U)
#define JPEGDEC_SWREG60_PP_IRQ_DIS_Msk  (0x1UL << JPEGDEC_SWREG60_PP_IRQ_DIS_Pos)
#define JPEGDEC_SWREG60_PP_IRQ_DIS      JPEGDEC_SWREG60_PP_IRQ_DIS_Msk
#define JPEGDEC_SWREG60_PP_IRQ_Pos      (8U)
#define JPEGDEC_SWREG60_PP_IRQ_Msk      (0x1UL << JPEGDEC_SWREG60_PP_IRQ_Pos)
#define JPEGDEC_SWREG60_PP_IRQ          JPEGDEC_SWREG60_PP_IRQ_Msk
#define JPEGDEC_SWREG60_PP_RDY_INT_Pos  (12U)
#define JPEGDEC_SWREG60_PP_RDY_INT_Msk  (0x1UL << JPEGDEC_SWREG60_PP_RDY_INT_Pos)
#define JPEGDEC_SWREG60_PP_RDY_INT      JPEGDEC_SWREG60_PP_RDY_INT_Msk
#define JPEGDEC_SWREG60_PP_BUS_INT_Pos  (13U)
#define JPEGDEC_SWREG60_PP_BUS_INT_Msk  (0x1UL << JPEGDEC_SWREG60_PP_BUS_INT_Pos)
#define JPEGDEC_SWREG60_PP_BUS_INT      JPEGDEC_SWREG60_PP_BUS_INT_Msk

/**************** Bit definition for JPEGDEC_SWREG61 register *****************/
#define JPEGDEC_SWREG61_PP_MAX_BURST_Pos  (0U)
#define JPEGDEC_SWREG61_PP_MAX_BURST_Msk  (0x1FUL << JPEGDEC_SWREG61_PP_MAX_BURST_Pos)
#define JPEGDEC_SWREG61_PP_MAX_BURST    JPEGDEC_SWREG61_PP_MAX_BURST_Msk
#define JPEGDEC_SWREG61_PP_OUT_SWAP32_E_Pos  (5U)
#define JPEGDEC_SWREG61_PP_OUT_SWAP32_E_Msk  (0x1UL << JPEGDEC_SWREG61_PP_OUT_SWAP32_E_Pos)
#define JPEGDEC_SWREG61_PP_OUT_SWAP32_E  JPEGDEC_SWREG61_PP_OUT_SWAP32_E_Msk
#define JPEGDEC_SWREG61_PP_OUT_ENDIAN_Pos  (6U)
#define JPEGDEC_SWREG61_PP_OUT_ENDIAN_Msk  (0x1UL << JPEGDEC_SWREG61_PP_OUT_ENDIAN_Pos)
#define JPEGDEC_SWREG61_PP_OUT_ENDIAN   JPEGDEC_SWREG61_PP_OUT_ENDIAN_Msk
#define JPEGDEC_SWREG61_PP_IN_ENDIAN_Pos  (7U)
#define JPEGDEC_SWREG61_PP_IN_ENDIAN_Msk  (0x1UL << JPEGDEC_SWREG61_PP_IN_ENDIAN_Pos)
#define JPEGDEC_SWREG61_PP_IN_ENDIAN    JPEGDEC_SWREG61_PP_IN_ENDIAN_Msk
#define JPEGDEC_SWREG61_PP_CLK_GATE_EN_Pos  (8U)
#define JPEGDEC_SWREG61_PP_CLK_GATE_EN_Msk  (0x1UL << JPEGDEC_SWREG61_PP_CLK_GATE_EN_Pos)
#define JPEGDEC_SWREG61_PP_CLK_GATE_EN  JPEGDEC_SWREG61_PP_CLK_GATE_EN_Msk
#define JPEGDEC_SWREG61_PP_DATA_DISC_EN_Pos  (9U)
#define JPEGDEC_SWREG61_PP_DATA_DISC_EN_Msk  (0x1UL << JPEGDEC_SWREG61_PP_DATA_DISC_EN_Pos)
#define JPEGDEC_SWREG61_PP_DATA_DISC_EN  JPEGDEC_SWREG61_PP_DATA_DISC_EN_Msk
#define JPEGDEC_SWREG61_PP_IN_SSWAP32_E_Pos  (10U)
#define JPEGDEC_SWREG61_PP_IN_SSWAP32_E_Msk  (0x1UL << JPEGDEC_SWREG61_PP_IN_SSWAP32_E_Pos)
#define JPEGDEC_SWREG61_PP_IN_SSWAP32_E  JPEGDEC_SWREG61_PP_IN_SSWAP32_E_Msk
#define JPEGDEC_SWREG61_PP_IN_A1_ENDIAN_Pos  (11U)
#define JPEGDEC_SWREG61_PP_IN_A1_ENDIAN_Msk  (0x1UL << JPEGDEC_SWREG61_PP_IN_A1_ENDIAN_Pos)
#define JPEGDEC_SWREG61_PP_IN_A1_ENDIAN  JPEGDEC_SWREG61_PP_IN_A1_ENDIAN_Msk
#define JPEGDEC_SWREG61_PP_IN_A1_SWAP32_Pos  (12U)
#define JPEGDEC_SWREG61_PP_IN_A1_SWAP32_Msk  (0x1UL << JPEGDEC_SWREG61_PP_IN_A1_SWAP32_Pos)
#define JPEGDEC_SWREG61_PP_IN_A1_SWAP32  JPEGDEC_SWREG61_PP_IN_A1_SWAP32_Msk
#define JPEGDEC_SWREG61_PP_IN_A2_ENDSEL_Pos  (13U)
#define JPEGDEC_SWREG61_PP_IN_A2_ENDSEL_Msk  (0x1UL << JPEGDEC_SWREG61_PP_IN_A2_ENDSEL_Pos)
#define JPEGDEC_SWREG61_PP_IN_A2_ENDSEL  JPEGDEC_SWREG61_PP_IN_A2_ENDSEL_Msk
#define JPEGDEC_SWREG61_PP_SCMD_DIS_Pos  (14U)
#define JPEGDEC_SWREG61_PP_SCMD_DIS_Msk  (0x1UL << JPEGDEC_SWREG61_PP_SCMD_DIS_Pos)
#define JPEGDEC_SWREG61_PP_SCMD_DIS     JPEGDEC_SWREG61_PP_SCMD_DIS_Msk
#define JPEGDEC_SWREG61_PP_AHB_HLOCK_EN_Pos  (15U)
#define JPEGDEC_SWREG61_PP_AHB_HLOCK_EN_Msk  (0x1UL << JPEGDEC_SWREG61_PP_AHB_HLOCK_EN_Pos)
#define JPEGDEC_SWREG61_PP_AHB_HLOCK_EN  JPEGDEC_SWREG61_PP_AHB_HLOCK_EN_Msk
#define JPEGDEC_SWREG61_PP_AXI_WR_ID_Pos  (16U)
#define JPEGDEC_SWREG61_PP_AXI_WR_ID_Msk  (0xFFUL << JPEGDEC_SWREG61_PP_AXI_WR_ID_Pos)
#define JPEGDEC_SWREG61_PP_AXI_WR_ID    JPEGDEC_SWREG61_PP_AXI_WR_ID_Msk
#define JPEGDEC_SWREG61_PP_AXI_RD_ID_Pos  (24U)
#define JPEGDEC_SWREG61_PP_AXI_RD_ID_Msk  (0xFFUL << JPEGDEC_SWREG61_PP_AXI_RD_ID_Pos)
#define JPEGDEC_SWREG61_PP_AXI_RD_ID    JPEGDEC_SWREG61_PP_AXI_RD_ID_Msk

/**************** Bit definition for JPEGDEC_SWREG62 register *****************/
#define JPEGDEC_SWREG62_DEINT_EDGE_DET_Pos  (0U)
#define JPEGDEC_SWREG62_DEINT_EDGE_DET_Msk  (0x7FFFUL << JPEGDEC_SWREG62_DEINT_EDGE_DET_Pos)
#define JPEGDEC_SWREG62_DEINT_EDGE_DET  JPEGDEC_SWREG62_DEINT_EDGE_DET_Msk
#define JPEGDEC_SWREG62_DEINT_BLEND_EN_Pos  (15U)
#define JPEGDEC_SWREG62_DEINT_BLEND_EN_Msk  (0x1UL << JPEGDEC_SWREG62_DEINT_BLEND_EN_Pos)
#define JPEGDEC_SWREG62_DEINT_BLEND_EN  JPEGDEC_SWREG62_DEINT_BLEND_EN_Msk
#define JPEGDEC_SWREG62_DEINT_THRESHOLD_Pos  (16U)
#define JPEGDEC_SWREG62_DEINT_THRESHOLD_Msk  (0x3FFFUL << JPEGDEC_SWREG62_DEINT_THRESHOLD_Pos)
#define JPEGDEC_SWREG62_DEINT_THRESHOLD  JPEGDEC_SWREG62_DEINT_THRESHOLD_Msk
#define JPEGDEC_SWREG62_DEINT_EN_Pos    (31U)
#define JPEGDEC_SWREG62_DEINT_EN_Msk    (0x1UL << JPEGDEC_SWREG62_DEINT_EN_Pos)
#define JPEGDEC_SWREG62_DEINT_EN        JPEGDEC_SWREG62_DEINT_EN_Msk

/**************** Bit definition for JPEGDEC_SWREG63 register *****************/
#define JPEGDEC_SWREG63_PP_IN_LU_BASE_Pos  (2U)
#define JPEGDEC_SWREG63_PP_IN_LU_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG63_PP_IN_LU_BASE_Pos)
#define JPEGDEC_SWREG63_PP_IN_LU_BASE   JPEGDEC_SWREG63_PP_IN_LU_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG64 register *****************/
#define JPEGDEC_SWREG64_PP_IN_CB_BASE_Pos  (2U)
#define JPEGDEC_SWREG64_PP_IN_CB_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG64_PP_IN_CB_BASE_Pos)
#define JPEGDEC_SWREG64_PP_IN_CB_BASE   JPEGDEC_SWREG64_PP_IN_CB_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG65 register *****************/
#define JPEGDEC_SWREG65_PP_IN_CR_BASE_Pos  (2U)
#define JPEGDEC_SWREG65_PP_IN_CR_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG65_PP_IN_CR_BASE_Pos)
#define JPEGDEC_SWREG65_PP_IN_CR_BASE   JPEGDEC_SWREG65_PP_IN_CR_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG66 register *****************/
#define JPEGDEC_SWREG66_PP_OUT_LU_BASE_Pos  (2U)
#define JPEGDEC_SWREG66_PP_OUT_LU_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG66_PP_OUT_LU_BASE_Pos)
#define JPEGDEC_SWREG66_PP_OUT_LU_BASE  JPEGDEC_SWREG66_PP_OUT_LU_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG67 register *****************/
#define JPEGDEC_SWREG67_PP_OUT_CH_BASE_Pos  (0U)
#define JPEGDEC_SWREG67_PP_OUT_CH_BASE_Msk  (0xFFFFFFFFUL << JPEGDEC_SWREG67_PP_OUT_CH_BASE_Pos)
#define JPEGDEC_SWREG67_PP_OUT_CH_BASE  JPEGDEC_SWREG67_PP_OUT_CH_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG68 register *****************/
#define JPEGDEC_SWREG68_CONTRAST_OFF1_Pos  (0U)
#define JPEGDEC_SWREG68_CONTRAST_OFF1_Msk  (0x3FFUL << JPEGDEC_SWREG68_CONTRAST_OFF1_Pos)
#define JPEGDEC_SWREG68_CONTRAST_OFF1   JPEGDEC_SWREG68_CONTRAST_OFF1_Msk
#define JPEGDEC_SWREG68_CONTRAST_OFF2_Pos  (10U)
#define JPEGDEC_SWREG68_CONTRAST_OFF2_Msk  (0x3FFUL << JPEGDEC_SWREG68_CONTRAST_OFF2_Pos)
#define JPEGDEC_SWREG68_CONTRAST_OFF2   JPEGDEC_SWREG68_CONTRAST_OFF2_Msk
#define JPEGDEC_SWREG68_CONTRAST_THR1_Pos  (24U)
#define JPEGDEC_SWREG68_CONTRAST_THR1_Msk  (0xFFUL << JPEGDEC_SWREG68_CONTRAST_THR1_Pos)
#define JPEGDEC_SWREG68_CONTRAST_THR1   JPEGDEC_SWREG68_CONTRAST_THR1_Msk

/**************** Bit definition for JPEGDEC_SWREG69 register *****************/
#define JPEGDEC_SWREG69_CONTRAST_THR2_Pos  (0U)
#define JPEGDEC_SWREG69_CONTRAST_THR2_Msk  (0xFFUL << JPEGDEC_SWREG69_CONTRAST_THR2_Pos)
#define JPEGDEC_SWREG69_CONTRAST_THR2   JPEGDEC_SWREG69_CONTRAST_THR2_Msk
#define JPEGDEC_SWREG69_COLOR_COEFFA1_Pos  (8U)
#define JPEGDEC_SWREG69_COLOR_COEFFA1_Msk  (0x3FFUL << JPEGDEC_SWREG69_COLOR_COEFFA1_Pos)
#define JPEGDEC_SWREG69_COLOR_COEFFA1   JPEGDEC_SWREG69_COLOR_COEFFA1_Msk
#define JPEGDEC_SWREG69_COLOR_COEFFA2_Pos  (18U)
#define JPEGDEC_SWREG69_COLOR_COEFFA2_Msk  (0x3FFUL << JPEGDEC_SWREG69_COLOR_COEFFA2_Pos)
#define JPEGDEC_SWREG69_COLOR_COEFFA2   JPEGDEC_SWREG69_COLOR_COEFFA2_Msk
#define JPEGDEC_SWREG69_PP_OUT_CR_FIRST_Pos  (28U)
#define JPEGDEC_SWREG69_PP_OUT_CR_FIRST_Msk  (0x1UL << JPEGDEC_SWREG69_PP_OUT_CR_FIRST_Pos)
#define JPEGDEC_SWREG69_PP_OUT_CR_FIRST  JPEGDEC_SWREG69_PP_OUT_CR_FIRST_Msk
#define JPEGDEC_SWREG69_PP_OUT_START_CH_Pos  (29U)
#define JPEGDEC_SWREG69_PP_OUT_START_CH_Msk  (0x1UL << JPEGDEC_SWREG69_PP_OUT_START_CH_Pos)
#define JPEGDEC_SWREG69_PP_OUT_START_CH  JPEGDEC_SWREG69_PP_OUT_START_CH_Msk
#define JPEGDEC_SWREG69_PP_IN_CR_FIRST_Pos  (30U)
#define JPEGDEC_SWREG69_PP_IN_CR_FIRST_Msk  (0x1UL << JPEGDEC_SWREG69_PP_IN_CR_FIRST_Pos)
#define JPEGDEC_SWREG69_PP_IN_CR_FIRST  JPEGDEC_SWREG69_PP_IN_CR_FIRST_Msk
#define JPEGDEC_SWREG69_PP_IN_START_CH_Pos  (31U)
#define JPEGDEC_SWREG69_PP_IN_START_CH_Msk  (0x1UL << JPEGDEC_SWREG69_PP_IN_START_CH_Pos)
#define JPEGDEC_SWREG69_PP_IN_START_CH  JPEGDEC_SWREG69_PP_IN_START_CH_Msk

/**************** Bit definition for JPEGDEC_SWREG70 register *****************/
#define JPEGDEC_SWREG70_COLOR_COEFFB_Pos  (0U)
#define JPEGDEC_SWREG70_COLOR_COEFFB_Msk  (0x3FFUL << JPEGDEC_SWREG70_COLOR_COEFFB_Pos)
#define JPEGDEC_SWREG70_COLOR_COEFFB    JPEGDEC_SWREG70_COLOR_COEFFB_Msk
#define JPEGDEC_SWREG70_COLOR_COEFFC_Pos  (10U)
#define JPEGDEC_SWREG70_COLOR_COEFFC_Msk  (0x3FFUL << JPEGDEC_SWREG70_COLOR_COEFFC_Pos)
#define JPEGDEC_SWREG70_COLOR_COEFFC    JPEGDEC_SWREG70_COLOR_COEFFC_Msk
#define JPEGDEC_SWREG70_COLOR_COEFFD_Pos  (20U)
#define JPEGDEC_SWREG70_COLOR_COEFFD_Msk  (0x3FFUL << JPEGDEC_SWREG70_COLOR_COEFFD_Pos)
#define JPEGDEC_SWREG70_COLOR_COEFFD    JPEGDEC_SWREG70_COLOR_COEFFD_Msk
#define JPEGDEC_SWREG70_PP_OUT_H_EXT_Pos  (30U)
#define JPEGDEC_SWREG70_PP_OUT_H_EXT_Msk  (0x3UL << JPEGDEC_SWREG70_PP_OUT_H_EXT_Pos)
#define JPEGDEC_SWREG70_PP_OUT_H_EXT    JPEGDEC_SWREG70_PP_OUT_H_EXT_Msk

/**************** Bit definition for JPEGDEC_SWREG71 register *****************/
#define JPEGDEC_SWREG71_COLOR_COEFFE_Pos  (0U)
#define JPEGDEC_SWREG71_COLOR_COEFFE_Msk  (0x3FFUL << JPEGDEC_SWREG71_COLOR_COEFFE_Pos)
#define JPEGDEC_SWREG71_COLOR_COEFFE    JPEGDEC_SWREG71_COLOR_COEFFE_Msk
#define JPEGDEC_SWREG71_COLOR_COEFFF_Pos  (10U)
#define JPEGDEC_SWREG71_COLOR_COEFFF_Msk  (0xFFUL << JPEGDEC_SWREG71_COLOR_COEFFF_Pos)
#define JPEGDEC_SWREG71_COLOR_COEFFF    JPEGDEC_SWREG71_COLOR_COEFFF_Msk
#define JPEGDEC_SWREG71_ROTATION_MODE_Pos  (18U)
#define JPEGDEC_SWREG71_ROTATION_MODE_Msk  (0x7UL << JPEGDEC_SWREG71_ROTATION_MODE_Pos)
#define JPEGDEC_SWREG71_ROTATION_MODE   JPEGDEC_SWREG71_ROTATION_MODE_Msk
#define JPEGDEC_SWREG71_CROP_STARTX_Pos  (21U)
#define JPEGDEC_SWREG71_CROP_STARTX_Msk  (0x1FFUL << JPEGDEC_SWREG71_CROP_STARTX_Pos)
#define JPEGDEC_SWREG71_CROP_STARTX     JPEGDEC_SWREG71_CROP_STARTX_Msk
#define JPEGDEC_SWREG71_PP_OUT_W_EXT_Pos  (30U)
#define JPEGDEC_SWREG71_PP_OUT_W_EXT_Msk  (0x3UL << JPEGDEC_SWREG71_PP_OUT_W_EXT_Pos)
#define JPEGDEC_SWREG71_PP_OUT_W_EXT    JPEGDEC_SWREG71_PP_OUT_W_EXT_Msk

/**************** Bit definition for JPEGDEC_SWREG72 register *****************/
#define JPEGDEC_SWREG72_PP_IN_WIDTH_Pos  (0U)
#define JPEGDEC_SWREG72_PP_IN_WIDTH_Msk  (0x1FFUL << JPEGDEC_SWREG72_PP_IN_WIDTH_Pos)
#define JPEGDEC_SWREG72_PP_IN_WIDTH     JPEGDEC_SWREG72_PP_IN_WIDTH_Msk
#define JPEGDEC_SWREG72_PP_IN_HEIGHT_Pos  (9U)
#define JPEGDEC_SWREG72_PP_IN_HEIGHT_Msk  (0xFFUL << JPEGDEC_SWREG72_PP_IN_HEIGHT_Pos)
#define JPEGDEC_SWREG72_PP_IN_HEIGHT    JPEGDEC_SWREG72_PP_IN_HEIGHT_Msk
#define JPEGDEC_SWREG72_RANGEMAP_COEF_Y_Pos  (18U)
#define JPEGDEC_SWREG72_RANGEMAP_COEF_Y_Msk  (0x1FUL << JPEGDEC_SWREG72_RANGEMAP_COEF_Y_Pos)
#define JPEGDEC_SWREG72_RANGEMAP_COEF_Y  JPEGDEC_SWREG72_RANGEMAP_COEF_Y_Msk
#define JPEGDEC_SWREG72_CROP_STARTY_Pos  (24U)
#define JPEGDEC_SWREG72_CROP_STARTY_Msk  (0xFFUL << JPEGDEC_SWREG72_CROP_STARTY_Pos)
#define JPEGDEC_SWREG72_CROP_STARTY     JPEGDEC_SWREG72_CROP_STARTY_Msk

/**************** Bit definition for JPEGDEC_SWREG73 register *****************/
#define JPEGDEC_SWREG73_PP_BOT_YIN_BASE_Pos  (2U)
#define JPEGDEC_SWREG73_PP_BOT_YIN_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG73_PP_BOT_YIN_BASE_Pos)
#define JPEGDEC_SWREG73_PP_BOT_YIN_BASE  JPEGDEC_SWREG73_PP_BOT_YIN_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG74 register *****************/
#define JPEGDEC_SWREG74_PP_BOT_CIN_BASE_Pos  (2U)
#define JPEGDEC_SWREG74_PP_BOT_CIN_BASE_Msk  (0x3FFFFFFFUL << JPEGDEC_SWREG74_PP_BOT_CIN_BASE_Pos)
#define JPEGDEC_SWREG74_PP_BOT_CIN_BASE  JPEGDEC_SWREG74_PP_BOT_CIN_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG79 register *****************/
#define JPEGDEC_SWREG79_SCALE_WRATIO_Pos  (0U)
#define JPEGDEC_SWREG79_SCALE_WRATIO_Msk  (0x3FFFFUL << JPEGDEC_SWREG79_SCALE_WRATIO_Pos)
#define JPEGDEC_SWREG79_SCALE_WRATIO    JPEGDEC_SWREG79_SCALE_WRATIO_Msk
#define JPEGDEC_SWREG79_RGB_G_PADD_Pos  (18U)
#define JPEGDEC_SWREG79_RGB_G_PADD_Msk  (0x1FUL << JPEGDEC_SWREG79_RGB_G_PADD_Pos)
#define JPEGDEC_SWREG79_RGB_G_PADD      JPEGDEC_SWREG79_RGB_G_PADD_Msk
#define JPEGDEC_SWREG79_RGB_R_PADD_Pos  (23U)
#define JPEGDEC_SWREG79_RGB_R_PADD_Msk  (0x1FUL << JPEGDEC_SWREG79_RGB_R_PADD_Pos)
#define JPEGDEC_SWREG79_RGB_R_PADD      JPEGDEC_SWREG79_RGB_R_PADD_Msk
#define JPEGDEC_SWREG79_RGB_PIX_IN32_Pos  (28U)
#define JPEGDEC_SWREG79_RGB_PIX_IN32_Msk  (0x1UL << JPEGDEC_SWREG79_RGB_PIX_IN32_Pos)
#define JPEGDEC_SWREG79_RGB_PIX_IN32    JPEGDEC_SWREG79_RGB_PIX_IN32_Msk
#define JPEGDEC_SWREG79_YCBCR_RANGE_Pos  (29U)
#define JPEGDEC_SWREG79_YCBCR_RANGE_Msk  (0x1UL << JPEGDEC_SWREG79_YCBCR_RANGE_Pos)
#define JPEGDEC_SWREG79_YCBCR_RANGE     JPEGDEC_SWREG79_YCBCR_RANGE_Msk
#define JPEGDEC_SWREG79_RANGEMAP_C_EN_Pos  (30U)
#define JPEGDEC_SWREG79_RANGEMAP_C_EN_Msk  (0x1UL << JPEGDEC_SWREG79_RANGEMAP_C_EN_Pos)
#define JPEGDEC_SWREG79_RANGEMAP_C_EN   JPEGDEC_SWREG79_RANGEMAP_C_EN_Msk
#define JPEGDEC_SWREG79_RANGEMAP_Y_EN_Pos  (31U)
#define JPEGDEC_SWREG79_RANGEMAP_Y_EN_Msk  (0x1UL << JPEGDEC_SWREG79_RANGEMAP_Y_EN_Pos)
#define JPEGDEC_SWREG79_RANGEMAP_Y_EN   JPEGDEC_SWREG79_RANGEMAP_Y_EN_Msk

/**************** Bit definition for JPEGDEC_SWREG80 register *****************/
#define JPEGDEC_SWREG80_SCALE_HRATION_Pos  (0U)
#define JPEGDEC_SWREG80_SCALE_HRATION_Msk  (0x3FFFFUL << JPEGDEC_SWREG80_SCALE_HRATION_Pos)
#define JPEGDEC_SWREG80_SCALE_HRATION   JPEGDEC_SWREG80_SCALE_HRATION_Msk
#define JPEGDEC_SWREG80_RGB_B_PADD_Pos  (18U)
#define JPEGDEC_SWREG80_RGB_B_PADD_Msk  (0x1FUL << JPEGDEC_SWREG80_RGB_B_PADD_Pos)
#define JPEGDEC_SWREG80_RGB_B_PADD      JPEGDEC_SWREG80_RGB_B_PADD_Msk
#define JPEGDEC_SWREG80_VER_SCALE_MODE_Pos  (23U)
#define JPEGDEC_SWREG80_VER_SCALE_MODE_Msk  (0x3UL << JPEGDEC_SWREG80_VER_SCALE_MODE_Pos)
#define JPEGDEC_SWREG80_VER_SCALE_MODE  JPEGDEC_SWREG80_VER_SCALE_MODE_Msk
#define JPEGDEC_SWREG80_HOR_SCALE_MODE_Pos  (25U)
#define JPEGDEC_SWREG80_HOR_SCALE_MODE_Msk  (0x3UL << JPEGDEC_SWREG80_HOR_SCALE_MODE_Pos)
#define JPEGDEC_SWREG80_HOR_SCALE_MODE  JPEGDEC_SWREG80_HOR_SCALE_MODE_Msk
#define JPEGDEC_SWREG80_PP_IN_STRUCT_Pos  (27U)
#define JPEGDEC_SWREG80_PP_IN_STRUCT_Msk  (0x7UL << JPEGDEC_SWREG80_PP_IN_STRUCT_Pos)
#define JPEGDEC_SWREG80_PP_IN_STRUCT    JPEGDEC_SWREG80_PP_IN_STRUCT_Msk
#define JPEGDEC_SWREG80_PP_FAST_SCALE_EN_Pos  (30U)
#define JPEGDEC_SWREG80_PP_FAST_SCALE_EN_Msk  (0x1UL << JPEGDEC_SWREG80_PP_FAST_SCALE_EN_Pos)
#define JPEGDEC_SWREG80_PP_FAST_SCALE_EN  JPEGDEC_SWREG80_PP_FAST_SCALE_EN_Msk

/**************** Bit definition for JPEGDEC_SWREG81 register *****************/
#define JPEGDEC_SWREG81_HSCALE_INVRA_Pos  (0U)
#define JPEGDEC_SWREG81_HSCALE_INVRA_Msk  (0xFFFFUL << JPEGDEC_SWREG81_HSCALE_INVRA_Pos)
#define JPEGDEC_SWREG81_HSCALE_INVRA    JPEGDEC_SWREG81_HSCALE_INVRA_Msk
#define JPEGDEC_SWREG81_WSCALE_INVRA_Pos  (16U)
#define JPEGDEC_SWREG81_WSCALE_INVRA_Msk  (0xFFFFUL << JPEGDEC_SWREG81_WSCALE_INVRA_Pos)
#define JPEGDEC_SWREG81_WSCALE_INVRA    JPEGDEC_SWREG81_WSCALE_INVRA_Msk

/**************** Bit definition for JPEGDEC_SWREG82 register *****************/
#define JPEGDEC_SWREG82_R_MASK_Pos      (0U)
#define JPEGDEC_SWREG82_R_MASK_Msk      (0xFFFFFFFFUL << JPEGDEC_SWREG82_R_MASK_Pos)
#define JPEGDEC_SWREG82_R_MASK          JPEGDEC_SWREG82_R_MASK_Msk

/**************** Bit definition for JPEGDEC_SWREG83 register *****************/
#define JPEGDEC_SWREG83_G_MASK_Pos      (0U)
#define JPEGDEC_SWREG83_G_MASK_Msk      (0xFFFFFFFFUL << JPEGDEC_SWREG83_G_MASK_Pos)
#define JPEGDEC_SWREG83_G_MASK          JPEGDEC_SWREG83_G_MASK_Msk

/**************** Bit definition for JPEGDEC_SWREG84 register *****************/
#define JPEGDEC_SWREG84_B_MASK_Pos      (0U)
#define JPEGDEC_SWREG84_B_MASK_Msk      (0xFFFFFFFFUL << JPEGDEC_SWREG84_B_MASK_Pos)
#define JPEGDEC_SWREG84_B_MASK          JPEGDEC_SWREG84_B_MASK_Msk

/**************** Bit definition for JPEGDEC_SWREG85 register *****************/
#define JPEGDEC_SWREG85_PP_CROP8_D_E_Pos  (0U)
#define JPEGDEC_SWREG85_PP_CROP8_D_E_Msk  (0x1UL << JPEGDEC_SWREG85_PP_CROP8_D_E_Pos)
#define JPEGDEC_SWREG85_PP_CROP8_D_E    JPEGDEC_SWREG85_PP_CROP8_D_E_Msk
#define JPEGDEC_SWREG85_CROP8_R_E_Pos   (1U)
#define JPEGDEC_SWREG85_CROP8_R_E_Msk   (0x1UL << JPEGDEC_SWREG85_CROP8_R_E_Pos)
#define JPEGDEC_SWREG85_CROP8_R_E       JPEGDEC_SWREG85_CROP8_R_E_Msk
#define JPEGDEC_SWREG85_PP_OUT_SWAP16_E_Pos  (2U)
#define JPEGDEC_SWREG85_PP_OUT_SWAP16_E_Msk  (0x1UL << JPEGDEC_SWREG85_PP_OUT_SWAP16_E_Pos)
#define JPEGDEC_SWREG85_PP_OUT_SWAP16_E  JPEGDEC_SWREG85_PP_OUT_SWAP16_E_Msk
#define JPEGDEC_SWREG85_PP_OUT_TILED_E_Pos  (3U)
#define JPEGDEC_SWREG85_PP_OUT_TILED_E_Msk  (0x1UL << JPEGDEC_SWREG85_PP_OUT_TILED_E_Pos)
#define JPEGDEC_SWREG85_PP_OUT_TILED_E  JPEGDEC_SWREG85_PP_OUT_TILED_E_Msk
#define JPEGDEC_SWREG85_PP_OUT_WIDTH_Pos  (4U)
#define JPEGDEC_SWREG85_PP_OUT_WIDTH_Msk  (0x7FFUL << JPEGDEC_SWREG85_PP_OUT_WIDTH_Pos)
#define JPEGDEC_SWREG85_PP_OUT_WIDTH    JPEGDEC_SWREG85_PP_OUT_WIDTH_Msk
#define JPEGDEC_SWREG85_PP_OUT_HEIGHT_Pos  (15U)
#define JPEGDEC_SWREG85_PP_OUT_HEIGHT_Msk  (0x7FFUL << JPEGDEC_SWREG85_PP_OUT_HEIGHT_Pos)
#define JPEGDEC_SWREG85_PP_OUT_HEIGHT   JPEGDEC_SWREG85_PP_OUT_HEIGHT_Msk
#define JPEGDEC_SWREG85_PP_OUT_FORMAT_Pos  (26U)
#define JPEGDEC_SWREG85_PP_OUT_FORMAT_Msk  (0x7UL << JPEGDEC_SWREG85_PP_OUT_FORMAT_Pos)
#define JPEGDEC_SWREG85_PP_OUT_FORMAT   JPEGDEC_SWREG85_PP_OUT_FORMAT_Msk
#define JPEGDEC_SWREG85_PP_IN_FORMAT_Pos  (29U)
#define JPEGDEC_SWREG85_PP_IN_FORMAT_Msk  (0x7UL << JPEGDEC_SWREG85_PP_IN_FORMAT_Pos)
#define JPEGDEC_SWREG85_PP_IN_FORMAT    JPEGDEC_SWREG85_PP_IN_FORMAT_Msk

/**************** Bit definition for JPEGDEC_SWREG86 register *****************/
#define JPEGDEC_SWREG86_MASK1_STARTX_Pos  (0U)
#define JPEGDEC_SWREG86_MASK1_STARTX_Msk  (0x7FFUL << JPEGDEC_SWREG86_MASK1_STARTX_Pos)
#define JPEGDEC_SWREG86_MASK1_STARTX    JPEGDEC_SWREG86_MASK1_STARTX_Msk
#define JPEGDEC_SWREG86_MASK1_STARTY_Pos  (11U)
#define JPEGDEC_SWREG86_MASK1_STARTY_Msk  (0x7FFUL << JPEGDEC_SWREG86_MASK1_STARTY_Pos)
#define JPEGDEC_SWREG86_MASK1_STARTY    JPEGDEC_SWREG86_MASK1_STARTY_Msk
#define JPEGDEC_SWREG86_MASK1_ABLEND_EN_Pos  (22U)
#define JPEGDEC_SWREG86_MASK1_ABLEND_EN_Msk  (0x1UL << JPEGDEC_SWREG86_MASK1_ABLEND_EN_Pos)
#define JPEGDEC_SWREG86_MASK1_ABLEND_EN  JPEGDEC_SWREG86_MASK1_ABLEND_EN_Msk
#define JPEGDEC_SWREG86_RANGMAP_COEF_C_Pos  (23U)
#define JPEGDEC_SWREG86_RANGMAP_COEF_C_Msk  (0x1FUL << JPEGDEC_SWREG86_RANGMAP_COEF_C_Pos)
#define JPEGDEC_SWREG86_RANGMAP_COEF_C  JPEGDEC_SWREG86_RANGMAP_COEF_C_Msk
#define JPEGDEC_SWREG86_PP_VC1_ADV_E_Pos  (28U)
#define JPEGDEC_SWREG86_PP_VC1_ADV_E_Msk  (0x1UL << JPEGDEC_SWREG86_PP_VC1_ADV_E_Pos)
#define JPEGDEC_SWREG86_PP_VC1_ADV_E    JPEGDEC_SWREG86_PP_VC1_ADV_E_Msk
#define JPEGDEC_SWREG86_PP_IN_FORMAT_ES_Pos  (29U)
#define JPEGDEC_SWREG86_PP_IN_FORMAT_ES_Msk  (0x7UL << JPEGDEC_SWREG86_PP_IN_FORMAT_ES_Pos)
#define JPEGDEC_SWREG86_PP_IN_FORMAT_ES  JPEGDEC_SWREG86_PP_IN_FORMAT_ES_Msk

/**************** Bit definition for JPEGDEC_SWREG87 register *****************/
#define JPEGDEC_SWREG87_MASK2_STARTX_Pos  (0U)
#define JPEGDEC_SWREG87_MASK2_STARTX_Msk  (0x7FFUL << JPEGDEC_SWREG87_MASK2_STARTX_Pos)
#define JPEGDEC_SWREG87_MASK2_STARTX    JPEGDEC_SWREG87_MASK2_STARTX_Msk
#define JPEGDEC_SWREG87_MASK2_STARTY_Pos  (11U)
#define JPEGDEC_SWREG87_MASK2_STARTY_Msk  (0x7FFUL << JPEGDEC_SWREG87_MASK2_STARTY_Pos)
#define JPEGDEC_SWREG87_MASK2_STARTY    JPEGDEC_SWREG87_MASK2_STARTY_Msk
#define JPEGDEC_SWREG87_MASK2_ABLEND_E_Pos  (22U)
#define JPEGDEC_SWREG87_MASK2_ABLEND_E_Msk  (0x1UL << JPEGDEC_SWREG87_MASK2_ABLEND_E_Pos)
#define JPEGDEC_SWREG87_MASK2_ABLEND_E  JPEGDEC_SWREG87_MASK2_ABLEND_E_Msk
#define JPEGDEC_SWREG87_MASK2_STARTY_EXT_Pos  (23U)
#define JPEGDEC_SWREG87_MASK2_STARTY_EXT_Msk  (0x3UL << JPEGDEC_SWREG87_MASK2_STARTY_EXT_Pos)
#define JPEGDEC_SWREG87_MASK2_STARTY_EXT  JPEGDEC_SWREG87_MASK2_STARTY_EXT_Msk
#define JPEGDEC_SWREG87_MASK2_STARTX_EXT_Pos  (25U)
#define JPEGDEC_SWREG87_MASK2_STARTX_EXT_Msk  (0x3UL << JPEGDEC_SWREG87_MASK2_STARTX_EXT_Pos)
#define JPEGDEC_SWREG87_MASK2_STARTX_EXT  JPEGDEC_SWREG87_MASK2_STARTX_EXT_Msk
#define JPEGDEC_SWREG87_MASK1_STARTY_EXT_Pos  (27U)
#define JPEGDEC_SWREG87_MASK1_STARTY_EXT_Msk  (0x3UL << JPEGDEC_SWREG87_MASK1_STARTY_EXT_Pos)
#define JPEGDEC_SWREG87_MASK1_STARTY_EXT  JPEGDEC_SWREG87_MASK1_STARTY_EXT_Msk
#define JPEGDEC_SWREG87_MASK1_STARTX_EXT_Pos  (29U)
#define JPEGDEC_SWREG87_MASK1_STARTX_EXT_Msk  (0x3UL << JPEGDEC_SWREG87_MASK1_STARTX_EXT_Pos)
#define JPEGDEC_SWREG87_MASK1_STARTX_EXT  JPEGDEC_SWREG87_MASK1_STARTX_EXT_Msk

/**************** Bit definition for JPEGDEC_SWREG88 register *****************/
#define JPEGDEC_SWREG88_MASK1_ENDX_Pos  (0U)
#define JPEGDEC_SWREG88_MASK1_ENDX_Msk  (0x7FFUL << JPEGDEC_SWREG88_MASK1_ENDX_Pos)
#define JPEGDEC_SWREG88_MASK1_ENDX      JPEGDEC_SWREG88_MASK1_ENDX_Msk
#define JPEGDEC_SWREG88_MASK1_ENDY_Pos  (11U)
#define JPEGDEC_SWREG88_MASK1_ENDY_Msk  (0x7FFUL << JPEGDEC_SWREG88_MASK1_ENDY_Pos)
#define JPEGDEC_SWREG88_MASK1_ENDY      JPEGDEC_SWREG88_MASK1_ENDY_Msk
#define JPEGDEC_SWREG88_MASK1_E_Pos     (22U)
#define JPEGDEC_SWREG88_MASK1_E_Msk     (0x1UL << JPEGDEC_SWREG88_MASK1_E_Pos)
#define JPEGDEC_SWREG88_MASK1_E         JPEGDEC_SWREG88_MASK1_E_Msk
#define JPEGDEC_SWREG88_EXT_ORIG_WIDTH_Pos  (23U)
#define JPEGDEC_SWREG88_EXT_ORIG_WIDTH_Msk  (0x1FFUL << JPEGDEC_SWREG88_EXT_ORIG_WIDTH_Pos)
#define JPEGDEC_SWREG88_EXT_ORIG_WIDTH  JPEGDEC_SWREG88_EXT_ORIG_WIDTH_Msk

/**************** Bit definition for JPEGDEC_SWREG89 register *****************/
#define JPEGDEC_SWREG89_MASK2_ENDX_Pos  (0U)
#define JPEGDEC_SWREG89_MASK2_ENDX_Msk  (0x7FFUL << JPEGDEC_SWREG89_MASK2_ENDX_Pos)
#define JPEGDEC_SWREG89_MASK2_ENDX      JPEGDEC_SWREG89_MASK2_ENDX_Msk
#define JPEGDEC_SWREG89_MASK2_ENDY_Pos  (11U)
#define JPEGDEC_SWREG89_MASK2_ENDY_Msk  (0x7FFUL << JPEGDEC_SWREG89_MASK2_ENDY_Pos)
#define JPEGDEC_SWREG89_MASK2_ENDY      JPEGDEC_SWREG89_MASK2_ENDY_Msk
#define JPEGDEC_SWREG89_MASK2_EN_Pos    (22U)
#define JPEGDEC_SWREG89_MASK2_EN_Msk    (0x1UL << JPEGDEC_SWREG89_MASK2_EN_Pos)
#define JPEGDEC_SWREG89_MASK2_EN        JPEGDEC_SWREG89_MASK2_EN_Msk
#define JPEGDEC_SWREG89_MASK2_ENDY_EXT_Pos  (23U)
#define JPEGDEC_SWREG89_MASK2_ENDY_EXT_Msk  (0x3UL << JPEGDEC_SWREG89_MASK2_ENDY_EXT_Pos)
#define JPEGDEC_SWREG89_MASK2_ENDY_EXT  JPEGDEC_SWREG89_MASK2_ENDY_EXT_Msk
#define JPEGDEC_SWREG89_MASK2_ENDX_EXT_Pos  (25U)
#define JPEGDEC_SWREG89_MASK2_ENDX_EXT_Msk  (0x3UL << JPEGDEC_SWREG89_MASK2_ENDX_EXT_Pos)
#define JPEGDEC_SWREG89_MASK2_ENDX_EXT  JPEGDEC_SWREG89_MASK2_ENDX_EXT_Msk
#define JPEGDEC_SWREG89_MASK1_ENDY_EXT_Pos  (27U)
#define JPEGDEC_SWREG89_MASK1_ENDY_EXT_Msk  (0x3UL << JPEGDEC_SWREG89_MASK1_ENDY_EXT_Pos)
#define JPEGDEC_SWREG89_MASK1_ENDY_EXT  JPEGDEC_SWREG89_MASK1_ENDY_EXT_Msk
#define JPEGDEC_SWREG89_MASK1_ENDX_EXT_Pos  (29U)
#define JPEGDEC_SWREG89_MASK1_ENDX_EXT_Msk  (0x3UL << JPEGDEC_SWREG89_MASK1_ENDX_EXT_Pos)
#define JPEGDEC_SWREG89_MASK1_ENDX_EXT  JPEGDEC_SWREG89_MASK1_ENDX_EXT_Msk

/**************** Bit definition for JPEGDEC_SWREG90 register *****************/
#define JPEGDEC_SWREG90_DOWN_CROSS_Pos  (0U)
#define JPEGDEC_SWREG90_DOWN_CROSS_Msk  (0x7FFUL << JPEGDEC_SWREG90_DOWN_CROSS_Pos)
#define JPEGDEC_SWREG90_DOWN_CROSS      JPEGDEC_SWREG90_DOWN_CROSS_Msk
#define JPEGDEC_SWREG90_DOWN_CROSS_EXT_Pos  (11U)
#define JPEGDEC_SWREG90_DOWN_CROSS_EXT_Msk  (0x3UL << JPEGDEC_SWREG90_DOWN_CROSS_EXT_Pos)
#define JPEGDEC_SWREG90_DOWN_CROSS_EXT  JPEGDEC_SWREG90_DOWN_CROSS_EXT_Msk
#define JPEGDEC_SWREG90_UP_CROSS_Pos  (15U)
#define JPEGDEC_SWREG90_UP_CROSS_Msk  (0x7FFUL << JPEGDEC_SWREG90_UP_CROSS_Pos)
#define JPEGDEC_SWREG90_UP_CROSS     JPEGDEC_SWREG90_UP_CROSS_Msk
#define JPEGDEC_SWREG90_DOWN_CROSS_EN_Pos  (26U)
#define JPEGDEC_SWREG90_DOWN_CROSS_EN_Msk  (0x1UL << JPEGDEC_SWREG90_DOWN_CROSS_EN_Pos)
#define JPEGDEC_SWREG90_DOWN_CROSS_EN   JPEGDEC_SWREG90_DOWN_CROSS_EN_Msk
#define JPEGDEC_SWREG90_UP_CROSS_EN_Pos  (27U)
#define JPEGDEC_SWREG90_UP_CROSS_EN_Msk  (0x1UL << JPEGDEC_SWREG90_UP_CROSS_EN_Pos)
#define JPEGDEC_SWREG90_UP_CROSS_EN     JPEGDEC_SWREG90_UP_CROSS_EN_Msk
#define JPEGDEC_SWREG90_LEFT_CROSS_EN_Pos  (28U)
#define JPEGDEC_SWREG90_LEFT_CROSS_EN_Msk  (0x1UL << JPEGDEC_SWREG90_LEFT_CROSS_EN_Pos)
#define JPEGDEC_SWREG90_LEFT_CROSS_EN   JPEGDEC_SWREG90_LEFT_CROSS_EN_Msk
#define JPEGDEC_SWREG90_RIGHT_CROSS_EN_Pos  (29U)
#define JPEGDEC_SWREG90_RIGHT_CROSS_EN_Msk  (0x1UL << JPEGDEC_SWREG90_RIGHT_CROSS_EN_Pos)
#define JPEGDEC_SWREG90_RIGHT_CROSS_EN  JPEGDEC_SWREG90_RIGHT_CROSS_EN_Msk

/**************** Bit definition for JPEGDEC_SWREG91 register *****************/
#define JPEGDEC_SWREG91_LEFT_CROSS_Pos  (0U)
#define JPEGDEC_SWREG91_LEFT_CROSS_Msk  (0x7FFUL << JPEGDEC_SWREG91_LEFT_CROSS_Pos)
#define JPEGDEC_SWREG91_LEFT_CROSS      JPEGDEC_SWREG91_LEFT_CROSS_Msk
#define JPEGDEC_SWREG91_RIGHT_CROSS_Pos  (11U)
#define JPEGDEC_SWREG91_RIGHT_CROSS_Msk  (0x7FFUL << JPEGDEC_SWREG91_RIGHT_CROSS_Pos)
#define JPEGDEC_SWREG91_RIGHT_CROSS     JPEGDEC_SWREG91_RIGHT_CROSS_Msk
#define JPEGDEC_SWREG91_PP_TILED_MODE_Pos  (22U)
#define JPEGDEC_SWREG91_PP_TILED_MODE_Msk  (0x3UL << JPEGDEC_SWREG91_PP_TILED_MODE_Pos)
#define JPEGDEC_SWREG91_PP_TILED_MODE   JPEGDEC_SWREG91_PP_TILED_MODE_Msk
#define JPEGDEC_SWREG91_DITHER_SELECT_B_Pos  (26U)
#define JPEGDEC_SWREG91_DITHER_SELECT_B_Msk  (0x3UL << JPEGDEC_SWREG91_DITHER_SELECT_B_Pos)
#define JPEGDEC_SWREG91_DITHER_SELECT_B  JPEGDEC_SWREG91_DITHER_SELECT_B_Msk
#define JPEGDEC_SWREG91_DITHER_SELECT_G_Pos  (28U)
#define JPEGDEC_SWREG91_DITHER_SELECT_G_Msk  (0x3UL << JPEGDEC_SWREG91_DITHER_SELECT_G_Pos)
#define JPEGDEC_SWREG91_DITHER_SELECT_G  JPEGDEC_SWREG91_DITHER_SELECT_G_Msk
#define JPEGDEC_SWREG91_DITHER_SELECT_R_Pos  (30U)
#define JPEGDEC_SWREG91_DITHER_SELECT_R_Msk  (0x3UL << JPEGDEC_SWREG91_DITHER_SELECT_R_Pos)
#define JPEGDEC_SWREG91_DITHER_SELECT_R  JPEGDEC_SWREG91_DITHER_SELECT_R_Msk

/**************** Bit definition for JPEGDEC_SWREG92 register *****************/
#define JPEGDEC_SWREG92_DISPLAY_WIDTH_Pos  (0U)
#define JPEGDEC_SWREG92_DISPLAY_WIDTH_Msk  (0x1FFFUL << JPEGDEC_SWREG92_DISPLAY_WIDTH_Pos)
#define JPEGDEC_SWREG92_DISPLAY_WIDTH   JPEGDEC_SWREG92_DISPLAY_WIDTH_Msk
#define JPEGDEC_SWREG92_UP_CROSS_EXT_Pos  (14U)
#define JPEGDEC_SWREG92_UP_CROSS_EXT_Msk  (0x3UL << JPEGDEC_SWREG92_UP_CROSS_EXT_Pos)
#define JPEGDEC_SWREG92_UP_CROSS_EXT    JPEGDEC_SWREG92_UP_CROSS_EXT_Msk
#define JPEGDEC_SWREG92_LEFT_CROSS_EXT_Pos  (16U)
#define JPEGDEC_SWREG92_LEFT_CROSS_EXT_Msk  (0x3UL << JPEGDEC_SWREG92_LEFT_CROSS_EXT_Pos)
#define JPEGDEC_SWREG92_LEFT_CROSS_EXT  JPEGDEC_SWREG92_LEFT_CROSS_EXT_Msk
#define JPEGDEC_SWREG92_RIGHT_CROSS_EXT_Pos  (18U)
#define JPEGDEC_SWREG92_RIGHT_CROSS_EXT_Msk  (0x3UL << JPEGDEC_SWREG92_RIGHT_CROSS_EXT_Pos)
#define JPEGDEC_SWREG92_RIGHT_CROSS_EXT  JPEGDEC_SWREG92_RIGHT_CROSS_EXT_Msk
#define JPEGDEC_SWREG92_CROP_STARTY_EXT_Pos  (20U)
#define JPEGDEC_SWREG92_CROP_STARTY_EXT_Msk  (0x7UL << JPEGDEC_SWREG92_CROP_STARTY_EXT_Pos)
#define JPEGDEC_SWREG92_CROP_STARTY_EXT  JPEGDEC_SWREG92_CROP_STARTY_EXT_Msk
#define JPEGDEC_SWREG92_CROP_STARTX_EXT_Pos  (23U)
#define JPEGDEC_SWREG92_CROP_STARTX_EXT_Msk  (0x7UL << JPEGDEC_SWREG92_CROP_STARTX_EXT_Pos)
#define JPEGDEC_SWREG92_CROP_STARTX_EXT  JPEGDEC_SWREG92_CROP_STARTX_EXT_Msk
#define JPEGDEC_SWREG92_PP_IN_W_EXT_Pos  (26U)
#define JPEGDEC_SWREG92_PP_IN_W_EXT_Msk  (0x7UL << JPEGDEC_SWREG92_PP_IN_W_EXT_Pos)
#define JPEGDEC_SWREG92_PP_IN_W_EXT     JPEGDEC_SWREG92_PP_IN_W_EXT_Msk
#define JPEGDEC_SWREG92_PP_IN_H_EXT_Pos  (29U)
#define JPEGDEC_SWREG92_PP_IN_H_EXT_Msk  (0x7UL << JPEGDEC_SWREG92_PP_IN_H_EXT_Pos)
#define JPEGDEC_SWREG92_PP_IN_H_EXT     JPEGDEC_SWREG92_PP_IN_H_EXT_Msk

/**************** Bit definition for JPEGDEC_SWREG93 register *****************/
#define JPEGDEC_SWREG93_ABLEND1_BASE_Pos  (0U)
#define JPEGDEC_SWREG93_ABLEND1_BASE_Msk  (0xFFFFFFFFUL << JPEGDEC_SWREG93_ABLEND1_BASE_Pos)
#define JPEGDEC_SWREG93_ABLEND1_BASE    JPEGDEC_SWREG93_ABLEND1_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG94 register *****************/
#define JPEGDEC_SWREG94_ABLEND2_BASE_Pos  (0U)
#define JPEGDEC_SWREG94_ABLEND2_BASE_Msk  (0xFFFFFFFFUL << JPEGDEC_SWREG94_ABLEND2_BASE_Pos)
#define JPEGDEC_SWREG94_ABLEND2_BASE    JPEGDEC_SWREG94_ABLEND2_BASE_Msk

/**************** Bit definition for JPEGDEC_SWREG95 register *****************/
#define JPEGDEC_SWREG95_ABLEND1_SCANL_Pos  (0U)
#define JPEGDEC_SWREG95_ABLEND1_SCANL_Msk  (0x1FFFUL << JPEGDEC_SWREG95_ABLEND1_SCANL_Pos)
#define JPEGDEC_SWREG95_ABLEND1_SCANL   JPEGDEC_SWREG95_ABLEND1_SCANL_Msk
#define JPEGDEC_SWREG95_ABLEND2_SCANL_Pos  (13U)
#define JPEGDEC_SWREG95_ABLEND2_SCANL_Msk  (0x1FFFUL << JPEGDEC_SWREG95_ABLEND2_SCANL_Pos)
#define JPEGDEC_SWREG95_ABLEND2_SCANL   JPEGDEC_SWREG95_ABLEND2_SCANL_Msk

/**************** Bit definition for JPEGDEC_SWREG99 register *****************/
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_352_Pos  (12U)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_352_Msk  (0x1UL << JPEGDEC_SWREG99_FUSE_PP_MAXW_352_Pos)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_352  JPEGDEC_SWREG99_FUSE_PP_MAXW_352_Msk
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_720_Pos  (13U)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_720_Msk  (0x1UL << JPEGDEC_SWREG99_FUSE_PP_MAXW_720_Pos)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_720  JPEGDEC_SWREG99_FUSE_PP_MAXW_720_Msk
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_1280_Pos  (14U)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_1280_Msk  (0x1UL << JPEGDEC_SWREG99_FUSE_PP_MAXW_1280_Pos)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_1280  JPEGDEC_SWREG99_FUSE_PP_MAXW_1280_Msk
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_1920_Pos  (15U)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_1920_Msk  (0x1UL << JPEGDEC_SWREG99_FUSE_PP_MAXW_1920_Pos)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_1920  JPEGDEC_SWREG99_FUSE_PP_MAXW_1920_Msk
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_4K_Pos  (16U)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_4K_Msk  (0x1UL << JPEGDEC_SWREG99_FUSE_PP_MAXW_4K_Pos)
#define JPEGDEC_SWREG99_FUSE_PP_MAXW_4K  JPEGDEC_SWREG99_FUSE_PP_MAXW_4K_Msk
#define JPEGDEC_SWREG99_FUSE_PP_ABLEND_Pos  (29U)
#define JPEGDEC_SWREG99_FUSE_PP_ABLEND_Msk  (0x1UL << JPEGDEC_SWREG99_FUSE_PP_ABLEND_Pos)
#define JPEGDEC_SWREG99_FUSE_PP_ABLEND  JPEGDEC_SWREG99_FUSE_PP_ABLEND_Msk
#define JPEGDEC_SWREG99_FUSE_PP_DEINT_Pos  (30U)
#define JPEGDEC_SWREG99_FUSE_PP_DEINT_Msk  (0x1UL << JPEGDEC_SWREG99_FUSE_PP_DEINT_Pos)
#define JPEGDEC_SWREG99_FUSE_PP_DEINT   JPEGDEC_SWREG99_FUSE_PP_DEINT_Msk
#define JPEGDEC_SWREG99_FUSE_PP_PP_Pos  (31U)
#define JPEGDEC_SWREG99_FUSE_PP_PP_Msk  (0x1UL << JPEGDEC_SWREG99_FUSE_PP_PP_Pos)
#define JPEGDEC_SWREG99_FUSE_PP_PP      JPEGDEC_SWREG99_FUSE_PP_PP_Msk

/**************** Bit definition for JPEGDEC_SWREG100 register ****************/
#define JPEGDEC_SWREG100_PPD_MAX_OWIDTH_Pos  (0U)
#define JPEGDEC_SWREG100_PPD_MAX_OWIDTH_Msk  (0x1FFFUL << JPEGDEC_SWREG100_PPD_MAX_OWIDTH_Pos)
#define JPEGDEC_SWREG100_PPD_MAX_OWIDTH  JPEGDEC_SWREG100_PPD_MAX_OWIDTH_Msk
#define JPEGDEC_SWREG100_PPD_IN_TILED_L_Pos  (14U)
#define JPEGDEC_SWREG100_PPD_IN_TILED_L_Msk  (0x3UL << JPEGDEC_SWREG100_PPD_IN_TILED_L_Pos)
#define JPEGDEC_SWREG100_PPD_IN_TILED_L  JPEGDEC_SWREG100_PPD_IN_TILED_L_Msk
#define JPEGDEC_SWREG100_PPD_PP_EXIST_Pos  (16U)
#define JPEGDEC_SWREG100_PPD_PP_EXIST_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_PP_EXIST_Pos)
#define JPEGDEC_SWREG100_PPD_PP_EXIST   JPEGDEC_SWREG100_PPD_PP_EXIST_Msk
#define JPEGDEC_SWREG100_PPD_OBUFF_LEVEL_Pos  (17U)
#define JPEGDEC_SWREG100_PPD_OBUFF_LEVEL_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_OBUFF_LEVEL_Pos)
#define JPEGDEC_SWREG100_PPD_OBUFF_LEVEL  JPEGDEC_SWREG100_PPD_OBUFF_LEVEL_Msk
#define JPEGDEC_SWREG100_PPD_OEN_VERSION_Pos  (18U)
#define JPEGDEC_SWREG100_PPD_OEN_VERSION_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_OEN_VERSION_Pos)
#define JPEGDEC_SWREG100_PPD_OEN_VERSION  JPEGDEC_SWREG100_PPD_OEN_VERSION_Msk
#define JPEGDEC_SWREG100_PPD_STRIPE_REM_Pos  (22U)
#define JPEGDEC_SWREG100_PPD_STRIPE_REM_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_STRIPE_REM_Pos)
#define JPEGDEC_SWREG100_PPD_STRIPE_REM  JPEGDEC_SWREG100_PPD_STRIPE_REM_Msk
#define JPEGDEC_SWREG100_PPD_IBUFF_LEVEL_Pos  (23U)
#define JPEGDEC_SWREG100_PPD_IBUFF_LEVEL_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_IBUFF_LEVEL_Pos)
#define JPEGDEC_SWREG100_PPD_IBUFF_LEVEL  JPEGDEC_SWREG100_PPD_IBUFF_LEVEL_Msk
#define JPEGDEC_SWREG100_PPD_BLEND_EXIST_Pos  (24U)
#define JPEGDEC_SWREG100_PPD_BLEND_EXIST_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_BLEND_EXIST_Pos)
#define JPEGDEC_SWREG100_PPD_BLEND_EXIST  JPEGDEC_SWREG100_PPD_BLEND_EXIST_Msk
#define JPEGDEC_SWREG100_PPD_DEINT_EXIST_Pos  (25U)
#define JPEGDEC_SWREG100_PPD_DEINT_EXIST_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_DEINT_EXIST_Pos)
#define JPEGDEC_SWREG100_PPD_DEINT_EXIST  JPEGDEC_SWREG100_PPD_DEINT_EXIST_Msk
#define JPEGDEC_SWREG100_PPD_SCALE_LEVEL_Pos  (26U)
#define JPEGDEC_SWREG100_PPD_SCALE_LEVEL_Msk  (0x3UL << JPEGDEC_SWREG100_PPD_SCALE_LEVEL_Pos)
#define JPEGDEC_SWREG100_PPD_SCALE_LEVEL  JPEGDEC_SWREG100_PPD_SCALE_LEVEL_Msk
#define JPEGDEC_SWREG100_PPD_DITH_EXIST_Pos  (28U)
#define JPEGDEC_SWREG100_PPD_DITH_EXIST_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_DITH_EXIST_Pos)
#define JPEGDEC_SWREG100_PPD_DITH_EXIST  JPEGDEC_SWREG100_PPD_DITH_EXIST_Msk
#define JPEGDEC_SWREG100_PPD_TILED_EXIST_Pos  (29U)
#define JPEGDEC_SWREG100_PPD_TILED_EXIST_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_TILED_EXIST_Pos)
#define JPEGDEC_SWREG100_PPD_TILED_EXIST  JPEGDEC_SWREG100_PPD_TILED_EXIST_Msk
#define JPEGDEC_SWREG100_PPD_PIXAC_E_Pos  (30U)
#define JPEGDEC_SWREG100_PPD_PIXAC_E_Msk  (0x1UL << JPEGDEC_SWREG100_PPD_PIXAC_E_Pos)
#define JPEGDEC_SWREG100_PPD_PIXAC_E    JPEGDEC_SWREG100_PPD_PIXAC_E_Msk
#define JPEGDEC_SWREG100_ABLEND_CROP_E_Pos  (31U)
#define JPEGDEC_SWREG100_ABLEND_CROP_E_Msk  (0x1UL << JPEGDEC_SWREG100_ABLEND_CROP_E_Pos)
#define JPEGDEC_SWREG100_ABLEND_CROP_E  JPEGDEC_SWREG100_ABLEND_CROP_E_Msk

#endif
