Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('App_utils', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
