from building import * 
import rtconfig

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = [cwd]
lib = []
if GetDepend("DISABLE_LVGL_V9"):
    lib = [GroupLibName("gif_dec")]

obj = DefineGroup('lib_gif_dec', src, depend = [''], CPPPATH = inc, LIBS=lib, LIBPATH=inc)
Return('obj')
