from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

if GetDepend(['BSP_USING_BOARD_EC_LB563XXX']):
    group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_EC_LB563XXX'], CPPPATH = path)
elif GetDepend(['BSP_USING_BOARD_EC_SS6700XXX']):
    group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_EC_SS6700XXX'], CPPPATH = path)
else:
    group = []

Return('group')
