from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_EH_LB555'], CPPPATH = path)

Return('group')
