import os
from building import * 

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = [cwd]


# add driver basic code
src = src + Glob('./*.c')

# add group to IDE project
objs = DefineGroup('middleware', src, depend = ['USING_CMSIS_DSP_ACC'], CPPPATH = inc)

Return('objs')
