from building import *

cwd = GetCurrentDir()
inc = [cwd]
src = Glob('*.c')
lib = [GroupLibName("wfm")]
CPPPATH = [cwd + '/../common', cwd]
group = DefineGroup('Drivers', src, depend = ['LCD_USING_OPM060E9_V10'], CPPPATH = CPPPATH, LIBS=lib, LIBPATH=inc)

Return('group')
