import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

# Add SDK
Import('SIFLI_SDK')
objs.extend(SConscript(os.path.join(SIFLI_SDK, 'SConscript'), variant_dir="sifli_sdk", duplicate=0))

# Add lcpu general code
objs.extend(SConscript(os.path.join(cwd,'../../src/SConscript'), variant_dir="lcpu_general", duplicate=0))

Return('objs')
