Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]
list = os.listdir(cwd)

group = DefineGroup('bt', src, depend = ['BSP_BLE_SIBLES'], CPPPATH = CPPPATH)


Return('group')
