# RT-Thread building script for component

import os
import shutil

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp') 
CPPPATH = [cwd]
CPPDEFINES = ['LFS_CONFIG=lfs_config.h']

group = DefineGroup('littlefs', src, depend = ['RT_USING_LITTLE_FS'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
