from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_586_DEVKIT_DPI'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_586_DEVKIT_DPI'):
    group = group + SConscript('../sf32lb586-devkit-lcd/script/SConscript')

Return('group')
