import os
from building import * 

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = [cwd]


# add driver basic code
src = src + Glob('./*.c')

if GetDepend("DISABLE_LVGL_V8") and GetDepend("DISABLE_LVGL_V9"):
    src = src + Glob('./lvgl_v7/*.c')
else:
    src = src + Glob('./lvgl_v8/*.c')

# add group to IDE project
objs = DefineGroup('app_fwk', src, depend = ['GUI_APP_FRAMEWORK'], CPPPATH = inc)
Return('objs')
