Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('audio', src,depend = ['BSP_USING_PC_SIMULATOR'],CPPPATH = CPPPATH)

Return('group')
