from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')
path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32LB52_ULP'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SF32LB52_ULP'):
    group = group + SConscript('../sf32lb52-ulp_base/script/SConscript')

Return('group')
