Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = ["main.c"]
src += ["sender.c"]
src += ["receiver.c"]
src += ["talk.c"]

CPPPATH = [cwd, str(Dir('#'))]
CPPDEFINES=[]

if GetDepend("SOC_SF32LB55X"):
    src += ["lcpu_img.c"]

try:
    simu = GetOption('simu')
except:
    simu = False

if simu:
    print("Add flag for 52X LCPU simulation")
    CPPDEFINES += ['SF32LB52X_58']
    src += ["lcpu_img.c"]    

group = DefineGroup('App_utils', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
