from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

src	= Glob('*.c')
if not GetDepend('BT_USING_HF'):
    SrcRemove(src, 'bt_rt_device_control_hf.c')
    SrcRemove(src, 'bt_rt_device_urc_hf.c')
if not GetDepend('BT_USING_A2DP'):
    SrcRemove(src, 'bt_rt_device_control_a2dp.c')
    SrcRemove(src, 'bt_rt_device_urc_a2dp.c')
if not GetDepend('BT_USING_SPP'):
    SrcRemove(src, 'bt_rt_device_control_spp.c')
    SrcRemove(src, 'bt_rt_device_urc_spp.c')
if not GetDepend('BT_USING_AVRCP'):
    SrcRemove(src, 'bt_rt_device_control_avrcp.c')
    SrcRemove(src, 'bt_rt_device_urc_avrcp.c')
if not GetDepend('BT_USING_AG'):
    SrcRemove(src, 'bt_rt_device_control_ag.c')
    SrcRemove(src, 'bt_rt_device_urc_ag.c')
if not GetDepend('BT_USING_HID'):
    SrcRemove(src, 'bt_rt_device_control_hid.c')
    SrcRemove(src, 'bt_rt_device_urc_hid.c')
if not GetDepend('BT_USING_PBAP'):
    SrcRemove(src, 'bt_rt_device_control_pbap.c')
    SrcRemove(src, 'bt_rt_device_urc_pbap.c')
if not GetDepend('BT_USING_GATT'):
    SrcRemove(src, 'bt_rt_device_control_gatt.c')
    SrcRemove(src, 'bt_rt_device_urc_gatt.c')

group = DefineGroup('bt', src, depend = ['RT_USING_BT','BT_FINSH'], CPPPATH = CPPPATH)

Return('group')
