from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = ['BSP_USING_PC_SIMULATOR'], CPPPATH = CPPPATH)

Return('group')
