Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = ['main.c']

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('App_utils', src, depend = [''], variant_dir="ble", CPPPATH = CPPPATH)

Return('group')
