from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [cwd]
lib = ['MemsicAlgo']
group = DefineGroup('Drivers', src, depend = ['MAG_USING_MMC36X0KJ'], LIBS = lib, CPPPATH = path, LIBPATH = path)

Return('group')
