#ifndef _IPC_CONFIG_H_
#define _IPC_CONFIG_H_
#include "board.h"

#define IPC_TEST_QUEUE (2)

#define HL_IPC_TX_BUF_ADDR         (HPSYS_MBOX_BUF_ADDR - HL_IPC_TX_BUF_SIZE)   /*  */
#define HL_IPC_TX_BUF_ADDR_ALIAS   (HCPU_ADDR_2_LCPU_ADDR(HL_IPC_TX_BUF_ADDR))
#define HL_IPC_RX_BUF_ADDR         LH_IPC_TX_BUF_ADDR_ALIAS

#define LH_IPC_TX_BUF_ADDR         (LPSYS_RAM_END - LPSYS_MBOX_BUF_SIZE - LH_IPC_TX_BUF_SIZE + 1)
#define LH_IPC_TX_BUF_ADDR_ALIAS   (LCPU_ADDR_2_HCPU_ADDR(LH_IPC_TX_BUF_ADDR))
#define LH_IPC_RX_BUF_ADDR         HL_IPC_TX_BUF_ADDR_ALIAS

#endif /* _IPC_CONFIG_H_ */

