from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32LB56_DEVKIT_LCD_A128R12N1'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SF32LB56_DEVKIT_LCD_A128R12N1'):
    group = group + SConscript('../sf32lb56-devkit-lcd_base/script/SConscript')

Return('group')
