from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, cwd + '/../include']
group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_MOTOR'], CPPPATH = CPPPATH)

Return('group')
