Import('RTT_ROOT')
Import('rtconfig')
import os
import sys
from building import * 

cwd = GetCurrentDir()

src = []
   
if GetDepend('BSP_USING_COMP_SVC'):   
    src += Glob('compass_service.c')
    
if GetDepend('BSP_USING_MAG_SVC'):   
    src += Glob('mag_service.c')
    
if GetDepend('BSP_USING_WEA_SVC'):   
    src += Glob('weather_service.c')
    
if GetDepend('BSP_USING_HR_SVC'):   
    src += Glob('hr_service.c')

if GetDepend('BSP_USING_BARO_SVC'):   
    src += Glob('baro_service.c')

if GetDepend('BSP_USING_ACCE_SVC'):   
    src += Glob('acce_service.c')

if GetDepend('BSP_USING_GYRO_SVC'):   
    src += Glob('gyro_service.c')

if GetDepend('BSP_USING_STEP_SVC'):   
    src += Glob('step_service.c')

if GetDepend('BSP_USING_GPS_SVC'):   
    src += Glob('gps_service.c')
    
   
if GetDepend('BSP_USING_TELEPHONE_SVC'):   
    src += Glob('telephone_service.c')  

if GetDepend('BSP_USING_ALARM_MANAGER_SVC'):
    src += Glob('alarm_manager_service.c')

if GetDepend('BSP_USING_TEST_SVC'):   
    src += ['test/tc_datasvc.c', 'test/test_service.c']
    
group = DefineGroup('service', src, depend = [''])

Return('group')
