import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = []

path =  [cwd]
path += [cwd + './linker_scripts']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
