import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
bf0_ap_hal_msp.c
''')

path =  [cwd]
path += [cwd + '/../linker_scripts']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
Return('group')
