from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../common', cwd]
group = DefineGroup('Drivers', src, depend = ['PA_USING_AW8155'], CPPPATH = CPPPATH)

Return('group')
