from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../../common', cwd]
group = DefineGroup('Drivers', src, depend = ['LCD_USING_CH13613'], CPPPATH = CPPPATH)

Return('group')
