from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')
path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_EM_LB525XXX'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_EM_LB525XXX'):
    group = group + SConscript('../sf32lb52-devkit-lcd/script/SConscript')

Return('group')
