from building import * 
import rtconfig

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = []

# add LittlevGL Sifli watch component common include
inc = inc + [cwd]
inc = inc + [cwd+'/..']

# add LittlevGL Sifli watch component code
src = src + Glob('./*.c')
if not (GetDepend('PKG_USING_UI_BINARY_LOADER') or GetDepend('PKG_USING_UI_XML_LOADER')):
    SrcRemove(src, 'lv_layout_loader.c')

if not GetDepend('LV_USING_FREETYPE_ENGINE'):
    SrcRemove(src, 'lv_freetype.c')

#if not GetDepend(['SOLUTION_WATCH']):
#	src = src + Glob('./resource/*.c')


LOCAL_CCFLAGS = ''

group = DefineGroup('LV_SF', src, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = inc, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
