ren clock_extreme_sports_am_en.bin apm_00.bin
ren clock_extreme_sports_pm_en.bin apm_01.bin
ren clock_extreme_sports_mon_10_en.bin mon_10.bin
ren clock_extreme_sports_mon_11_en.bin mon_11.bin
ren clock_extreme_sports_mon_12_en.bin mon_12.bin
ren clock_extreme_sports_mon_1_en.bin  mon_01.bin
ren clock_extreme_sports_mon_2_en.bin  mon_02.bin
ren clock_extreme_sports_mon_3_en.bin  mon_03.bin
ren clock_extreme_sports_mon_4_en.bin  mon_04.bin
ren clock_extreme_sports_mon_5_en.bin  mon_05.bin
ren clock_extreme_sports_mon_6_en.bin  mon_06.bin
ren clock_extreme_sports_mon_7_en.bin  mon_07.bin
ren clock_extreme_sports_mon_8_en.bin  mon_08.bin
ren clock_extreme_sports_mon_9_en.bin  mon_09.bin
ren clock_extreme_sports_num_0.bin num_00.bin
ren clock_extreme_sports_num_1.bin num_01.bin
ren clock_extreme_sports_num_2.bin num_02.bin
ren clock_extreme_sports_num_3.bin num_03.bin
ren clock_extreme_sports_num_4.bin num_04.bin
ren clock_extreme_sports_num_5.bin num_05.bin
ren clock_extreme_sports_num_6.bin num_06.bin
ren clock_extreme_sports_num_7.bin num_07.bin
ren clock_extreme_sports_num_8.bin num_08.bin
ren clock_extreme_sports_num_9.bin num_09.bin
ren clock_extreme_sports_num_dot.bin num_dot.bin
ren clock_extreme_sports_s_num_0.bin s_num_00.bin
ren clock_extreme_sports_s_num_1.bin s_num_01.bin
ren clock_extreme_sports_s_num_2.bin s_num_02.bin
ren clock_extreme_sports_s_num_3.bin s_num_03.bin
ren clock_extreme_sports_s_num_4.bin s_num_04.bin
ren clock_extreme_sports_s_num_5.bin s_num_05.bin
ren clock_extreme_sports_s_num_6.bin s_num_06.bin
ren clock_extreme_sports_s_num_7.bin s_num_07.bin
ren clock_extreme_sports_s_num_8.bin s_num_08.bin
ren clock_extreme_sports_s_num_9.bin s_num_09.bin
ren clock_extreme_sports_s_num_dot.bin s_num_dot.bin
ren clock_extreme_sports_week_7_en.bin week_00.bin
ren clock_extreme_sports_week_1_en.bin week_01.bin
ren clock_extreme_sports_week_2_en.bin week_02.bin
ren clock_extreme_sports_week_3_en.bin week_03.bin
ren clock_extreme_sports_week_4_en.bin week_04.bin
ren clock_extreme_sports_week_5_en.bin week_05.bin
ren clock_extreme_sports_week_6_en.bin week_06.bin
