import os
from building import * 
import rtconfig

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = [cwd]


# add driver basic code
src = src + Glob('./*.c')

# add group to IDE project
objs = DefineGroup('middleware', src, depend = [], CPPPATH = inc)
Return('objs')
