from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../common', cwd]
group = DefineGroup('Drivers', src, depend = ['TSC_USING_CST816'], CPPPATH = CPPPATH)

Return('group')
