import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

#include all subfolder
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Import('SIFLI_SDK')

#Add test code
objs.extend(SConscript(os.path.join(cwd, '../../src/SConscript'), variant_dir="lcpu_general", duplicate=0))



# Add SDK
objs.extend(SConscript(os.path.join(SIFLI_SDK, 'SConscript'), variant_dir="sifli_sdk", duplicate=0))

# Add rom_sym.lib
objs.extend(SConscript(os.path.join(SIFLI_SDK, 'example/rom_bin/lcpu_boot_loader/SConscript'), variant_dir="lcpu_rom", duplicate=0))

Return('objs')
