from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_EM_LB567XXX'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_EM_LB567XXX'):
    group = group + SConscript('../sf32lb5x-lcd/script/SConscript')

Return('group')
