Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []

if GetDepend("BSP_USING_RTTHREAD"):
    src+= ["os_adaptor_rtthread.c"]

CPPPATH = [cwd]
CPPPATH += [cwd+'/../inc']

group = DefineGroup('os_adapter', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
