Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Example', src, depend = ['APP_HAL_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
