Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = ["main.c"]

if GetDepend("SOC_SF32LB55X"):
    src += ["lcpu_img.c"]

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('App_utils', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
