from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_56_DEVKIT_LCD_NAND'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_56_DEVKIT_LCD_NAND'):
    group = group + SConscript('../sf32lb56-devkit-lcd/script/SConscript')

Return('group')
