import os
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

# Add source code
src = Glob('*.c')
group = DefineGroup('Applications', src, depend = [''],CPPPATH = CPPPATH)

Return('group')
